### ISSUE TITLE
Error "Must use PackageReference"

### ISSUE THREAD

**Issue by b3hdad** [AzureAD/microsoft-authentication-library-for-dotnet#2254] opened 2020-11-29 20:34 UTC
When I upgraded from v4.22.0 to v4.23.0, I get the error "Must use PackageReference" and compilation fails.

**Platform**

.net4.8

**Is this a new or existing app?**
The app is in production, and I have upgraded to a new version of MSAL

**Expected behavior**
Should compile

**Actual behavior**
Fails to compile with the specified error

**Comment by bgavrilMS** [comment] 2020-11-30 11:54
Hi @b3hdad - this is a duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2247

**Closed by bgavrilMS** 2020-11-30 11:54 UTC
Labels: Investigate
