### ISSUE TITLE
[Bug] MSAL OAuth2 + EWS not working

### ISSUE THREAD

**Issue by dsanghan** [AzureAD/microsoft-authentication-library-for-dotnet#1274] opened 2019-07-17 07:31 UTC
**Which Version of MSAL are you using ?**
4.1.0

**Platform**
Net 4.7

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ x ] Interactive

Other? - please describe;

**Is this a new or existing app?**
New App

**Repro**
Follow:
https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-authenticate-an-ews-application-by-using-oauth

Use an outlook.com account to login after setting the audience in above tutorial to support personal and work accounts.

Code sample is included in above tutorial

**Expected behavior**
You see the folders in your mailbox

**Actual behavior**
```
Error: System.ArgumentException: The given token is invalid.
   at Microsoft.Exchange.WebServices.Data.OAuthCredentials..ctor(String token, Boolean verbatim)
   at Microsoft.Exchange.WebServices.Data.OAuthCredentials..ctor(String token)
   at EwsOAuth.Program.<MainAsync>d__1.MoveNext() in C:\Users\dev\source\repos\EWS\EWS\Program.cs:line 43
```

**Possible Solution**

**Additional context/ Logs / Screenshots**
It's really easy to reproduce.

Try logging-in using an outlook.com account.

**Comment by jmprieur** [comment] 2019-07-17 09:51
@dsanghan : 
This does not seem to be an issue with MSAL.NET, but with the sample?

Apparently https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-authenticate-an-ews-application-by-using-oauth forgot to mention that you had to go to the **API permissions** tab, and add a permission to **Exchange** (in the **Supported legacy APIs** section).

BTW, depending on what you want to do, you might want to use the [Microsoft Graph API](https://docs.microsoft.com/en-us/graph/) instead?

**Comment by dsanghan** [comment] 2019-07-17 09:54
@jmprieur: The above sample does work for Exchange Online accounts, but does not work for personal accounts (Outlook.com, etc). I tried adding the API permission you've suggested but that does not fix it. I'm still getting the invalid token error.

AFAIK, Graph doesn't work for on-premises exchange.

**Comment by jmprieur** [comment] 2019-07-17 09:57
@dsanghan : are you hitting on premises exchange? 
Did you use EWS access as user as a scope?

![image](https://user-images.githubusercontent.com/13203188/61366490-f7081a00-a889-11e9-9917-999fbf6101ee.png)

**Comment by dsanghan** [comment] 2019-07-17 10:02
@jmprieur Presently testing with an Office 365 account. But we also want to support on-premises exchange, so don't want to use Graph. 

Yes, here's the permission enabled:
<img width="485" alt="Screen Shot 2019-07-17 at 3 30 51 PM" src="https://user-images.githubusercontent.com/6698354/61366803-e8306000-a8a7-11e9-8c44-4fad4912243f.png">

Also verified that we're asking for the correct scope:
```
var ewsScopes = new string[] { "https://outlook.office.com/EWS.AccessAsUser.All" };
```

**Comment by dsanghan** [comment] 2019-07-17 10:03
To be clear, the token works if I sign in with an Office365 account, but does not work if I sign in with an Outlook account.

**Comment by jmprieur** [comment] 2019-07-17 10:20
@dsanghan : I can repro it as well, and I see that MSAL.NET does it job (it gets an access token), however, this access token is not a standard JWT (it's an MSA token)

OAuthCredentials is probably trying to crack open it (which it should not do as the toke is only for EWS), and this fails.

**Comment by dsanghan** [comment] 2019-07-17 10:26
@jmprieur: Great. Would be great if you could link the issue here once it's opened so I can track it.

**Comment by jmprieur** [comment] 2019-07-17 11:03
@dsanghan : do you want to open an issue on https://github.com/officedev/ews-managed-api ?
I see that they don't take any feature requests, though? 
Maybe you should raise the issue is on the article : https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-authenticate-an-ews-application-by-using-oauth  ?

In any case closing this MSAL.NET (as external) issue as this is not a problem with MSAL

**Closed by jmprieur** 2019-07-17 11:03 UTC
Labels: external

**Comment by dsanghan** [comment] 2019-07-17 11:47
@jmprieur I did open one on https://github.com/officedev/ews-managed-api - but no replies yet.

The issue also happens on different platforms and libraries - I see the same issue on:
https://github.com/AzureAD/microsoft-authentication-library-for-objc

Feels like the backend should be sending a proper JWT instead of MSA token?

Is there a way I can use the MSA token for auth? Is there a way to convert between the two?

**Comment by jmprieur** [comment] 2019-07-17 11:56
The thing is that EWS is legacy technology and they probably use a dual stack (AAD for Work or School account and live for personal accounts). They would need to move their API to the new clean stack, but this would not necessarily work on premise.

The issue here is that OAuthCredentials is trying to validate the token whereas it should not: it's client code and the client shoud **never** look inside a token. It's the Web API's job to validate the token, not the client's job. 
Interestingly looking at the code, OAuthCredentials has an internal constructor that by passes the 'validation' of the token. If you could us it, this would probably work.

**Comment by dsanghan** [comment] 2019-07-17 12:48
Hmm, ok. I tried using the token directly, but that gives a strange 403 - no error description, just a 403 status.

**Comment by guidedways** [comment] 2019-09-23 00:46
Any update on this? Can't get personal Office 365 accounts to work with the MSAL library.

**Comment by jmprieur** [comment] 2019-09-23 06:52
@guidedways : I've contacted people on the Office side. again this is not MSAL, but how the token is being used by ews-managed-api.

**Comment by guidedways** [comment] 2024-02-17 21:22
@jmprieur Is there any workaround for personal Outlook accounts? I see Apple Calendar is able to authenticate and use OAuth somehow
