### ISSUE TITLE
[Bug] Microsoft.Identity.Client 4.48.1 InMemoryPartitionedAppTokenCacheAccessor.SaveRefreshToken throws NotSupportedException

### ISSUE THREAD

**Issue by paujohn** [AzureAD/microsoft-authentication-library-for-dotnet#3861] opened 2022-12-13 16:09 UTC
**Which version of MSAL.NET are you using?**
Microsoft.Identity.Client 4.48.1
Microsoft.Identity.Client.Extensions.Msal 2.25.0
Azure.Identity 1.8.0

**Platform**
.NET 4.7.1

**What authentication flow has the issue?**
During AcquireTokenForClient for a confidential client app.

**Is this a new or existing app?**
a. The app is in production, and I have upgraded to a new version of MSAL.

**Repro**
``` 
TokenCachePersistenceOptions persistenceOptions = new TokenCachePersistenceOptions();
persistenceOptions.UnsafeAllowUnencryptedStorage = false;

ClientCertificateCredentialOptions credentialOptions = new ClientCertificateCredentialOptions
{
    AuthorityHost = new Uri("https://login.microsoftonline.com/"),
    TokenCachePersistenceOptions = persistenceOptions,
};

lock (creationLock)
{
    if (credential == null)
    {
        Tracer?.Trace(TraceCodes.General, "credential is null; creating a new credential instance");
        credential = new ClientCertificateCredential(tenantId, applicationId, cert, credentialOptions);
        
    }
}

return credential; 
```
**Expected behavior**
An access token is retrieved.

**Actual behavior**
InMemoryPartitionedAppTokenCacheAccessor.SaveIdToken throws a NotSupportedException.

**Additional context / logs / screenshots**
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/eb81652247996f8f20205c24923340a4110d71d1/src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/InMemoryPartitionedAppTokenCacheAccessor.cs#L77-L84

Error Stack Trace:
```
exception in DeployTemplate: base exception: System.NotSupportedException: Specified method is not supported.
   at Microsoft.Identity.Client.PlatformsCommon.Shared.InMemoryPartitionedAppTokenCacheAccessor.SaveRefreshToken(MsalRefreshTokenCacheItem item)
   at Microsoft.Identity.Client.Cache.TokenCacheJsonSerializer.Deserialize(Byte[] bytes, Boolean clearExistingCacheData)
   at Microsoft.Identity.Client.TokenCache.Microsoft.Identity.Client.ITokenCacheSerializer.DeserializeMsalV3(Byte[] msalV3State, Boolean shouldClearExistingCache)
   at Microsoft.Identity.Client.Extensions.Msal.MsalCacheHelper.BeforeAccessNotification(TokenCacheNotificationArgs args)
   at Microsoft.Identity.Client.TokenCache.<Microsoft-Identity-Client-ITokenCacheInternal-OnBeforeAccessAsync>d__110.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Cache.CacheSessionManager.<RefreshCacheForReadOperationsAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Identity.Client.Cache.CacheSessionManager.<RefreshCacheForReadOperationsAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Cache.CacheSessionManager.<FindAccessTokenAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.ApiConfig.Executors.ConfidentialClientExecutor.<ExecuteAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Identity.AbstractAcquireTokenParameterBuilderExtensions.<ExecuteAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Identity.MsalConfidentialClient.<AcquireTokenForClientCoreAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Identity.MsalConfidentialClient.<AcquireTokenForClientAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Identity.ClientCertificateCredential.<GetTokenAsync>d__26.MoveNext()
: {0}
```

**Use Case**
We are migrating from the old Azure sdks to the new track2 sdks. While the Azure.Identity library tried to obtain the token, the Microsoft.Identity.Client threw the above error.

**Comment by pmaytak** [comment] 2022-12-13 19:26
This is a duplicate of #3218. Basically it's because the same cache source is shared for app and user tokens. App and user tokens should be in separate files.

@paujohn Which Azure.Identity SDK version do you use?

@bgavrilMS Do you know, does AzureSDK have a work around for this scenario? Like maybe specifying different persistence options for user/app credentials? If so, I can document it. Otherwise, would this have to be a fix on AzureSDKs or our side (as we discussed, right?)

**Comment by paujohn** [comment] 2022-12-13 23:45
@pmaytak using 'persistenceOptionsAux.UnsafeAllowUnencryptedStorage = false;' made the error go away. I guess we can use this as a work around?

**Comment by bgavrilMS** [comment] 2022-12-14 15:30
@paujohn - I assume you're only getting this error on dev boxes? Azure SDK combines user auth with client auth to provide a nice experience for developers. But in production there would only be app auth, i.e. a token is issues based on a certificate. 

Are you testing locally with certificates ? If so, I recommend that you delete Azure SDK's cache file or set the Name property of `persistenceOptions` (not 100% sure about this). 

Correct fix is for Azure SDK to use separate files for user auth and app auth, as per MSAL model. 

CC @schaabs

**Comment by bgavrilMS** [comment] 2022-12-21 15:41
Dup of of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3218

**Closed by bgavrilMS** 2022-12-21 15:41 UTC
Labels: duplicate
