### ISSUE TITLE
MsalServiceException: AADSTS53001: Device is not in required device state: domain_joined.

### ISSUE THREAD

**Issue by rdeveen** [AzureAD/microsoft-authentication-library-for-dotnet#873] opened 2019-02-07 10:21 UTC
**Which Version of MSAL are you using ?**
Microsoft.Identity.Client v2.7.0

**Platform**
UWP

**What authentication flow has the issue?**
* Desktop / Mobile
    * [X] Interactive
    * [X] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Is this a new or existing app?**
The app is in production, I haven't upgraded MSAL, but started seeing this issue. The [conditional access policy](https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/require-managed-devices) to make sure de device is domain joined has been added to AAD.

**Repro**
* Enable the conditional access policy.
https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/media/require-managed-devices/10.png
* On a domain joined device, the UWP app tries to acquire a token. 

```csharp
await publicClientApp.AcquireTokenByIntegratedWindowsAuthAsync(scopes);
or
await publicClientApp.AcquireTokenAsync(scopes);
```
* In Package.appxmanifest i added these capabilities.
```xml
  <Capabilities>
    <Capability Name="internetClient" />
    <Capability Name="privateNetworkClientServer" />
    <Capability Name="internetClientServer" />
    <uap:Capability Name="enterpriseAuthentication" /> 
    <uap:Capability Name="userAccountInformation" />
    <uap:Capability Name="sharedUserCertificates" />
  </Capabilities>
```

**Expected behavior**
Acquire a token.

**Actual behavior**
Receiving exception MsalServiceException.
  error: "interaction_required"
  error_description: "AADSTS53001: Device is not in required device state: domain_joined."

**Possible Solution**
I think the UWP app is not able to determine if the device is domain joined. Maybe i'm missing some capabilities?

**Comment by jmprieur** [comment] 2019-02-07 12:23
@rdeveen : does the exception have a non empty .Claims member?

**Comment by rdeveen** [comment] 2019-02-07 12:29
Yep, .Claims is null.

"error_codes":[53001]
"suberror":"message_only"

**Comment by jmprieur** [comment] 2019-02-20 12:16
Closing as duplicate of #643

**Closed by jmprieur** 2019-02-20 12:16 UTC
Labels: duplicate, scenario:Device certificate, scenario:Mobile-UWP

**Comment by rdeveen** [comment] 2019-03-04 16:16
Please reopen, the Web Account Manager is to connect the Universal Windows Platform (UWP) app to external identity providers, like Microsoft or Facebook, we are trying to use login using Work- or School accounts.

**Comment by jmprieur** [comment] 2019-03-04 16:57
@rdeveen did you try the following sample: https://github.com/Azure-Samples/active-directory-dotnet-native-uwp-wam (with work and school accounts) ?

**Comment by rdeveen** [comment] 2019-03-05 09:40
> @rdeveen did you try the following sample: https://github.com/Azure-Samples/active-directory-dotnet-native-uwp-wam (with work and school accounts) ?

Yes, I have tried that sample and that sample is working! 
What does that mean?

**Comment by jmprieur** [comment] 2019-03-05 10:07
This means that you need WAM in the case where an Azure AD tenant admin has setup a conditional access policy related to the device 

BTW, this also means that Web Account Manager is **not** to connect the Universal Windows Platform (UWP) app to external identity providers. WAM supports only Work and School accounts or Microsoft Personal account.

We need to integrate WAM with MSAL.NET for scenarios where the device certificate is needed (like your scenario). Meanwhile, if the WAM sample works for you, I'd say you should probably use it.

**Comment by rdeveen** [comment] 2019-03-06 18:27
So, it's not a bug in de MSAL library?

**Comment by jmprieur** [comment] 2019-03-06 18:32
no, @rdeveen : it's a feature that needs to be integrated (after we have GA MSAL.NET)
