### ISSUE TITLE
[Bug] User's default web browser does not open when running via `sudo`

### ISSUE THREAD

**Issue by mjcheetham** [AzureAD/microsoft-authentication-library-for-dotnet#1648] opened 2020-02-19 20:23 UTC
**Which Version of MSAL are you using ?**
MSAL 4.8.2

**Platform**
netcore (Linux and macOS)

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive

**Is this a new or existing app?**
c. This is a new app or experiment

**Repro**

```csharp
static void Main(string[] args)
{
    var app = PublicClientApplicationBuilder.Create(clientId)
        .WithRedirectUri("http://localhost")
        .Build();

    await app.AcquireTokenInteractive(scopes)
        .WithSystemWebViewOptions(new SystemWebViewOptions())
        .ExecuteAsync();
}
```

```shell
$ sudo dotnet run 
```

**Expected behavior**
The current (real) user's default web browser is opened to the authentication page.

**Actual behavior**
The root (UID 0) user's default web browser is opened instead of the real user.

**Possible Solution**
On non-Windows platforms check if the `SUDO_USER` environment variable is set.
If it is then use the value as the `ProcessStartInfo::UserName` property when performing the `Process::Start` in [`PlatformProxyShared::StartDefaultOsBrowser`](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/1cef43d185bb0a1dcc013d2ec232ae9d4c6c053a/src/client/Microsoft.Identity.Client/Platforms/Shared/NetStdCore/PlatformProxyShared.cs#L16).

**Additional context/Logs/Screenshots**
Both the UID and EUID are set to that of 'root' (i.e, 0) when running the process via `sudo`.

Child processes by default fork with their parent's real UID and EUID. The .NET Core `Process` class will correctly [attempt set the process to the correct user](https://github.com/dotnet/corefx/blob/bcfd3d34f519fc1369294304747c82f643be6ff1/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs#L453) if the `ProcessStartInfo::UserName` field has been set to non-`null`.

**Comment by jmprieur** [comment] 2020-02-20 18:37
Thanks @mjcheetham 
from your point of view is it a bug ? or an enhancement?

**Comment by mjcheetham** [comment] 2020-02-21 13:12
> from your point of view is it a bug ? or an enhancement?

@jmprieur it depends on what it meant by the "system" browser. According to the `SystemWebViewOptions` documentation the 'default' or 'system' browser should be:
> "the user configured browser [will be used]"

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/1cef43d185bb0a1dcc013d2ec232ae9d4c6c053a/src/client/Microsoft.Identity.Client/ApiConfig/SystemWebViewOptions.cs#L55-L61

I also realise the customised browser launching `OpenBrowserAsync` API is called out as being experimental, but the system web browser interactive flow itself is not. So perhaps this documentation is "incorrect" and should say "effective user".

IMO this should be the _real/interactive_ user's default browser and not the 'root' user's because the _real_ user's configured browser is assumed to be trusted by them, and also would be the one typically already 'signed in' with existing accounts via cookies. If they've changed from the default new-user's browser (same as root) there was a reason.

Also from a consistency point, on Windows the real user's preferred browser is launched regardless if the process is running with elevated privileges or not (`runas ≈ sudo`).

**Comment by bgavrilMS** [comment] 2021-12-22 09:56
Duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2839
Most browsers do not cross user, so there is no solution expect to throw an exception.

**Closed by bgavrilMS** 2021-12-22 09:56 UTC
Labels: duplicate, enhancement, scenario:Desktop
