### ISSUE TITLE
WwwAuthenticateParameters fails to create response from headers

### ISSUE THREAD

**Issue by Trimack** [AzureAD/microsoft-authentication-library-for-dotnet#3026] opened 2021-11-18 10:34 UTC
The WWWAuthenticate helper fails for 

`Bearer authorization_uri=https://login.microsoftonline.com/12345678-268e-46c2-8d30-1ad8ad2cd49d/oauth2/authorize, resource_id=https://testingorg0127.crm10.dynamics.com/`

There seem to be 2 problems: 

1. MSAL does not know how to parse authorization_uri property
2. The WWWAUtheticate collection has 1 element, but `.Any()` returns `false`

For more details please see [here](https://microsoft.sharepoint.com/teams/ADAL/_layouts/OneNote.aspx?id=%2Fteams%2FADAL%2FSiteAssets%2FDevEx%20Notebook&wd=target%28_NET%2FGeneral.one%7C69621FF6-FA3F-42F7-B919-35F9CB84D567%2FBug%20repro%203026%7CCDBF44A1-F140-40B8-9CCB-CFE77D9E77A7%2F%29)

**Comment by bgavrilMS** [comment] 2021-11-18 10:37
Hi @Trimack - can you please provide an example header that this helper fails on? We do have some unit tests around it, and even integration tests, so I find it hard to believe that it `will always fail`.

**Comment by Trimack** [comment] 2021-11-18 10:46
I just did in what I believe to be a related issue in https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3027#issue-1057201374.

I honestly do not understand why this doesn't work and how is the property supposed to work but here's a screenshot from the VS:
![image](https://user-images.githubusercontent.com/1777400/142401108-4a47f5f4-3062-42c2-a6a7-a54680cb7dcc.png)

**Comment by bgavrilMS** [comment] 2021-11-18 10:51
Is there an URI I can access to get this 401 + authenticate header?

**Comment by Trimack** [comment] 2021-11-18 11:30
An example URI is `https://mktcxptip11111810sg891crm08.crm10.dynamics.com/api/data/v9.1`.

**Comment by trwalke** [comment] 2021-12-02 18:20
So I am able to reproduce this and it Looks like there are some additional configurations that are needed in order for us ot access the data in this header. Not sure why it is different for this endpoint. This looks like something along the lines of what we need but not 100% sure yet.

https://stackoverflow.com/questions/52333446/core-2-1-refuses-to-respond-with-access-control-expose-headers

Looks like similar things happens in other languages as well
https://stackoverflow.com/questions/61357247/why-is-the-www-authenticate-header-missing-from-when-i-call-api-from-react-app

**Comment by alvin-h** [comment] 2022-06-01 20:14
Will a fix for this be prioritized?

I've tried using **CreateFromResourceResponseAsync()** to which all properties I need (Authority, Resource) returns null.

Manually using a GET request with HttpClient to the resourceUri and passing in the HttpResponseHeaders object from that into **CreateFromResponseHeaders()** also returns null.

Manually passing in the **WWW-Authenticate** header value as a string into **CreateFromWwwAuthenticateHeaderValue()** also returns null.

This is how the header string looks like:
`Bearer authorization_uri=https://login.microsoftonline.com/<our-tenant-id>/oauth2/authorize, resource_id=https://<our-api-domain>/`

**Comment by bgavrilMS** [comment] 2022-07-22 14:57
@trwalke - aren't you working on this?

**Closed** 2022-12-15 06:12 UTC
Labels: bug, P2
