### ISSUE TITLE
Latest MSAL incompatible with latest Xamarin.Android.Support.* libraries 

### ISSUE THREAD

**Issue by jamescro** [AzureAD/microsoft-authentication-library-for-dotnet#443] opened 2017-07-06 17:25 UTC
When you create a new Xamarin.Forms app from scratch, or when you upgrade an existing Xamarin Form app to the latest Xamarin.Android.Support libraries, you get this error when you launch the authz/authn process:

System.MissingMethodException: Method 'Android.Support.CustomTabs.CustomTabsIntent.LaunchUrl' not found.

It appears that the intent that the latest version of MSAL uses to launch he authentication process doesn't exist in the latest versions of the Xamarin Android libraries, so it looks like developers who start with fresh Xamarin.Forms apps will have  to downgrade those libraries in order to get MSAL to work.

See this issue in a Xamarin Microsoft Graph sample:
https://github.com/microsoftgraph/xamarin-csharp-connect-sample/issues/17

**Comment by lueyyou** [comment] 2017-07-26 04:33
Hi there, can we get a fix for this? This is delaying the development of our app. Unless there's another package we can use instead of MSAL?

**Comment by kpanwar** [comment] 2017-08-08 17:15
@jamescro @lueyyou - please use ` Install-Package Microsoft.Identity.Client -Version 1.1.1-alpha0388 -Source https://www.myget.org/F/aad-clients-nightly/api/v3/index.json` to try out the new package

**Comment by BtrJay** [comment] 2017-08-09 08:19
Hi @kpanwar , I've updated the package to 1.1.1-alpha0388 and it builds in Debug.

However I still have the compilation issue in Release mode.

Please see the following error.

_error MSB4018: Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'System.Threading.Tasks.Task`1<Microsoft.Identity.Client.AuthenticationResult> Microsoft.Identity.Client.PublicClientApplication::AcquireTokenAsync(System.Collections.Generic.IEnumerable`1<System.String>,System.String,Microsoft.Identity.Client.UIBehavior,System.String,System.Collections.Generic.IEnumerable`1<System.String>,System.String)' (defined in assembly 'PodcastApp.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null') with scope 'Microsoft.Identity.Client, Version=1.1.1.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve System.Threading.Tasks.Task`1<Microsoft.Identity.Client.AuthenticationResult> Microsoft.Identity.Client.PublicClientApplication::AcquireTokenAsync(System.Collections.Generic.IEnumerable`1<System.String>,System.String,Microsoft.Identity.Client.UIBehavior,System.String,System.Collections.Generic.IEnumerable`1<System.String>,System.String)_


And this is my package.config.

<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Acr.Support" version="2.1.0" targetFramework="monoandroid71" />
  <package id="Acr.UserDialogs" version="6.5.1" targetFramework="monoandroid71" />
  <package id="AndHUD" version="1.2.0" targetFramework="monoandroid71" />
  <package id="AutoMapper" version="6.1.1" targetFramework="monoandroid71" />
  <package id="BuildIt.Config.Core" version="1.0.0.26" targetFramework="monoandroid71" />
  <package id="BuildIt.Forms" version="1.1.0.47-beta" targetFramework="monoandroid71" />
  <package id="BuildIt.General" version="1.1.0.30" targetFramework="monoandroid71" />
  <package id="BuildIt.States" version="1.1.0.48-beta" targetFramework="monoandroid71" />
  <package id="FluentValidation" version="7.1.1" targetFramework="monoandroid71" />
  <package id="HockeySDK.Xamarin" version="4.1.5" targetFramework="monoandroid71" />
  <package id="Microsoft.Azure.Mobile.Client" version="4.0.0" targetFramework="monoandroid71" />
  <package id="Microsoft.Azure.Mobile.Client.SQLiteStore" version="4.0.0" targetFramework="monoandroid71" />
  <package id="Microsoft.Bcl" version="1.1.10" targetFramework="monoandroid71" />
  <package id="Microsoft.Bcl.Build" version="1.0.21" targetFramework="monoandroid71" />
  <package id="Microsoft.CSharp" version="4.3.0" targetFramework="monoandroid71" />
  <package id="Microsoft.Identity.Client" version="1.1.1-alpha0388" targetFramework="monoandroid71" />
  <package id="Microsoft.Net.Http" version="2.2.29" targetFramework="monoandroid71" />
  <package id="Microsoft.NETCore.Platforms" version="1.1.0" targetFramework="monoandroid71" />
  <package id="Microsoft.Rest.ClientRuntime" version="2.3.7" targetFramework="monoandroid71" />
  <package id="Microsoft.Win32.Primitives" version="4.3.0" targetFramework="monoandroid71" />
  <package id="modernhttpclient" version="2.4.2" targetFramework="monoandroid71" />
  <package id="MvvmCross.Binding" version="5.0.5" targetFramework="monoandroid71" />
  <package id="MvvmCross.Core" version="5.0.5" targetFramework="monoandroid71" />
  <package id="MvvmCross.Forms" version="5.0.5" targetFramework="monoandroid71" />
  <package id="MvvmCross.Platform" version="5.0.5" targetFramework="monoandroid71" />
  <package id="NETStandard.Library" version="1.6.1" targetFramework="monoandroid71" />
  <package id="Newtonsoft.Json" version="10.0.3" targetFramework="monoandroid71" />
  <package id="PCLCrypto" version="2.0.147" targetFramework="monoandroid71" />
  <package id="PCLStorage" version="1.0.2" targetFramework="monoandroid71" />
  <package id="PInvoke.BCrypt" version="0.3.2" targetFramework="monoandroid71" />
  <package id="PInvoke.Kernel32" version="0.3.2" targetFramework="monoandroid71" />
  <package id="PInvoke.NCrypt" version="0.3.2" targetFramework="monoandroid71" />
  <package id="PInvoke.Windows.Core" version="0.3.2" targetFramework="monoandroid71" />
  <package id="Plugin.MediaManager" version="0.4.1" targetFramework="monoandroid71" />
  <package id="Splat" version="2.0.0" targetFramework="monoandroid71" />
  <package id="sqlite-net-pcl" version="1.3.3" targetFramework="monoandroid71" />
  <package id="SQLitePCLRaw.bundle_green" version="1.1.5" targetFramework="monoandroid71" />
  <package id="SQLitePCLRaw.core" version="1.1.5" targetFramework="monoandroid71" />
  <package id="SQLitePCLRaw.lib.e_sqlite3.android" version="1.1.5" targetFramework="monoandroid71" />
  <package id="SQLitePCLRaw.provider.e_sqlite3.android" version="1.1.5" targetFramework="monoandroid71" />
  <package id="StyleCop.Analyzers" version="1.0.2" targetFramework="monoandroid71" developmentDependency="true" />
  <package id="System.AppContext" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Collections" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Collections.Concurrent" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Collections.Specialized" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.ComponentModel.TypeConverter" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Console" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Diagnostics.Debug" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Diagnostics.Tools" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Diagnostics.Tracing" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Dynamic.Runtime" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Globalization" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Globalization.Calendars" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.IO" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.IO.Compression" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.IO.Compression.ZipFile" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.IO.FileSystem" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.IO.FileSystem.Primitives" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Linq" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Linq.Expressions" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Linq.Queryable" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Net.Http" version="4.3.2" targetFramework="monoandroid71" />
  <package id="System.Net.Primitives" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Net.Sockets" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.ObjectModel" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Reflection" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Reflection.Extensions" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Reflection.Primitives" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Resources.ResourceManager" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Runtime" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Runtime.Extensions" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Runtime.Handles" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Runtime.InteropServices" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Runtime.InteropServices.RuntimeInformation" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Runtime.Numerics" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Runtime.Serialization.Formatters" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Runtime.Serialization.Primitives" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Security.Cryptography.Algorithms" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Security.Cryptography.Encoding" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Security.Cryptography.Primitives" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Security.Cryptography.X509Certificates" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Text.Encoding" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Text.Encoding.Extensions" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Text.RegularExpressions" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Threading" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Threading.Tasks" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Threading.Timer" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Xml.ReaderWriter" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Xml.XDocument" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Xml.XmlDocument" version="4.3.0" targetFramework="monoandroid71" />
  <package id="Validation" version="2.2.8" targetFramework="monoandroid71" />
  <package id="Xam.Plugin.Connectivity" version="3.0.1" targetFramework="monoandroid71" />
  <package id="Xam.Plugins.DownloadManager" version="1.2.0" targetFramework="monoandroid71" />
  <package id="Xam.Plugins.Settings" version="3.0.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Animated.Vector.Drawable" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Annotations" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Compat" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Core.UI" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Core.Utils" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.CustomTabs" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Design" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Fragment" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Media.Compat" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Transition" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v4" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.AppCompat" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.CardView" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.MediaRouter" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.Palette" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.RecyclerView" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Vector.Drawable" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Build.Download" version="0.4.6" targetFramework="monoandroid71" />
  <package id="Xamarin.FFImageLoading" version="2.2.9" targetFramework="monoandroid71" />
  <package id="Xamarin.FFImageLoading.Forms" version="2.2.9" targetFramework="monoandroid71" />
  <package id="Xamarin.Firebase.Common" version="42.1021.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Firebase.Iid" version="42.1021.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Firebase.Messaging" version="42.1021.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Forms" version="2.3.5.256-pre6" targetFramework="monoandroid71" />
  <package id="Xamarin.GooglePlayServices.Base" version="42.1021.1" targetFramework="monoandroid71" />
  <package id="Xamarin.GooglePlayServices.Basement" version="42.1021.1" targetFramework="monoandroid71" />
  <package id="Xamarin.GooglePlayServices.Gcm" version="42.1021.1" targetFramework="monoandroid71" />
  <package id="Xamarin.GooglePlayServices.Iid" version="42.1021.1" targetFramework="monoandroid71" />
  <package id="Xamarin.GooglePlayServices.Tasks" version="42.1021.1" targetFramework="monoandroid71" />
</packages>

Not sure what's actually causing it. 

Any help would be greatly appreciated.

Regards,

Jay

**Comment by trwalke** [comment] 2017-08-11 21:26
Hi @BtrJay  , unfortunately we cannot reproduce this issue on our side. If I find any useful information ill let you know.

**Closed** 2017-08-22 00:52 UTC
Labels: enhancement, P1

**Comment by robintschroeder** [comment] 2017-09-29 20:27
+1 

I can't downgrade to the earlier droid libraries. Is there a more recent alpha library that has been fixed? I am experiencing the error with 1.1.1-alpha0388.

Stack Trace:

09-29 15:20:35.254 I/MonoDroid(27963):   at (wrapper dynamic-method) System.Object:4892706f-bea6-471d-9fb3-022b8eb00bf9 (intptr,intptr)
09-29 15:20:35.271 W/art     (27963): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
09-29 15:20:35.278 D/Mono    (27963): DllImport searching in: '__Internal' ('(null)').
09-29 15:20:35.278 D/Mono    (27963): Searching for 'java_interop_jnienv_throw'.
09-29 15:20:35.278 D/Mono    (27963): Probing 'java_interop_jnienv_throw'.
09-29 15:20:35.278 D/Mono    (27963): Found as 'java_interop_jnienv_throw'.
An unhandled exception occured.

09-29 15:20:40.023 E/mono    (27963): 
09-29 15:20:40.023 E/mono    (27963): Unhandled Exception:
09-29 15:20:40.023 E/mono    (27963): System.MissingMethodException: Method 'Microsoft.Identity.Client.PublicClientApplication.AcquireTokenAsync' not found.
09-29 15:20:40.023 E/mono-rt (27963): [ERROR] FATAL UNHANDLED EXCEPTION: System.MissingMethodException: Method 'Microsoft.Identity.Client.PublicClientApplication.AcquireTokenAsync' not found.

**Comment by kpanwar** [comment] 2017-09-29 20:36
@robintschroeder - your error does not reflect the issue that is being addressed here.

**Comment by robintschroeder** [comment] 2017-10-02 16:36
@kpanwar I apologize, my error is much like @BtrJay 's error in this thread. 
I *think* the error I am experiencing is related to setting up the Azure AD side incorrectly and calling a bad scope from the mobile side - or, at least that is what appears to have resolved it for me - at least at this time. So, yes, it appears to be unrelated. Thank you.

**Comment by SureshbabuLucky** [comment] 2017-10-31 14:36
Hi,

Experiencing exception in Azure B2C Directory login by using MSAL Library on Android platform with the following two libraries when updated to latest version (26.1.0.1)

1. Xamarin.Android.Support.CustomTabs (version 26.1.0.1)
2. Xamarin.Android.Support.v4 (version 26.1.0.1)

Exception:

System.MissingMethodException: Method 'Android.Support.CustomTabs.CustomTabsIntent.LaunchUrl' not found.

StackTrace:

MonoDroid( 7659): UNHANDLED EXCEPTION:
MonoDroid( 7659): System.MissingMethodException: Method 'Android.Support.CustomTabs.CustomTabsIntent.LaunchUrl' not found.
MonoDroid( 7659):   at Android.App.Activity.n_OnResume (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] :0 
MonoDroid( 7659):   at (wrapper dynamic-method) S
An unhandled exception occured.

**Comment by wmatthiesen** [comment] 2017-11-10 12:26
Is there any update on this?  Using Microsoft.Identity.Client v1.1.0-preview throwing the "TabsIntent.LaunchUrl  not found" makes it impossible to move to production for android.  
I have been seeing this issue for at least two months.  iOS works.

**Comment by jennyf19** [comment] 2018-02-05 01:37
@wmatthiesen Can you try v1.1.2-preview? Also, see our [wiki](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Troubleshooting-Xamarin.Android-issues-with-MSAL) for more information. Let us know if this helps. Thanks.
