### ISSUE TITLE
[Bug] Can't navigate back from ToS and Privacy Statement sites in consent prompt

### ISSUE THREAD

**Issue by rikyuz** [AzureAD/microsoft-authentication-library-for-dotnet#1724] opened 2020-03-24 12:05 UTC
**Which Version of MSAL are you using ?**
MSAL 4.9.0

**Platform**
UWP

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Is this a new or existing app?**
This is a new app or experiment

**Repro**
Launch the interactive login process by calling AcquireTokenInteractive.

```csharp
authResult = await PublicClientApp.AcquireTokenInteractive(Scopes)
                                .ExecuteAsync()
                                .ConfigureAwait(false);
```

**Expected behavior**
When presented with the consent page which lists the required permissions there are hyperlinks for Terms Of Service and Privacy Statement. When user clicks either of these links it should be possible to return to the consent prompt with a back button.

**Actual behavior**
The login window doesn't have a back button and it's impossible to return from the site after user has clicked the hyperlink.

**Additional context/ Logs / Screenshots**
![ConsentPrompt](https://user-images.githubusercontent.com/51473445/77423674-6ac6d300-6dd8-11ea-98a3-987350b4f72a.png)

**Comment by bgavrilMS** [comment] 2020-03-24 13:51
I tried with a .net app (not UWP) and those clicking those links makes the system browser pop up and navigate. 
I can confirm the issue on UWP though, clicking those links leads to the embedded browser navigating to the TOS page itself. 

Would it be possible for the TOS page to have a url "back" button instead? That might work.

The control we use to perform authentication - WebAuthenticationBroker - is in maintenance mode and are very unlikely to fix this low priority issue.

**Comment by bgavrilMS** [comment] 2020-03-24 13:54
The issue will likely be fixed when we integrate with WAM, tracked by https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/643

**Comment by rikyuz** [comment] 2020-03-24 14:00
I have tried to add a back button to the page like so:

`<a href="#" onclick="history.go(-1)" class="w3-button w3-theme-d4">Back</a>`

This however doesn't navigate back to the consent prompt but instead goes to the home page of office.com for the account I'm signing in with.

@bgavrilMS do you have any idea when to expect this to be fixed?

**Comment by bgavrilMS** [comment] 2020-03-24 14:08
I'll leave the issue open since the workaround doesn't work. @jmprieur can advise on next steps. I'll contact the WAB team for guidance on this.

**Comment by rikyuz** [comment] 2020-03-24 14:09
@bgavrilMS thanks, I'll stay tuned!

**Comment by rikyuz** [comment] 2020-03-25 18:31
@bgavrilMS did you hear back from the WAB team? @jmprieur do you have a solution how to overcome this problem?

**Comment by jmprieur** [comment] 2020-03-25 18:53
@rikyuz :the WAB team has a work item in progress to fix this (for a future version of Windows)

Do you need to sign-in AAD only users? or also AAD + MSA?
If you want to sign-in only Work and School accounts (AAD), then this sample might help you: https://github.com/azure-samples/active-directory-dotnet-native-uwp-wam : it's leveraging WAM (which does not yet support AAD+MSA)

**Comment by jmprieur** [comment] 2020-03-25 19:29
no, indeed, you cannot use WAM in that case.
Removing the "bug" as this is not an MSAL.NET bug, but an external issue (with Windows), which they are going to fix.
Do you agree to close the issue @rikyuz  ?

**Comment by rikyuz** [comment] 2020-03-25 19:31
@jmprieur I guess we don't have a choice. You may close this issue.

Is there any way for me to monitor how the fix implementation is progressing? Is there any time estimate?

**Comment by jmprieur** [comment] 2020-03-25 20:17
I'll ask the Windows team.

**Comment by jmprieur** [comment] 2020-03-26 19:09
@rikyuz :The Windows team advised that you use FeedbackHub / feature request to track it

**Closed by jmprieur** 2020-03-26 19:09 UTC
Labels: external, scenario:Mobile-UWP, wontfix

**Comment by rikyuz** [comment] 2020-03-26 19:13
@jmprieur All right. Thank you for helping out!

**Comment by rikyuz** [comment] 2020-04-03 12:51
@jmprieur sorry to bother you again but I noticed that Microsoft has implemented a back button to their ToS and Privacy Statement pages which can be navigated to from the login popup:

<img width="489" alt="Microsoft Privacy Statement" src="https://user-images.githubusercontent.com/51473445/78362405-b7719180-75c2-11ea-845e-dbb299dd1518.png">

Would it be possible to ask from someone how these buttons function? I wonder if I could use the same implementation for my pages. Thank you.
