### ISSUE TITLE
[Bug] Microsoft.Identity.Client.MsalClientException: User canceled authentication. Xamarin forms

### ISSUE THREAD

**Issue by NiladriPadhy** [AzureAD/microsoft-authentication-library-for-dotnet#3286] opened 2022-04-20 16:11 UTC
Getting issue MSAL Authentication for some users Xamarin Forms.

**Original Exception**
AuthCodeRequestComponent.VerifyAuthorizationResult (Microsoft.Identity.Client.UI.AuthorizationResult authorizationResult, System.String originalState)
Microsoft.Identity.Client.MsalClientException: User canceled authentication.

I can ensure user has not cancelled the authentication process.

**Stack Trace:**
icrosoft.Identity.Client.Internal
AuthCodeRequestComponent.VerifyAuthorizationResult (Microsoft.Identity.Client.UI.AuthorizationResult authorizationResult, System.String originalState)
Microsoft.Identity.Client.Internal
AuthCodeRequestComponent.FetchAuthCodeAndPkceInternalAsync (Microsoft.Identity.Client.UI.IWebUI webUi, System.Threading.CancellationToken cancellationToken)
Microsoft.Identity.Client.Internal
AuthCodeRequestComponent.FetchAuthCodeAndPkceVerifierAsync (System.Threading.CancellationToken cancellationToken)
Microsoft.Identity.Client.Internal.Requests
InteractiveRequest.GetTokenResponseAsync (System.Threading.CancellationToken cancellationToken)
Microsoft.Identity.Client.Internal.Requests
InteractiveRequest.ExecuteAsync (System.Threading.CancellationToken cancellationToken)
Microsoft.Identity.Client.Internal.Requests
RequestBase.RunAsync (System.Threading.CancellationToken cancellationToken)
Microsoft.Identity.Client.ApiConfig.Executors
PublicClientExecutor.ExecuteAsync (Microsoft.Identity.Client.ApiConfig.Parameters.AcquireTokenCommonParameters commonParameters, Microsoft.Identity.Client.ApiConfig.Parameters.AcquireTokenInteractiveParameters interactiveParameters, System.Threading.CancellationToken cancellationToken)

 **Code Snippet:**
if (DeviceInfo.Platform == DevicePlatform.iOS)
            {
                _pca = PublicClientApplicationBuilder.Create(Configurations.ClientID).WithTenantId(Configurations.TenantID)
                       .WithBroker(false)
                       .WithRedirectUri(Configurations.IOSRedirectUri)
                       .WithIosKeychainSecurityGroup(AppConstants.KeyChainSecurityGroup)
                       .Build();
            }
            else
            {
                _pca = PublicClientApplicationBuilder.Create(Configurations.ClientID).WithTenantId(Configurations.TenantID)
                       .WithBroker(false)
                       .WithRedirectUri(Configurations.AndroidRedirectUri)
                       .Build();
            }
// Gets the available accounts
            var accounts = await _pca.GetAccountsAsync();

            // Stores first account available
            Common.Account = accounts.FirstOrDefault();

            try
            {
                // This call acquires the access token silently without asking for user credentials
                var authResult = await _pca.AcquireTokenSilent(Configurations.Scopes, Common.Account).ExecuteAsync();

                // Stores the access token
                AppConstants.AccessToken = authResult.AccessToken;

                return true;
            }
            catch (MsalUiRequiredException ex)
            {
                try
                {
                    // This present a interactive window to user where in user needs to
                    // enter credentials for acquiring access token
                    var authResult = await _pca.AcquireTokenInteractive(Configurations.Scopes)
                                           .WithParentActivityOrWindow(App.RootViewController)
                                           .WithUseEmbeddedWebView(true)
                                           .ExecuteAsync();

                    AppConstants.AccessToken = authResult.AccessToken;

                    return true;
                }
                catch (Exception ex2)
                {
                    Crashes.TrackError(ex2);
                }

                return false;
            }

Around 15% of iOS App users facing this issue. Looking for immediate help.

Best Regards
Niladri

**Comment by NiladriPadhy** [comment] 2022-04-25 11:54
Any Update on this?

**Comment by SameerK-MSFT** [comment] 2022-04-27 22:07
It is hard to tell from here. Please use ConfigureAwait(false) on all the async operations. Thaw would solve any threading issues. Let us know how it goes.

**Comment by NiladriPadhy** [comment] 2022-04-29 04:54
Its not occuring in Debug mode. Its occuring in the builds, once its used by multiple users. We kept the ConfigureAwait(false) in all async operations, investingating the issue. We will let you know once we verified the fix.

**Comment by bgavrilMS** [comment] 2022-05-02 12:49
It might be a threading issue, but we can't reproduce it. Can you make sure you always call `AcquireTokenInteractive` from the UI thread? Also, why are you using the embedded browser and not the system browser?

**Comment by NiladriPadhy** [comment] 2022-05-05 05:46
> Also, why are you using the

**Comment by NiladriPadhy** [comment] 2022-05-05 05:55
> It might be a threading issue, but we can't reproduce it. Can you make sure you always call `AcquireTokenInteractive` from the UI thread? Also, why are you using the embedded browser and not the system browser?

Explicitly I am not invoking in UI Thread, You can refer the code above. Do I need to put AcquireTokenInteractive in an explicity UI **thread Device.BeginInvokeOnMainThread(() => { });**?  Regarding embeded browser, I am using because of security reason. Will embeded browser will cause this User cancelled authentication error?

**Comment by bgavrilMS** [comment] 2022-05-05 09:53
We are not aware of any security differences between system browser vs embedded browser. There are pros and cons for each of them. Google has a very clear preference for system browser, but the reasoning is not clear. 

I recommend you try to call AcquireTokenInteractive from UI thread, see if this helps. 

The `User Cancelled` error comes when we detect that the webview was closed. This may be the user actually closing it, or if the webview fails to pop up.

**Comment by edgiardina** [comment] 2022-05-18 22:18
Would like to chime in here, we see this specific issue on Android... we discovered it while trying to track down a separate issue, which is that our users get logged out after a deploy / app update on iOS and Android (We are a Xamarin Forms project).

(In the image below, we deployed May 10th and saw a spike of 'cancellations'). 
![image](https://user-images.githubusercontent.com/3627193/169164917-789b69f0-f064-4a63-b6e8-c6d45da52898.png)

**Comment by NiladriPadhy** [comment] 2022-06-23 10:28
Yes, this might be the case. When we released the update that we got this error.

**Comment by NiladriPadhy** [comment] 2022-08-01 11:10
Few days back we released an update to Appstore and Playstore. We observed again spike in "User canceled authentication" Exception. Around 2% users faced the issue. as @SameerK-MSFT  suggested we have added ConfigureAwait(false). After adding ConfigureAwait(false), we are getting less number of errors compared to previous release.

**Comment by bgavrilMS** [comment] 2022-12-22 14:02
A small number of these errors is normal. Users can legitimately close the browser or sometimes an error is displayed in the browser (e.g. bad smth smth / your account has been locked etc., please contact your tenant admin) without any possiblity of going forward.

**Closed by bgavrilMS** 2022-12-22 14:02 UTC
Labels: Investigate
