### ISSUE TITLE
[Bug] [S] WebView2Loader.dll is missing in net472 app

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-authentication-library-for-dotnet#2482] opened 2021-03-18 01:32 UTC
**Which Version of MSAL are you using ?**
4.33

**Platform**
net472

**What authentication flow has the issue?**
Interactive WebView2

**Repro 1**
[WebView2LoaderRepro.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/6746106/WebView2LoaderRepro.zip)
- WebView2Library references WebView2 SDK NuGet.
- WebView2Library does specify AnyCPU PlatformTarget explicitly.
- WebView2Library is packed as a NuGet.
- WebView2App references WebView2Library as a NuGet.
- Run WebView2App for net472 target.

**Repro 2**
1. Use NetDesktopWinFormsWAM project.
2. Update to reference MSAL NuGet instead of source code project.
3. Build, run, do interactive request.
4. WebView2Loader error occurs.

**Expected behavior**
WebView2 should show up.

**Actual behavior**
If App targets net472, I see different behavior depending on the PlatformTarget element in the App csproj.
- None specified - BadImageFormatException
- AnyCPU - DllNotFoundException
- x86 or x64 - everything works

**Additional context / logs / screenshots**
Current workaround is to set `PlatformTarget` to either x86 or x64 in the app's project file.

Related issue in WebView2 repo:
[Using WebView2 in a WPF Assembly](https://github.com/MicrosoftEdge/WebView2Feedback/issues/730#issuecomment-803132248)

**Comment by bgavrilMS** [comment] 2021-03-18 12:01
I was not able to reproduce this issue. @pmaytak - could you try to create a simple repro and open a bug on WebView2 team ? Should be sufficient to just try

```csharp
string s = CoreWebView2Environment.GetAvailableBrowserVersionString();
Console.WriteLine(s);
```

**Comment by pmaytak** [comment] 2021-03-18 17:54
@bgavrilMS Added zip repro above.
Bug: https://github.com/MicrosoftEdge/WebView2Feedback/issues/1091

**Comment by pmaytak** [comment] 2021-03-31 03:16
@bgavrilMS It's an issue with WebView2 SDK. Possible bug and workaround is described [here](https://github.com/MicrosoftEdge/WebView2Feedback/issues/730#issuecomment-803132248). Workaround is to add `<PlatformTarget>AnyCPU</PlatformTarget>` to the project file.

**Comment by bgavrilMS** [comment] 2021-03-31 08:51
Nice, thanks for following this up @pmaytak !

**Comment by pmaytak** [comment] 2021-04-09 03:58
@bgavrilMS Adding PlatformTarget element workaround doesn't work for us.

Should we exclude WebView2 here for NetFx targets?
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/c25582a72f1dd7f9a3270120c490734d164c4dc0/src/client/Microsoft.Identity.Client/Platforms/Features/WebView2WebUi/WebView2WebUiFactory.cs#L46-L50

NetDesktopWinFormsWAM still doesn't include the WebView2Loader.dll.
![image](https://user-images.githubusercontent.com/34331512/114126141-b564a180-98ac-11eb-8ed4-1fcddae54de1.png)

NetCoreWinFormsWAM does include the different WebView2Loader.dll runtimes.
![image](https://user-images.githubusercontent.com/34331512/114126189-d200d980-98ac-11eb-897a-75b42462db48.png)

Also for reference: [Release notes for WebView2 SDK](https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes).

**Comment by bgavrilMS** [comment] 2021-05-18 10:41
We should think about catching the exception and re-thrwoing a meaningful error with the workaround,

**Comment by pmaytak** [comment] 2021-07-01 07:31
Update: Seems like the workaround doesn't work when the library is consumed as a NuGet. Left comment in the WebView2 feedback issue.

**Comment by pmaytak** [comment] 2021-07-12 21:47
cc @bgavrilMS @mjcheetham 
I may have found another workaround for this. In the client app project add `<PlatformTarget>AnyCPU</PlatformTarget>` and directly reference WebView2 NuGet.

**Comment by jmprieur** [comment] 2021-07-13 07:43
@pmaytak do we want to document this in the wiki?

**Comment by pmaytak** [comment] 2021-07-13 16:09
@jmprieur We do have it in a wiki: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/WebView2#troubleshooting. But thanks, for the reminder, I'll update it.

**Comment by bgavrilMS** [comment] 2022-07-22 15:00
Closing as no fix. For AAD authorities, please use WAM.

**Closed by bgavrilMS** 2022-07-22 15:00 UTC
Labels: bug, P2, external, workaround exists
