### ISSUE TITLE
[Bug] Net Standard Platform Proxy Updates

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#3451] opened 2022-07-06 17:01 UTC
- NetStandard13PlatformProxy.cs is incorrectly named, it should be updated to reflect net standard 2.0.

- Update NetStandard13PlatformProxy.cs to use logic from the netcoreapp2.1 target as these platform proxies should ideally be the same after the net standard 2.1 update.

- Investigate if the netcoreapp2.1 target should be deleted.

**Comment by bgavrilMS** [comment] 2022-07-20 10:14
Closing as duplicate of #1991

**Closed by bgavrilMS** 2022-07-20 10:14 UTC
Labels: internal

**Comment by pmaytak** [comment] 2022-08-04 20:52
[Released in 4.46.0](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.46.0)
