### ISSUE TITLE
There is WebView2  problem  when use WindowsAppSDKSelfContained base onWinUI3

### ISSUE THREAD

**Issue by adxpcc** [AzureAD/microsoft-authentication-library-for-dotnet#3941] opened 2023-02-06 05:32 UTC
I I downlaod  demo code.
 from 
https://github.com/Azure-Samples/ms-identity-netcore-winui
and
add <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained> in the project file(csproj)

F5 debug

![image](https://user-images.githubusercontent.com/15758574/216891041-8be36d96-c8b8-4fb4-bd41-b7456ab96392.png)

VS2022+win10_22h2

**Comment by bgavrilMS** [comment] 2023-02-06 12:06
Looks like a duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3583 and there is a workaround posted here: 

https://github.com/microsoft/microsoft-ui-xaml/issues/5689#issuecomment-982128778

**Closed by bgavrilMS** 2023-02-06 12:06 UTC

**Comment by baskren** [comment] 2023-02-09 13:53
@bgavrilMS : posted work around does not work (I _really_, _really_ tried).

Here is a simple demo app showing that the work around does not work: https://github.com/baskren/WinUi3_MSAL_SelfContained_WorkAround_Fail

Here is a simple demo app illustrating the original failure:
https://github.com/baskren/WinUi3_MSAL_SelfContained_Fail
