### ISSUE TITLE
[Feature Request] Provide WithCertificateName API to fetch certificate by name

### ISSUE THREAD

**Issue by SameerK-MSFT** [AzureAD/microsoft-authentication-library-for-dotnet#2767] opened 2021-07-15 04:21 UTC
**Is your feature request related to a problem? Please describe.**
To provide certificate to confidential client, developer has name of the cert available; but needs to write code to fetch it.

**Describe the solution you'd like**
Provide a WithCertificateByName API that will accept the name of certificate and provide the first found certificate for configuration.

**Describe alternatives you've considered**
Not many alternative that I can think of

**Additional context**
This will reduce the code developers need to write and improve their productivity.

**Comment by bgavrilMS** [comment] 2021-07-22 14:27
Closing as duplicate of #2768

**Closed by bgavrilMS** 2021-07-22 14:27 UTC
Labels: Feature Request, enhancement, scenario:ConfidentialClient
