### ISSUE TITLE
[Tracking] FIDO2 Support

### ISSUE THREAD

**Issue by prajaybasu** [AzureAD/microsoft-authentication-library-for-dotnet#1339] opened 2019-08-14 05:34 UTC
Both [Microsoft](https://www.microsoft.com/en-us/microsoft-365/blog/2018/11/20/sign-in-to-your-microsoft-account-without-a-password-using-windows-hello-or-a-security-key/) and [Azure AD](https://techcommunity.microsoft.com/t5/Azure-Active-Directory-Identity/Announcing-the-public-preview-of-Azure-AD-support-for-FIDO2/ba-p/746362) accounts support FIDO2 based logins using Windows Hello (i.e., FIDO2 platform authenticator supporting resident keys) or USB/Lightning/NFC based security keys. Android is also a certified platform authenticator but I do not believe it supports resident keys yet.  

There are also platform APIs that are implemented and/or are in the works: 

* [Windows 10](https://github.com/Microsoft/webauthn)
* [Android](https://developers.google.com/android/reference/com/google/android/gms/fido/package-summary) - [Xamarin bindings](https://www.nuget.org/packages/Xamarin.GooglePlayServices.Fido/) (I'm not sure if resident keys and FIDO2 PIN UI are supported)
* [Apple WebKit](https://bugs.webkit.org/show_bug.cgi?id=181943)
* [YubiKey lightning](https://www.yubico.com/lightning-project/)

Are there any plans to support FIDO2 in MSAL.NET so I can use my security keys without a webview (using Windows/Android platform APIs and [libfido2](https://github.com/Yubico/libfido2) on Linux/macOS) or using the OS webview (iOS/macOS)? Is there a unified repository for having this as a cross platform feature request for all supported scenarios?  

I believe MSAL support should be a part of Microsoft's FIDO2 roadmap. Without MSAL support plans in the near future I do not see the point of FIDO2 support if majority of applications can't login with it

**Comment by jennyf19** [comment] 2019-08-22 17:57
@prajaybasu We are considering it. No ETA for now.

**Comment by bgavrilMS** [comment] 2020-07-21 10:41
FIDO keys should work fine. On Windows, you need to use the system browser, ideally the new Chromium based Edge, although Chrome also works as far as I know. 

In the future, we will extend support to the embedded browser as well. Tracking issue: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1398

**Comment by prajaybasu** [comment] 2020-07-23 20:41
A seamless FIDO2 experience across Microsoft applications will require the adoption of WebView2, as mentioned in your  linked issue. Given that a lot of Microsoft first party desktop applications use the embedded view, I still cannot use my YubiKey to login anywhere on my personal computer except on the web apps.

**Comment by prajaybasu** [comment] 2020-07-23 20:46
MSAL desktop and mobile libraries should also consider supporting a 100% native login experience on platforms where it is possible (Windows currently) to make the passwordless experience seamless without browser redirects. Native interop with the WebAuthN Win32 API would be required - https://github.com/Microsoft/webauthn

**Comment by bgavrilMS** [comment] 2020-07-24 08:46
Thanks for the detailed explanation @prajaybasu . WebView2 is still in preview so we cannot use it until it is generally available. I have a prototype of MSAL using WebView2 and it's working well. 

We are also looking at integrating with WAM https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/643 which should open up the Windows Hello and other native experience.

**Comment by jmprieur** [comment] 2020-09-22 07:51
@bgavrilMS : adding a link on how to install WebView2: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#understanding-the-webview2-runtime

**Comment by jmprieur** [comment] 2020-11-18 14:05
@bgavrilMS : I think that we can close? this would be a dupe of the support for the system browser in ASP.NET Core?

**Comment by jmprieur** [comment] 2020-11-18 14:15
Status:
- FIDO2 does not work on embedded browsers yet, but we have a solution (IWebView2). It should work with system browser
- it works with WAM, but only for Work or school accounts, not MSA (known issue)

**Comment by jmprieur** [comment] 2020-12-14 13:08
See also https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1670

**Comment by bgavrilMS** [comment] 2021-01-14 14:09
With MSAL 4.25, apps can use WAM which mostly supports FIDO (it doesn't currently work with MSA accounts)
With WebView2, MSAL + embedded browser should also support FIDO (https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1398)
With system browser, Chrome and Edge support FIDO

**Comment by bgavrilMS** [comment] 2021-03-18 18:28
Closing this as we now support FIDO via; 

- system browser
- Win10 broker (WAM) 
- WebView2 embedded browser

We are keeping WebBrowser1 (legacy embedded browser) only on .NET Classic targets for backwards compatibility and will probably remove it in MSAL 5

**Closed by bgavrilMS** 2021-03-18 18:28 UTC
Labels: Feature Request, enhancement, scenario:Desktop, scenario:Mobile-UWP
