### ISSUE TITLE
Cache deserialization does not clear existing state

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1080] opened 2019-04-16 14:15 UTC
**Which Version of MSAL are you using ?**
MSAL 3.0.4-preview

**Platform**
net45 and others that support custom serialization

**What authentication flow has the issue?**
serialization

** Repro **

1. Have 2 apps share the same token cache. They can use different clientIDs. Use MsalV3 serialization / deserialization methods.
2. Login interactively from app A
3. Sign out from app B
4. View accounts from app A

**Actual**: an account is still found for app A (despite cache.json
**Expected**: no accounts

5. Perform any other "write" operation with app A, such as log in with another user

**Actual**: the original state is also restored (user from step 2)

Root cause: de-serialize performs a MERGE, so when the cache file changes, the app does not throw away it's in-memory state. 

User impact: users cannot share the cache just using the serialization hooks provided by MSAL.

**Comment by jmprieur** [comment] 2019-04-21 09:32
@bgavrilMS 
This is by design. The cache serialized cache needs to have some eventing mechanism, like in https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/blob/master/src/Microsoft.Identity.Client.Extensions.Msal/MsalCacheHelper.cs#L70

proposing to close it as by design

cc: @MarkZuber @henrik-me @jennyf19 @trwalke

**Closed by jmprieur** 2019-04-21 09:32 UTC
Labels: By Design, scenario:Desktop
