### ISSUE TITLE
Consent is presented every time for MSA accounts

### ISSUE THREAD

**Issue by andretms** [AzureAD/microsoft-authentication-library-for-dotnet#468] opened 2017-09-08 21:40 UTC
Every time a MSA account sign-in, a consent is displayed, even if the user already had consented to the same scope before.

**Steps to repro**

- Build and run the WPF client from: https://docs.microsoft.com/en-us/azure/active-directory/develop/guidedsetups/active-directory-windesktop
- Sign-in with a MSA account. You will be prompted to consent to the scope
- End the app
- Sign-in again with the same MSA account. You will be prompted to consent to the scope

**Comment by jmprieur** [comment] 2017-09-09 04:47
Good catch @andretms. I can repro it as well on https://github.com/Azure-Samples/active-directory-dotnet-desktop-msgraph-v2 which has an implementation of the cache, each time I sign-out, and re-signin with my MSA.

**Analysis:**
- This happens both with the new and the old sign-in experience
- Looking at the fiddler traces, I have not seen any prompt=consent passed by MSAL.Net so I think that this is a problem with the STS.
cc: @kpanwar

**Comment by ajtruckle** [comment] 2017-09-10 10:11
I have a related issue. My console app uses the registry to store the access token and expiry timestamp. So, it shows the consent screen once and then, if they use the console app again within an hour it doesn't show the consent screen because the cached access token is still valid. If the expiry date is now lapse, I get it to show the consent screen again.

I find this annoying. With the Google Calendar API once you can authorized your app for consent that it is. It continues to work. So if my users decide to use my Outlook console app instead to sync with their Outlook calendar it is going to be annoying that it will keep asking for consent every hour.

Your documentation indicates this is handled by the RefreskToken but this is not exposed. One of your staff said it is handled internally but I can't see how that is the case, atleast, not with how I am doing things.

Once my user has consented I would like it to stay that way for them else it is not a nice user experience.  Please help me fix this issue too because I am reluctant to add this Microsoft Graph Console app to my application features until it is resolved for me.

Thank you.

**Comment by jmprieur** [comment] 2017-12-11 11:20
Apparently MSA does not retain consent. this. Closing this

**Closed by jmprieur** 2017-12-11 11:20 UTC

**Comment by JaykeBird** [comment] 2018-05-30 08:52
Hey @jmprieur , so if I may ask, what was the reason for closing this? Is it something that's just beyond the scope of this library?

**Comment by jmprieur** [comment] 2018-05-30 13:51
Yes, indeed, I was told that this is the MSA service that re-requests consent each time. Let me check if this still true as thing have evolved since December. @JaykeBird did you try recently?

**Comment by JaykeBird** [comment] 2018-05-30 21:51
Hmm... utilizing the WPF sample app, it actually seems to perform correctly now after restarting the app (i.e. not asking me to log back in/get consent again). I'm experiencing a different situation in my own app, but I feel that I may be doing something incorrect there. Thank you for responding!

**Comment by jmprieur** [comment] 2018-05-30 22:15
Thanks for the update, @JaykeBird 
On my side I confirmed, the consent should not be re-asked now for MSA.
