### ISSUE TITLE
[Bug] Issue with Single Sign-On (SSO) Implementation

### ISSUE THREAD

**Issue by JineshKamdar98** [AzureAD/microsoft-authentication-library-for-dotnet#4741] opened 2024-05-03 07:22 UTC
### Library version used

4.43.0.0

### .NET version

.NET Framework 4.8

### Scenario

PublicClient - desktop app

### Is this a new or an existing app?

None

### Issue description and reproduction steps

Hello everyone,

I'm encountering an issue with the implementation of Single Sign-On (SSO) in our WPF application, and I'd appreciate some guidance or insights from the community.

Here's a breakdown of our setup:

- We have a main WPF application that utilizes ADFS with MSAL for login purposes.
- Within this application, we've developed a custom WebView2 control, leveraging the PublicClientApplication to integrate with our custom control.
- Additionally, we provide support for hosting web applications within our WPF application. Recently, we incorporated an Angular (SPA) web application into our WPF environment, which also uses ADFS with MSAL for login.
- Our objective is to enable Single Sign-On (SSO) functionality in the hosted web application, utilizing the cache generated during the login process of our WPF application.

We've managed to achieve this integration successfully. However, we encountered a roadblock when attempting to implement automatic login in the WPF application under specific conditions. More specifically:

We aim to automate the login process in the WPF application if a certain flag, let's call it "SingleSignOnUser," is set to True by the user. This is accomplished using the AcquireTokenSilent API provided by PublicClientApplication.
The issue arises when calling AcquireTokenSilent: it doesn't display any prompts at the start of the WPF application and logs in automatically, and we're unable to achieve Single Sign-On (SSO) functionality in the hosted web application.

It's important to note that we retain the user data folder in its path, and we're not deleting it along with the cache.
Has anyone else encountered a similar issue, or perhaps have insights into what might be causing this behavior? Any assistance or suggestions would be greatly appreciated!

Thank you in advance for your help.

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by neha-bhargava** [comment] 2024-05-03 17:15
Duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4739

**Closed by neha-bhargava** 2024-05-03 17:15 UTC
Labels: untriaged, needs attention
