### ISSUE TITLE
Moving from login.microsoftonline.com to b2clogin.com causes `The IDP client key/secret is not properly configured` error with Facebook IDP

### ISSUE THREAD

**Issue by livehop** [AzureAD/microsoft-authentication-library-for-dotnet#808] opened 2019-01-21 21:47 UTC
I upgraded to MSAL 2.7.0 and tried to move to <tenant>.b2conline.com
I am using Xamarin Forms

In my Xamarin Forms application, the login screen appears, I am able to register and also get my user created but the control never gets redirected to my app. (the application just hangs). 
Am I missing a redirect setting somewhere ? In my native app; I set my redirect to 
msal<tenantid>://auth

**What authentication flow has the issue?**
Native/Xamarin

Other? - please describe;

**Repro**

```csharp
  AuthenticationClient = new PublicClientApplication(AppSettings.B2cClientId,
                $"{AppSettings.B2cAuthority}{AppSettings.B2cTenant}/{AppSettings.B2cPolicy}");
            AuthenticationClient.RedirectUri = $"msal{AppSettings.B2cClientId}://auth";
…

                var result = await App.AuthenticationClient.AcquireTokenAsync(
                    AppSettings.Scopes,
                    GetAccountByPolicy(accounts, AppSettings.DefaultB2cPolicy), 
                    App.UiParent);

Hangs in the above line.


```

**Expected behavior**
I was expecting it to return with the access tokens so that I can save them and move to the next screen.

**Actual behavior**
The application just freezes

**Comment by jennyf19** [comment] 2019-01-22 19:05
@livehop Which platform (iOS, Android, UWP) is having the issue? 
for the redirect uri, do you have the client_id in there? $"msal{client_id}://auth"

**Comment by livehop** [comment] 2019-01-22 19:38
I am testing this on Android; on further debugging I found that the problem is with Facebook and MSAL; the same settings works when I use the web but on Android it says your credentials and key are incorrectly set up. 

The other ways of logging (Microsoft / gmail ) work ok; facebook just gives an exception. I also tried the same thing with the MSAL active-directory-b2c-xamarin-native-master project on github; it gives the same error only for facebook.

many thanks!

**Comment by livehop** [comment] 2019-01-22 19:40
Sorry .. just to clarify, the "hang" that I was saying was incorrect; the thread was just existing; -- I am just getting an exception with Facebook. I have deleted the IDP and recreated it twice -- not sure if I am missing some subtle step.

**Comment by jennyf19** [comment] 2019-01-22 19:42
@livehop Thanks for the additional information. Can you send the exact error message you're getting? Are you using system browser or embedded webview for auth?

**Comment by livehop** [comment] 2019-01-22 19:47
I am using the system browser; attached is the Display error message I get
on my actual device

Thanks!

**Comment by livehop** [comment] 2019-01-22 19:48
![screenshot_20190122-144642](https://user-images.githubusercontent.com/11602611/51561280-c902c980-1e54-11e9-8360-a936adafc559.png)

**Comment by jennyf19** [comment] 2019-01-22 19:53
@livehop Thanks...very helpful. You're getting an error back from B2C. Did you follow the [b2c documentation for setting up a FB IDP](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-setup-fb-app)?

**Comment by livehop** [comment] 2019-01-22 19:57
I tried repeating this document twice -- not sure what is wrong; if I do it
using the 'run workflow' on azure b2c (for webapp account); the same
facebook IDP  works. For now, I am just going to remove Facebook from my
policy :(.

Thinking of deleting and recreating the Facebook IDP again (just to double
confirm I am not missing any step).

**Comment by jmprieur** [comment] 2019-01-23 03:19
Adding @parakhj 
I think that the application your created on facebook is not well configured, or you did not copy the client secret correctly. I would not think that this is an MSAL issue.
cc: @jennyf19

**Comment by livehop** [comment] 2019-01-23 14:58
Actually this was working before I went to b2conline.com Secondly, when I
test it using the webapp flow; I am able to authenticate by my jwt.ms
webpage does not show tokens returned (blank). On my android, it does not
even get to the authentication page; directly gives the exception I pasted
above.

I have deleted and re-created the ID's in Facebook and Azure twice;
following the exact instructions (I truly hope I am not making any silly
mistake) -- but it is really strange why it is not working.

If you would like me to share the webapp test url I can share it with you
but I can see why its easy to conclude I have not set it up correctly since
that is what I think also if it is working for everyone else.  (not sure
what my mistake is).

Wondering if I should screen print my facebook pages and azure pages; to
help us spot my mistake; (if that is safe).

**Comment by jennyf19** [comment] 2019-01-23 17:18
@livehop Are you using `$"https://{your-tenant-name}.b2clogin.com/tfp/{your-tenant-ID}/{policyname}"` as the authority? You mention b2conline.com above, but it should be [b2clogin.com](https://docs.microsoft.com/en-us/azure/active-directory-b2c/b2clogin). 
You can email us anything you want regarding your set-up. jeferrie@microsoft.com

**Comment by livehop** [comment] 2019-01-23 17:27
Yes I am using $"https://{your-tenant-name}.
b2clogin.com/tfp/{your-tenant-ID}/{policyname}
<http://b2clogin.com/tfp/%7Byour-tenant-ID%7D/%7Bpolicyname%7D>"

I mist-typed it as b2conline (quick typing  -- sorry for the confusion). I
am following the exact guide lines from the Azure documentation to change
to b2clogin . I used to be on the older way of doing things until I saw
that they are going to deprecate it and I put myself in trouble:(.

**Comment by parakhj** [comment] 2019-01-23 17:29
What is the reply URL that you specified in the FB app registration?
Parakh
________________________________

**Comment by livehop** [comment] 2019-01-23 17:51
My
redirect URL is :   https://<tenant name all lower case>.b2clogin.com/
<tenantname>.onmicrosoft.com/oauth2/authresp
site URL is : https://<tenant name all lower case>.b2clogin.com/

thanks

**Comment by livehop** [comment] 2019-01-24 00:46
I used the jwt.ms just as a placeholder because it was recommended in the
documentation.... I can point it to localhost or my site, however I don't
think it will change the outcome :(, since on my native app also I get an
exception.

Very strange I am getting this issue., if it helps I can share my client ID
pwds.... And recreate then later once we find the issue

**Comment by parakhj** [comment] 2019-01-24 21:31
Fiddler/network trace is probably the easiest way to track down the issue.  Other option is, could you paste the response from facebook to B2C right after click on "Facebook" to sign in

**Comment by livehop** [comment] 2019-01-24 22:05
I have the fiddler trace also from the jwt page response; the error is the
same (not properly configured); apologies for wasting all our time -- I am
going to re-configure this one last time and I will also document it screen
by screen blurring the sensitive information to see what mistake I am
making.

Following is the response header of jwt :-

https://jwt.ms/#error=server_error&error_description=AADB2C90243%3a+The+IDP%27s+client+key%2fsecret+is+not+properly+configured.%0d%0aCorrelation+ID%3a+636487c1-d96c-471d-8a5b-ecf0688e7237%0d%0aTimestamp%3a+2019-01-24+22%3a01%3a59Z%0d%0a


Please let me know where you want the fiddler log; in the mean time let me
document my mistake (I am sure I am doing something very silly).

Thanks!

**Comment by livehop** [comment] 2019-01-24 22:16
Just tried again -- configured but the same error; would you guys want to
come on my teamviewer for exactly 2-3 minutes; I can go over the changes
live and show you it is not working;
Wondering if I should just delete and start with a new facebook app from
scratch.

Let me try that.

**Comment by jennyf19** [comment] 2019-01-24 22:21
@livehop sorry you're having so many issues with this. @parakhj let me know if you want to join a call, you are the expert in this area.

**Comment by jennyf19** [comment] 2019-01-24 22:33
@livehop Thanks for the update. So, to rephrase, you were not able to update an existing app that uses login.microsoftonline.com with b2clogin.com? However creating a new FB app directly with b2clogin.com worked? 

This only happened w/the FB IDP? were you able to update other IDPs successfully?

@parakhj according to the [documentation](https://docs.microsoft.com/en-us/azure/active-directory-b2c/b2clogin) it doesn't seem like it should require creating a new app...would be nice to follow up and find the root cause so we can update docs and make sure more customers don't hit this issue. your thoughts?

**Comment by livehop** [comment] 2019-01-24 22:39
That is correct; my existing app with microsoftonline (which was working);
I tried to change the site URL's etc to b2clogin.com; and that kept giving
me an error however when I created a new app and did the same changes; that
worked. Also, right now I have two appid's on facebook both exactly
identical but only one of them works (the newly created one).

Also, this happened only for FB IDP, the other two that I tried were
Microsoft and Google (both worked fine with the existing account changes).
If you guys needed to see my screen or need any information from me; please
let me know; I am willing to change it back and reproduce it; if that helps
us.

Many thanks

**Comment by parakhj** [comment] 2019-01-24 22:53
Can you send a screenshot of your facebook settings (of the non-working app)

**Comment by livehop** [comment] 2019-01-25 01:44
Please let me know if you want to try it -- I will not delete it for now
(just incase we want to reproduce the error).

Thanks

**Comment by jennyf19** [comment] 2019-01-25 03:21
@livehop Can you email us (jeferrie@microsoft.com) a screenshot of your facebook settings for the non-working app? As asked by @parakhj above...thanks!

**Comment by jennyf19** [comment] 2019-02-04 20:12
@livehop @parakhj Do we have an update on this?

**Comment by livehop** [comment] 2019-02-05 22:15
Give me a week's time; I will remove code from my Xamarin application and
create a sample application pointing to existing profiles that don't work
for your test. We could either do a screen share or I could send that app
over to you and changes the id's later.

Regards,
Dhiru

**Comment by jennyf19** [comment] 2019-02-05 22:35
@livehop sounds good

**Comment by livehop** [comment] 2019-02-06 00:00
Hi,
While I was cleaning up my code; I am encountering an exception; (which I
am not sure why); apologies for the dumb question in advance.

I have a login page; which calls the MSAL authenication page (on the click
of a button -- Command) this is working perfectly; however I tried to get
rid of my redundant login page such that after the splashscreen I should
directly go to my MSAL login page; when I tried to do that I get an
exception; the MSAL exception I get reads

"On the Android platform, you have to pass the Activity to the UIParent
object. See https://aka.ms/msal-interactive-android for details."

The same exact code works if I load a "mock login page" and call
the AuthenticationClient.AcquireTokenAsync() method via a login command, I
am sure I am missing something silly.

Please advise if possible.

Regards,
Dhiru

**Comment by jennyf19** [comment] 2019-02-06 00:11
@livehop Here are the details on passing the activity to the UIParent on [android](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/MSAL.NET-uses-web-browser#choosing-between-embedded-web-browser-or-system-browser-on-xamarinandroid)

**Comment by jennyf19** [comment] 2019-05-03 23:22
@livehop any update on this?

**Comment by livehop** [comment] 2019-05-05 17:51
oops sorry, let me try to put a test together next week (currently
travelling); will get back to you by next Monday (May 12th).

Regards,
Dhiru

**Comment by henrik-me** [comment] 2019-06-28 22:08
@livehop : closing this one. Please re-open if you have any updates or need us to look further into this.

**Closed by henrik-me** 2019-06-28 22:08 UTC
Labels: IdP: Facebook, external, scenario:B2C
