### ISSUE TITLE
'Link Framework SDKs Only' causes MT2101 can't resolve the reference error

### ISSUE THREAD

**Issue by vikram-ma** [AzureAD/microsoft-authentication-library-for-dotnet#745] opened 2018-12-26 08:31 UTC
**Which Version of ADAL are you using ?**
Microsoft.Identity.Client 2.6.2

**Which platform has the issue?**
Xamarin iOS

**Repro**
Add Microsoft.Identity.Client 2.6.2 package to Xamarin Forms project
Set linker behavior to 'Link Framework SDKs only'
Compile+Link

**Expected behavior**
There should not be any linker error.

**Actual behavior**
Setting Linker Behavior to 'Link Framework SDKs Only' causes MTouch MT2101 error.

**Additional context/ Logs / Screenshots**
/ Users/TestApp/iOS/MTOUCH: Error MT2101: Can't resolve the reference 'System.String System.String::TrimStart(System.Char)', referenced from the method 'Microsoft.Identity.Json.Schema.JsonSchema Microsoft.Identity.Json.Schema.JsonSchemaBuilder::ResolveReferences(Microsoft.Identity.Json.Schema.JsonSchema)' in 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. (MT2101) (TestApp.iOS)

**Comment by chixlol** [comment] 2018-12-26 13:48
I can reproduce this issue with 2.6.1 and Xamarin Forms.

My Android Build fails with 'Link Framework SDKs only' and with 'None' the build runs till the end, but the App crashes during the splash screen.

**Comment by vikram-ma** [comment] 2018-12-27 00:18
@chixlol Crash in splash screen is due to MissingMethodException, it is already logged, issue number 744 https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/744

**Comment by irjudson** [comment] 2018-12-27 02:55
I am having this issue as well. In fact none of the link options compiles successfully in my Azure DevOps Pipeline -- which is quite discouraging.

**Comment by Rashun001** [comment] 2018-12-27 19:19
Seeing the same issues with DevOps Pipeline.  I raised this issue in the Visual Studio for Mac Group, and back channelling through them.  But does anyone have a direct connect with the DevOps Team.  A simple request, create an Agent that has all version of Tooling and SDK, or Libraries needs Unit Tests for DevOps?  Not sure which.

**Comment by narindermakin** [comment] 2018-12-28 00:21
I can reproduce it with version 2.6.2. The cause seems to be the TrimStart method in JsonSchemaModelBuilder. This method is not present in mscorlib version 4.0.0.0 and fails. Could have used TrimStart(new char{'#'}) instead of TrimStart('#'). 

private JsonSchema ResolveReferences(JsonSchema schema)
        {
            if (schema.DeferredReference != null)
            {
                string reference = schema.DeferredReference;

                bool locationReference = reference.StartsWith("#", StringComparison.Ordinal);
                if (locationReference)
                {
                    reference = UnescapeReference(reference);
                }

                JsonSchema resolvedSchema = _resolver.GetSchema(reference);

                if (resolvedSchema == null)
                {
                    if (locationReference)
                    {
                        string[] escapedParts = **schema.DeferredReference.TrimStart('#').**Split(new[] { '/' }, StringSplitOptions.RemoveEmptyEntries);
                        JToken currentToken = _rootSchema;
                        foreach (string escapedPart in escapedParts)
                        {
                            string part = UnescapeReference(escapedPart);

**Comment by bgavrilMS** [comment] 2019-01-02 11:34
Looking at these 2 issues

**Comment by bgavrilMS** [comment] 2019-01-02 14:00
@narindermakin - thanks for digging this up. Indeed I can see that the VSTS Hosted 2017 agent is still using  VisualStudio/15.8.7, which would explain why I can see this issue at all (I use the latest 15.9.4). 

Will investigate some more and contact the VSTS team to get an update on when the hosted agent image will be updated.

**Comment by bgavrilMS** [comment] 2019-01-02 15:33
I logged a bug on the Xamarin folk. Still investigating on Mac.

**Comment by bgavrilMS** [comment] 2019-01-02 20:42
It looks like a Mono bug. I can repro it with VS 15.8.7 on Windows. 

Please upgrade to latest VS (15.9.*) or VS for Mac.

**Comment by narindermakin** [comment] 2019-01-03 01:03
@bgavrilMS  thank you for confirming the resolution. One more assistance needed - Could you re-confirm the dependency list of packages that are needed to make version 2.6.2 version work on iOS?  The samples are using older versions and not up to date.

**Comment by irjudson** [comment] 2019-01-03 04:12
I am using the latest version of VS for mac; still have the problem with Azure Devops...

**Comment by irjudson** [comment] 2019-01-03 04:15
> It looks like a Mono or Xamarin bug. I can repro it with VS 15.8.7 on Windows.
> 
> Please upgrade to latest VS (15.9.*) or VS for Mac.

see above

**Comment by bgavrilMS** [comment] 2019-01-03 09:59
@irjudson - what agent are you using on VSTS? I just checked and all the hosted Mac agents use VS for Mac 7.7.1 or earlier. 

@narindermakin - when do you get that exception? It looks like a runtime exception - please provide more details. Are you just performing normal interactive auth in iOS in a Xamarin XForms app? I will try our Xamarin sample on iOS and report back.

**Comment by bgavrilMS** [comment] 2019-01-03 18:45
@narindermakin - I can't repro that exception. I tried with our sample https://github.com/Azure-Samples/active-directory-xamarin-native-v2 but also with an upgraded version (same code, but added to a brand new XForms project, using the latest xforms.dll)

**Comment by Rashun001** [comment] 2019-01-03 20:39
> @narindermakin - I can't repro that exception. I tried with our sample https://github.com/Azure-Samples/active-directory-xamarin-native-v2 but also with an upgraded version (same code, but added to a brand new XForms project, using the latest xforms.dll)

Which version of XForms are you using latest v.Next 4.0 or 3.x.

Also are you seeing this via Azure DevOps, or are you only running a local agent?

**Comment by bgavrilMS** [comment] 2019-01-03 20:54
I am using latest stable 3.x. I have seen this running on my local machine. It should not matter if it is local machine or Azure DevOps, it's the Visual Studio version that matters.

**Comment by narindermakin** [comment] 2019-01-03 22:09
I am using 3.4.0.1008975 last stable version of Xamarin.Forms with VS 15.9.4 on Windows paired with a Mac (cleared cache on mac also). The exception comes in the call App.PCA.AcquireTokenAsync(scopes, account, App.UiParent). Note that App.PCA.AcquireTokenSilentAsync(scopes, account, authority, false) works as expected and returns below, (since account is null)

ex = {Microsoft.Identity.Client.MsalUiRequiredException: Null account was passed in AcquiretokenSilent API. Pass in an account object or call acquireToken to authenticate.
  at Microsoft.Identity.Client.ClientApplicationBase+<AcquireTokenSilentCommonAsync>d__45....

<------App.PCA.AcquireTokenAsync(scopes, account, App.UiParent) where account is null ---->
--- inner exception ---
BlockLiteral.SetupBlock is not supported when the dynamic registrar has been linked away. (ObjCRuntime.RuntimeException)
  at ObjCRuntime.BlockLiteral.SetupBlock (System.Delegate trampoline, System.Delegate userDelegate, System.Boolean safe) [0x00002] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/ObjCRuntime/Blocks.cs:94 
  at ObjCRuntime.BlockLiteral.SetupBlockUnsafe (System.Delegate trampoline, System.Delegate userDelegate) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/ObjCRuntime/Blocks.cs:162 
  at UIKit.UIAlertActio
n.Create (System.String title, UIKit.UIAlertActionStyle style, System.Action`1[T] handler) [0x0002e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/UIKit/UIAlertAction.g.cs:106 
  at Xamarin.Forms.Platform.iOS.Platform.CreateActionWithWindowHide (System.String text, UIKit.UIAlertActionStyle style, System.Action setResult, UIKit.UIWindow window) [0x00015] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Platform.cs:311 
  at Xamarin.Forms.Platform.iOS.Platform.PresentAlert (Xamarin.Forms.Internals.AlertArguments arguments) [0x00098] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Platform.cs:329 
  at Xamarin.Forms.Platform.iOS.Platform.<.ctor>b__7_1 (Xamarin.Forms.Page sender, Xamarin.Forms.Internals.AlertArguments arguments) [0x0000a] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Platform.cs:50 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.
Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0003b] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/mcs/class/corlib/System.Reflection/MonoMethod.cs:305 
2019-01-03 16:56:43.269 LitMemMobApp.iOS[5540:577029] critical: Stacktrace:

2019-01-03 16:56:43.269 LitMemMobApp.iOS[5540:577029] critical: 
Native stacktrace:

2019-01-03 16:56:43.276 LitMemMobApp.iOS[5540:577029] critical: 	0   LitMemMobApp.iOS                    0x00000001043457d0 LitMemMobApp.iOS + 51828688
2019-01-03 16:56:43.276 LitMemMobApp.iOS[5540:577029] critical: 	1   libsystem_platform.dylib            0x0000000185a819f0 <redacted> + 56
2019-01-03 16:56:43.276 LitMemMobApp.iOS[5540:577029] critical: 	2   libsystem_pthread.dylib             0x0000000185a87020 <redacted> + 380
2019-01-03 16:56:43.276 LitMemMobApp.iOS[5540:577029] critical: 	3   libsystem_c.dylib                   0x0000000185962d78 abort + 140
2019-01-03 16:56:43.277 LitMemMobApp.iOS[5540:577029] critical: 	4   LitMemMobApp.iOS                    0x000000010445ef68 xamarin_get_block_descriptor + 8696
2019-01-03 16:56:43.277 LitMemMobApp.iOS[5540:577029] critical: 	5   LitMemMobApp.iOS                    0x0000000104385f04 mono_pmip + 225916
2019-01-03 16:56:43.277 LitMemMobApp.iOS[5540:577029] critical: 	6   LitMemMobApp.iOS                    0x000000010434542c LitMemMobApp.iOS + 51827756
2019-01-03 16:56:43.277 LitMemMobApp.iOS[5540:577029] critical: 	7   LitMemMobApp.iOS                    0x000000010434412c LitMemMobApp.iOS + 51822892
2019-01-03 16:56:43.277 LitMemMobApp.iOS[5540:577029] critical: 	8   LitMemMobApp.iOS                    0x000000010433c32c LitMemMobApp.iOS + 51790636
2019-01-03 16:56:43.277 LitMemMobApp.iOS[5540:577029] critical: 	9   LitMemMobApp.iOS                    0x0000000101542208 LitMe
mMobApp.iOS + 3580424
2019-01-03 16:56:43.278 LitMemMobApp.iOS[5540:577029] critical: 	10  LitMemMobApp.iOS                    0x00000001013957ac LitMemMobApp.iOS + 1824684
2019-01-03 16:56:43.278 LitMemMobApp.iOS[5540:577029] critical: 	11  LitMemMobApp.iOS                    0x000000010139d114 LitMemMobApp.iOS + 1855764
2019-01-03 16:56:43.278 LitMemMobApp.iOS[5540:577029] critical: 	12  LitMemMobApp.iOS                    0x000000010247119c LitMemMobApp.iOS + 19501468
2019-01-03 16:56:43.278 LitMemMobApp.iOS[5540:577029] critical: 	13  LitMemMobApp.iOS                    0x000000010150d068 LitMemMobApp.iOS + 3362920
2019-01-03 16:56:43.279 LitMemMobApp.iOS[5540:577029] critical: 	14  LitMemMobApp.iOS                    0x0000000104354d10 mono_pmip + 24712
2019-01-03 16:56:43.279 LitMemMobApp.iOS[5540:577029] critical: 	15  LitMemMobApp.iOS                    0x00000001043c1c64 mono_pmip + 471004
2019-01-03 16:56:43.279 LitMemMobApp.iOS[5540:577029] critical: 	16  LitMemMobApp.iOS                    0x00000001043c5288 mono_pmip + 484864
2019-01-03 16:56:43.279 LitMemMobApp.iOS[5540:577029] critical: 	17  LitMemMobApp.iOS                    0x00000001011dc618 LitMemMobApp.iOS + 17944
2019-01-03 16:56:43.279 LitMemMobApp.iOS[5540:577029] critical: 	18  LitMemMobApp.iOS                    0x00000001011dd884 LitMemMobApp.iOS + 22660
2019-01-03 16:56:43.279 LitMemMobApp.iOS[5540:577029] critical: 	19  Foundation                          0x000000018692842c <redacted> + 336
2019-0
1-03 16:56:43.280 LitMemMobApp.iOS[5540:577029] critical: 	20  CoreFoundation                      0x0000000185e051f0 <redacted> + 24
2019-01-03 16:56:43.280 LitMemMobApp.iOS[5540:577029] critical: 	21  CoreFoundation                      0x0000000185e05170 <redacted> + 88
2019-01-03 16:56:43.280 LitMemMobApp.iOS[5540:577029] critical: 	22  CoreFoundation                      0x0000000185e04a54 <redacted> + 176
2019-01-03 16:56:43.280 LitMemMobApp.iOS[5540:577029] critical: 	23  CoreFoundation                      0x0000000185dff920 <redacted> + 1040
2019-01-03 16:56:43.281 LitMemMobApp.iOS[5540:577029] critical: 	24  CoreFoundation                      0x0000000185dff1f0 CFRunLoopRunSpecific + 436
2019-01-03 16:56:43.281 LitMemMobApp.iOS[5540:577029] critical: 	25  GraphicsServices                    0x0000000188078584 GSEventRunModal + 100
2019-01-03 16:56:43.281 LitMemMobApp.iOS[5540:577029] critical: 	26  UIKitCore                           0x00000001b300ad40 UIApplicationMain + 212
2019-01-03 16:56:43.28
1 LitMemMobApp.iOS[5540:577029] critical: 	27  LitMemMobApp.iOS                    0x00000001024ab7d8 LitMemMobApp.iOS + 19740632
2019-01-03 16:56:43.282 LitMemMobApp.iOS[5540:577029] critical: 	28  LitMemMobApp.iOS                    0x0000000102432f2c LitMemMobApp.iOS + 19246892
2019-01-03 16:56:43.282 LitMemMobApp.iOS[5540:577029] critical: 	29  LitMemMobApp.iOS                    0x0000000102432eec LitMemMobApp.iOS + 19246828
2019-01-03 16:56:43.282 LitMemMobApp.iOS[5540:577029] critical: 	30  LitMemMobApp.iOS                    0x0000000101205420 LitMemMobApp.iOS + 185376
2019-01-03 16:56:43.282 LitMemMobApp.iOS[5540:577029] critical: 	31  LitMemMobApp.iOS                    0x000000010150d068 LitMemMobApp.iOS + 3362920
2019-01-03 16:56:43.282 LitMemMobApp.iOS[5540:577029] critical: 	32  LitMemMobApp.iOS                    0x0000000104354d10 mono_pmip + 24712
2019-01-03 16:56:43.283 LitMemMobApp.iOS[5540:577029] critical: 	33  LitMemMobApp.iOS                    0x00000001043c1c64 mono_pmip + 471004
2019
-01-03 16:56:43.283 LitMemMobApp.iOS[5540:577029] critical: 	34  LitMemMobApp.iOS                    0x00000001043c6f20 mono_pmip + 492184
2019-01-03 16:56:43.284 LitMemMobApp.iOS[5540:577029] critical: 	35  LitMemMobApp.iOS                    0x000000010433bb18 LitMemMobApp.iOS + 51788568
2019-01-03 16:56:43.284 LitMemMobApp.iOS[5540:577029] critical: 	36  LitMemMobApp.iOS                    0x000000010446d4a8 _Z9__isctypeim + 47160
2019-01-03 16:56:43.284 LitMemMobApp.iOS[5540:577029] critical: 	37  LitMemMobApp.iOS                    0x0000000101205320 LitMemMobApp.iOS + 185120
2019-01-03 16:56:43.285 LitMemMobApp.iOS[5540:577029] critical: 	38  libdyld.dylib                       0x00000001858bebb4 <redacted> + 4
2019-01-03 16:56:43.285 LitMemMobApp.iOS[5540:577029] critical: 
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
========
=========================================================The app has been terminated.

**Comment by bgavrilMS** [comment] 2019-01-09 16:00
Closing, I will update this thread when I hear back from the VSTS people about them updating the Hosted build images.

**Closed by bgavrilMS** 2019-01-09 16:00 UTC
Labels: external

**Comment by minaairsupport** [comment] 2019-01-10 01:10
I think Appcenter face the same issue 

  `CSC : error CS1705: Assembly 'AgentWay' with identity 'AgentWay, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'Microsoft.Identity.Client, Version=2.6.2.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae' which has a higher version than referenced assembly 'Microsoft.Identity.Client' with identity 'Microsoft.Identity.Client, Version=2.1.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae' `

maybe that regarding to visual studio version installed 

https://docs.microsoft.com/en-us/appcenter/build/software#visual-studio-for-mac

**Comment by bgavrilMS** [comment] 2019-01-10 10:37
Yes, App Center will have the same problem. 

The VSTS (Azure DevOps) team have a tentative deadline of end of January for updating the Hosted agents build. It seems to take longer because the new image is very large.

**Comment by bgavrilMS** [comment] 2019-01-28 18:54
@stezma  - I am sorry I do not have any update. I will ping the DevOps guys again.

**Comment by bgavrilMS** [comment] 2019-02-07 14:20
Possible workaround for VSTS https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/852#issuecomment-461318277

**Comment by kgbuddhima** [comment] 2019-05-10 15:10
I also have this issue in iOS VSTS  build.
MTOUCH : error MT2101: Can't resolve the reference 'System.String System.String::Trim(System.Char)', referenced from the method 'System.Threading.Tasks.Task`1<FFImageLoading.Work.DataResolverResult> FFImageLoading.DataResolvers.BundleDataResolver::ResolveFromBundlesAsync(System.String,System.String,FFImageLoading.Work.TaskParameter,System.Threading.CancellationToken)' in 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. 

is there any solution for this ?

**Comment by bgavrilMS** [comment] 2019-05-10 15:37
@kgbuddhima - yes, update Visual Studio

**Comment by MouthOfMadness** [comment] 2019-07-11 22:09
Is there a workaround, I just started getting this bug:

(default target) (1) ->
(_CompileToNative target) -> 
  MTOUCH : error MT2101: Can't resolve the reference 'System.String System.String::Trim(System.Char)', referenced from the method 'System.Threading.Tasks.Task`1<FFImageLoading.Work.DataResolverResult> FFImageLoading.DataResolvers.BundleDataResolver::ResolveFromBundlesAsync(System.String,System.String,FFImageLoading.Work.TaskParameter,System.Threading.CancellationToken)' in 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. [/Users/vsts/agent/2.153.2/work/1/s/Mobile/AI.Mobile.iOS/AI.Mobile.iOS.csproj]

**Comment by markrobert194** [comment] 2021-07-07 09:01
Did anyone find a fix for this?
