### ISSUE TITLE
[Bug] Fix build warning in Test App

### ISSUE THREAD

**Issue by SameerK-MSFT** [AzureAD/microsoft-authentication-library-for-dotnet#3096] opened 2022-01-07 22:14 UTC
**Logs and network traces**
NA

--- Component: --- 
com.fasterxml.jackson.core jackson-annotations 2.12.1 - Maven 

--- Found at: --- 
/s/tests/CacheCompat/CommonCache.Test.MsalJava/pom.xml

**Comment by bgavrilMS** [comment] 2022-01-13 16:41
I assume it's a duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3098

**Closed by bgavrilMS** 2022-01-13 16:41 UTC
Labels: bug, internal
