### ISSUE TITLE
`TokenCacheNotificationArgs.Account` is null when read from cache

### ISSUE THREAD

**Issue by fuocor** [AzureAD/microsoft-authentication-library-for-dotnet#3111] opened 2022-01-13 11:53 UTC
I noticed that the first time the token is read from the cache it changes the `HasTokens` but does not assign the Account to the `TokenCacheNotificationArgs` in the `OnAfterAccessAsync` method. Only after token is accessed with `AcquireTokenInLongRunningProcess` is it set.

**Which version of MSAL.NET are you using?**
4.40.0

**Platform**
ALL

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [x] On-Behalf-Of
* Daemon app 
    * [x] Service to Service calls

**Is this a new or existing app?**
a. The app is in production, and I have upgraded to a new version of MSAL.

**Expected behavior**
`TokenCacheNotificationArgs.Account` should be set.

**Actual behavior**
`TokenCacheNotificationArgs.Account` is null

**Comment by bgavrilMS** [comment] 2022-01-13 15:37
This is by design. MSAL loads one (or more) tokens from the token cache. There is no one / individual account to publish.
MSAL only knows about the account when it fetches new tokens (access token, id token etc.) and populates that field. 

What are you trying to do ? Why do you need the account info for OBO?

**Comment by fuocor** [comment] 2022-01-13 20:28
PS - my use case for OBO is not session based. I have virtual actors holding OBO tokens in order to perform downstream actions in the MSGraph and Dynamics, knowing the account when the token is pulled from the cache without going to the trouble of acquiring an access token makes things easier.

I also take issue with the naming of `ILongRunningWebApi` which has little association to an OBO flow. The OBO flow encompasses an AccessToken with a long lived RefreshToken absent of any concept of a session. by introducing session and removing refresh tokens from the original implementation the library is drifting towards a web model rather than a general use oauth library.

The change also breaks anyone who implemented caching of OBO prior to making the change, which I consider irresponsible

**Comment by jmprieur** [comment] 2022-01-14 03:58
Thanks for the feedback @fuocor 
Did you experience a regression? I'm asking, because, in a write operation you would get the account information as Bogdan wrote, but to my knowledge, this has never worked in read operations as the suggested cache key, even MSAL.NET 4.38 (introduction of the long running process), it was the hash of the token for OBO tokens, and not the user. Also MSAL did not support OBO at all until recently.

We don't want web APIs to be able to call `AcquireTokenSilent` with an account, as it would get any OBO token for the user, which would not respect conditional access policies relative to clients (think an app/user on a corporate network is allowed to call the web API, but not the same app/user from a network outside the corporate network).

The term session might be not well chosen. This is really a key which represents the original incoming token to the web API. 

As far as your scenario is concerned. What are the virtual actors ? I don't understand how they hold OBO tokens? do you mean they hold the incoming token to the web API? (in order to get OBO tokens)? and they hold it even when they expire?

**Comment by fuocor** [comment] 2022-01-14 13:46
You can think of the virtual actor as an extension of the user. Each instance of the actor has an owner and behave on-behalf-of the owner across the system. Amongst the use cases is the digital twin of a device that shares data to rest endpoints, the identity used to pushed that data comes from an obo flow that was used to configure it.

In the previous versions of MSAL the obo flow would capture the AccessToken and RefreshToken, and when pushed to the cache, contained both.

The break that I mentioned comes from the fact that stored OBO info (pre 38) cannot be read from the cache with post 38 because of the addition of a sessionId to content. In pre 38 it was the cache's responsibility to correlate the ID to storage, but now it seems to have also been embedded into the content.

The basic premise of obo is for an application to behave as the user when the user is not present. I am not sure where the logic for the conditional access policies come from. The confidential client application is added to a domain by an administrator permissions with clearly stated scopes and there must be a consent given prior to using the OBO

It seems that you are cutting out authenticated headless behavior.

**Comment by fuocor** [comment] 2022-01-14 13:54
I do understand the issue with `AquireTokenSilent` for OBO as I had raised an earlier issue on the topic, where there was only a single Account pre confidential client but no way to get it when the `GetAccounts` was deprecated. So you have made things easier from that perspective.

I have been able update my code to the `ILongRunningWebApi ` but it does break all the previously cached tokens even though the SessionId used is the same as the key I was using to correlate the cache to account.

**Comment by gabrigiunchi** [comment] 2023-05-24 09:41
@fuocor  I have your same use case and I'm having the same issue with ILongRunningWebApi.
I can migrate to the new long-running OBO but it breaks the old tokens, did you find a way to have a smooth migration?

**Comment by bgavrilMS** [comment] 2023-05-24 10:13
@gabrigiunchi - in a web api, you parse the incoming assertion. Look at the oid and tid claims. The account id is `oid.tid` (well, it's a little more complex for guest accounts). 

MSAL is not able to parse the incoming assertion, it might be encrypted etc.

**Comment by gabrigiunchi** [comment] 2023-05-24 12:55
the problem is that after calling AcquireTokenSilent, item.OboCacheKey is "" because the token does not contain user_assertion_hash anymore

<img width="626" alt="image" src="https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/22346749/d2ab75d6-f389-4bda-8760-2d6a95f7968a">

Then, when we call AcquireTokenInLongRunningProcess, this filter will fail and no refresh tokens are returned

<img width="765" alt="image" src="https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/22346749/38e62542-152c-4019-bc31-b3a70da9c7fb">

**Comment by gabrigiunchi** [comment] 2023-05-25 06:41
this is allegedly why user_assertion_hash is null when calling AcquireTokenSilent.
RequestParams doesn't have UserAssertions, thus user_assertion_hash is not set. This makes it hard to then retrieve the token given the filter mentioned above

<img width="592" alt="image" src="https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/22346749/9a94e115-0a2e-44b5-8234-5813aca0ff09">

**Comment by pmaytak** [comment] 2023-05-26 06:17
@bgavrilMS's comment https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3111#issuecomment-1561215420 explains why `AcquireTokenSilent` was updated to correctly not return OBO tokens. So in a web API you would just call `AcquireTokenOnBehalfOf` each time you need a token, which would also check the cache first.

In long-running OBO scenarios with previous MSAL versions, you would call `AcquireTokenOnBehalfOf` with a valid user token to initiate this session; save this user token somewhere; then use it to call `AcquireTokenOnBehalfOf` in your background process again to get the cached token. This original user token is needed because its hash is used as a cache key for OBO tokens.

So in order to use the older cached tokens with the newer long-running OBO API then, you'd have to either keep around that original user token or its hash. Do you have that original user assertion or do you just call `AcquireTokenSilent` right now to get the cached tokens?

**Comment by gabrigiunchi** [comment] 2023-05-30 05:41
Thanks for the explanation, now it's more clear! I did found a workaround for my problem so we can close this issue. Thanks everyone! :)

**Closed** 2023-05-30 11:19 UTC
Labels: question, answered
