### ISSUE TITLE
TokenCache.SerializeAdalV3 behavior change between 4.32.1  and 4.37.0

### ISSUE THREAD

**Issue by RandalliLama** [AzureAD/microsoft-authentication-library-for-dotnet#3246] opened 2022-03-24 00:12 UTC
**Logs and network traces**
Without logs or traces, it is unlikely that the team can investigate your issue. Capturing logs and network traces is described in [Logging wiki](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging).

**Which version of MSAL.NET are you using?**
4.32.1 -> 4.37.0

**Platform**
.NET 4.72

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [X] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

**Is this a new or existing app?**

This is a production app.

**Repro**

```csharp
var app = ConfidentialClientApplicationBuilder.Create(_clientId)
    .WithAuthority(_authority)
    .WithCertificate(authCert)
    .Build();

byte[] serializedCache = null;
app.UserTokenCache.SetAfterAccess((args) =>
{
    serializedCache = args.TokenCache.SerializeAdalV3();
});

var scopes = new[] { _resource + MsalScopeSuffix };
var userAssertion = new UserAssertion(userToken);

// Sending the x5c enables application developers to achieve easy certificate roll-over in Azure AD
var parameterBuilder = app.AcquireTokenOnBehalfOf(scopes, userAssertion)
    .WithSendX5C(true);

var result = await parameterBuilder.ExecuteAsync();
```

**Expected behavior**
Before upgrading the MSAL version TokenCache.SerializeAdalV3 always returned a non-null value.

**Actual behavior**
After upgrading the MSAL version SetAfterAccess is called twice and both times TokenCache.SerializeAdalV3 returns null.

**Comment by trwalke** [comment] 2022-03-24 00:24
I imagine this has something to our recent OBO/Cache updates. @pmaytak thoughts?

I am able to reproduce with the latest MSAL

**Comment by pmaytak** [comment] 2022-03-24 05:42
I vaguely remember some refactoring in token cache related code that might have indirectly affected this. I will check.
@RandalliLama Why do you call Serialize**Adal**V3 and not Serialize**Msal**V3?

**Comment by bgavrilMS** [comment] 2022-03-24 10:48
ADAL serialization primitives only looks at refresh token. Access tokens are not sharable between ADAL and MSAL. So this is probably by design.

**Comment by bgavrilMS** [comment] 2022-03-24 10:52
@trwalke - if you use the long running OBO (see integration tests), do you get tokens? 

I think we should disable the ADAL serialization primitives for OBO and client_credentials, i.e. throw a meaningful exception that they cannot be used.

**Comment by bgavrilMS** [comment] 2022-04-04 13:28
Closing as by design.

**Closed by bgavrilMS** 2022-04-04 13:28 UTC
Labels: Investigate, scenario:ConfidentialClient
