### ISSUE TITLE
[Bug] Unable to find keychain in entitlements.plist using MSAL and Xamarin (even though it is there!)

### ISSUE THREAD

**Issue by SophisticatedConsulting** [AzureAD/microsoft-authentication-library-for-dotnet#2972] opened 2021-10-21 07:40 UTC
### Set up:

- Windows 10 (current build/patches)
- VS 2019 (Version 16.11.5)
- Xamarin.Forms 5.0.0.2196
- Xamarin iOS
- iPhone (14.0.1) connected locally through USB
- Azure AD B2C service
- MSAL (Microsoft.Identity.Client) 4.37.0

### Steps to reproduce:

1. Build and run -
2. https://github.com/Azure-Samples/active-directory-b2c-xamarin-native.git
4. The app deploys and runs on the locally connected iPhone.
6. The create account flow runs correctly, however the attempt to create a token fails (see below for error msg)
7. Fails at:

       AuthenticationResult authResult = await _pca.AcquireTokenInteractive(B2CConstants.Scopes)
       .WithPrompt(Prompt.NoPrompt)
       .WithAuthority(B2CConstants.AuthorityPasswordReset)
       .ExecuteAsync();

Error reported:

          MSAL v 4.37.0 Microsoft.Identity.Client.MsalClientException "The application does not have keychain access groups enabled 
          in the Entitlements.plist. As a result, there was a failure to save to the iOS keychain. The keychain access group '_[TeamId].uk.
          [domain].[app]_' is not enabled in the Entitlements.plist. Also, use the WithIosKeychainSecurityGroup api to set the keychain 
          access group. See https://aka.ms/msal-net-enable-keychain-groups for more details on enabling keychain access groups 
          and entitlements."

### Further steps taken:

1. I have replaced the default AD B2C directory with my own Azure B2C AD.
2. This is correctly set up and the flows all work correctly for a Web App.
3. I can see the authentication succeeding and a token being granted for the correct App in the AD B2C logs/audit.
4. The app is being correctly instantiated:

       var builder = PublicClientApplicationBuilder.Create(B2CConstants.ClientID)
       .WithB2CAuthority(B2CConstants.AuthoritySignInSignUp)
       .WithIosKeychainSecurityGroup(B2CConstants.IOSKeyChainGroup)
       .WithRedirectUri($"msal{B2CConstants.ClientID}://auth");

5. The entitlements.plist keychain is correctly set:

       <key>keychain-access-groups</key>
       <array>
       <string>$(AppIdentifierPrefix)uk.[domain].[app]</string>
       </array>
6. The entitlements.plist is correctly set in the project (for iPhone) and the team is correct
<CodesignEntitlements>Entitlements.plist</CodesignEntitlements>

7. The URL type is correctly set in info.plist (but the code never gets this far):

        <array>
        <dict>
        <key>CFBundleURLName</key>
        <string>uk.[domain].[app]</string>
        <key>CFBundleURLSchemes</key>
        <array>
        <string>msal[guid for app]</string>
        </array>
        <key>CFBundleTypeRole</key>
        <string>None</string>
        </dict>
        </array>
8. Tried updating libraries (from 4.36 specified in the sample… no help.

My suspicion is that something is not working for the scenario of an ios device connected locally, e.g. the entitlements.plist is not being correctly included.

**Comment by ramon26cruz** [comment] 2022-05-02 18:06
I am having the same issue. Any update on this?

**Comment by bgavrilMS** [comment] 2022-12-21 16:13
Please see https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-net-xamarin-ios-considerations#troubleshooting-keychain-access

We are not able to reproduce this issue, it is almost always a configuration problem. The tools are not the best. 

Please consider moving to Maui. We will drop Xamarin support in a few months, once Xamarin is dropped as well.

**Closed by bgavrilMS** 2022-12-21 16:13 UTC
Labels: ios broker
