### ISSUE TITLE
MSAL writing null family_id value in JSON string on iOS

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-authentication-library-for-dotnet#1176] opened 2019-05-29 02:29 UTC
**Which Version of MSAL are you using ?**
i think from 3.0.1-preview

**Platform**
xamarin iOS

**Actual behavior**
In the JSON string, we are writing null for the family_id value, it should be string.empty or ""

```
  "home_account_id": "9f44...a8ca",

  "environment": "login.windows.net",

  "client_info": "eyJ1aWQiOiI5Z...RhOGNhIn0",

  "client_id": "4b0db...6f8e0",

  "secret": "OAQ...A9K1dIAA",

  "credential_type": "RefreshToken",

  "family_id": null
```

Am working on a repro of this to provide more context. will update tomorrow.

**Comment by bgavrilMS** [comment] 2019-05-29 09:18
No need to spend time reproducing this, we probably have unit tests around it. 

According to the JSON spec, null is a valid value and is equivalent to empty string: http://www.json.org/
See also: https://stackoverflow.com/questions/21120999/representing-null-in-json

I do not understand customer impact here.

**Comment by jennyf19** [comment] 2019-05-29 16:13
@bgavrilMS Here's the issue:
1) We are omitting all the other missing fields, and only writing "null" for family_id
2) Null is valid, but in Obj-C it can cause issues as it's translated to NSNull, which can result in issues for apps that don't except NSNulls.
3) When we did cache compat testing w/native iOS, we were behaving like the other SDKs and not writing null fields to JSON. This change might cause production apps to crash.

**Comment by jmprieur** [comment] 2019-05-30 21:15
@bgavrilMS : is it the issue you fixed?

**Comment by bgavrilMS** [comment] 2019-05-31 14:27
Waiting for @henrik-me with instructions on this. PR is out, but not merged.

**Comment by MarkZuber** [comment] 2019-06-18 22:06
effectively a dup of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1189 which is fixed.

**Comment by henrik-me** [comment] 2019-06-20 03:17
Yup, it's a dupe as 1189 is more generic. Should validate this scenario though with the fix for #1189

**Comment by jmprieur** [comment] 2019-07-02 14:05
this is now fixed and available in MSAL.NET 4.1

**Closed by jmprieur** 2019-07-02 14:05 UTC
Labels: Fixed, enhancement, scenario:Mobile-iOS
