### ISSUE TITLE
[Bug] When explorer.exe process is not set as shell then WAM throws exception

### ISSUE THREAD

**Issue by anurag-2911** [AzureAD/microsoft-authentication-library-for-dotnet#4115] opened 2023-05-03 00:33 UTC
**Logs and network traces**
I have captured MSAL logs
**Which version of MSAL.NET are you using?**
4.49.1.0

**Platform**
.net framework 4.8

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x ] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?

**Is this a new or existing app?**

c. This is a new app or experiment.
-->

**Repro**
1. Set any other process other than explorer.exe process as a shell by changing the registry HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon\Shell as "notepad.exe".
2. Logout and Login, so that notepad.exe is the new shell.
3. Run the sample WPF starter application to connect to a tenant using PublicClientApp.AcquireTokenInteractive.
4. Set this option to true when building the IPublicClientApplication: WithWindowsBroker(true)
5. When the default option of the explorer.exe process is the shell then everything works fine but if any other process like for example notepad.exe is the shell then WAM gives the error and can't connect to AzureAD.
6. Error as captured by MSAL logging:
  Microsoft.Identity.Client.MsalServiceException: WAM Error  Microsoft.Identity.Client.Platforms.Features.WamBroker.AadPlugin 
 Error Code: WAM_aad_provider_error_2147746132 
 Error Message:  
 WAM Error Message:  
 Internal Error Code: 2147746132 
 Is Retryable: False 
 Possible causes: 
 - Invalid redirect uri - ensure you have configured the following url in the AAD portal App Registration: ms-appx-web://microsoft.aad.brokerplugin/25356a13-d1c9-43cb-858e-88fc11631b29 
- No Internet connection 
Please see https://aka.ms/msal-net-wam for details about Windows Broker integration
   at Microsoft.Identity.Client.Platforms.Features.WamBroker.WamAdapters.CreateMsalResponseFromWamResponse(IWebTokenRequestResultWrapper wamResponse, IWamPlugin wamPlugin, String clientId, ILoggerAdapter logger, Boolean isInteractive)
   at Microsoft.Identity.Client.Platforms.Features.WamBroker.WamBroker.<AcquireInteractiveWithAadBrowserAsync>d__16.MoveNext()
8. Redirect URI is configured as everything works fine if explorer.exe is set as shell, and I can reproduce the issue easily using the starter MSAL.net application, also if needed I can upload my application also.

```csharp
IPublicClientApplication clientApp = PublicClientApplicationBuilder.Create(ClientId)
                    .WithDefaultRedirectUri()
                    .WithAuthority(AzureCloudInstance.AzurePublic, TenantId)
                    .WithWindowsBroker(true)
                    .WithLogging(new MSALLogger(), true)
                    .Build();
authResult = await clientApp .AcquireTokenInteractive(scopes)
                        .WithAccount(accounts.FirstOrDefault())
                        .WithPrompt(Prompt.SelectAccount)
                        .ExecuteAsync();

**Expected behavior**
It should launch the Microsoft Account selection form.

**Actual behavior**
WAM exception is thrown

**Possible solution**
<!--- Only if you have suggestions on a fix for the bug -->

**Additional context/logs / screenshots/links to code**
Reproduction steps are easy and I can provide my sample application which is the same as given as the starter WPF application for MSAL.NET.

**Comment by bgavrilMS** [comment] 2023-05-03 10:25
1. Please try with the latest MSAL, we made big changes in WAM interop
2. What's the scenario for changing the shell?

**Comment by common-tasks** [comment] 2023-05-04 05:05
1. We have done most of the testing using the version of the library which has this issue, I can try changing the library version now, but it will need complete testing. I will get back to this one day from today.
2. Our product "ZENworks" is used by some organizations like hospitals and schools where we display our desktop application as a shell, so that is the only application running for the end user, and the end-user launches other custom applications using that desktop application, for example, one school application, etc. It is a big use case for us.

**Comment by MSamWils** [comment] 2023-05-04 23:03
Hi @common-tasks , the broker path required windows OS inbox apps to run which has dependency on the explorer.exe. Is your scenario running in the remote session like Azure Virtual Desktop (AVD) or Citrix?

**Comment by common-tasks** [comment] 2023-05-05 01:39
No, it is not in the remote session, I can reproduce the issue on a physical machine like the laptop having Windows 10 OS.

**Comment by common-tasks** [comment] 2023-05-08 16:43
Hello @bgavrilMS: I tried with the latest MSAL, and the result is the same.That is when explorer.exe is not the shell it can't connect.

_```
Error Acquiring Token:
MSAL.Desktop.4.53.0.0.MsalServiceException: 
	ErrorCode: unknown_broker_error
Microsoft.Identity.Client.MsalServiceException: Unknown Status: Unexpected
Error: 0x80040154
Context: (pii)
Tag: 0x21420087 (error code 2147746132) (internal error code 557973639)
   at Microsoft.Identity.Client.Platforms.Features.RuntimeBroker.WamAdapters.ThrowExceptionFromWamError(AuthResult authResult, AuthenticationRequestParameters authenticationRequestParameters, ILoggerAdapter logger)
   at Microsoft.Identity.Client.Platforms.Features.RuntimeBroker.WamAdapters.HandleResponse(AuthResult authResult, AuthenticationRequestParameters authenticationRequestParameters, ILoggerAdapter logger, String errorMessage)
   at Microsoft.Identity.Client.Platforms.Features.RuntimeBroker.RuntimeBroker.<AcquireTokenInteractiveDefaultUserAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Platforms.Features.RuntimeBroker.RuntimeBroker.<AcquireTokenInteractiveAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Broker.BrokerInteractiveRequestComponent.<FetchTokensAsync>d__9.MoveNext()
```_

**Comment by bgavrilMS** [comment] 2023-05-08 17:52
Can you get a token silently for the Windows user - see https://github.com/bgavrilMS/MSAL-SingleAccount-SSO/blob/master/SSO/Program.cs#L175

**Comment by common-tasks** [comment] 2023-05-09 01:39
Hello @bgavrilMS: Yes, I am following the recommended calling pattern, that is I first try to get the token silently, and on getting "MsalUiRequiredException" I call interactively. So if nothing is there in the cache, i.e. for the first-time MSAL.NET application interacting with AAD, it gets MsalUiRequiredException.

**Comment by MSamWils** [comment] 2023-05-09 05:45
Hi @common-tasks, in order to exercise the broker flow on windows, it required the explorer.exe to be activated. If the explorer.exe didn't get started due to any reason, calling WAM via MSAL will be failed with 0x80040154 error.
May I ask did you try to use the immersive shell in your environment setup?

**Comment by common-tasks** [comment] 2023-05-09 19:09
Hello @MSamWils, the desktop application which runs as a shell in place of the explorer is fully tested on the shell option and is in production for a long time, changing to the immersive shell is not an option.

**Comment by common-tasks** [comment] 2023-05-12 06:17
Hello @MSamWils, I see that issue is marked "requires more info" , can you please change that state or any info is still needed?

Thanks!
Anurag

**Comment by common-tasks** [comment] 2023-05-17 05:39
Hello @MSamWils, Any plans to fix this bug, if yes, when can we expect the fix?

**Comment by localden** [comment] 2024-07-09 05:30
@anurag-2911 - this is a fairly uncommon scenario so we will close it for the time being. As it was mentioned above, the Windows authentication broker, in the current implementation, expects to interact with `explorer.exe`.

**Closed by localden** 2024-07-09 05:30 UTC
Labels: bug, external, P3, WAM, scenario:Desktop, public-client, cpp_wrapper_issue
