### ISSUE TITLE
Please update Xamarin.Android.Support.* dependencies to 28.0.0.3 on MSAL and sample

### ISSUE THREAD

**Issue by tranb3r** [AzureAD/microsoft-authentication-library-for-dotnet#1600] opened 2020-01-29 11:19 UTC
**Which Version of MSAL are you using ?**

Microsoft.Identity.Client 4.8.1-preview1

**Platform**

Xamarin.Forms (android app)

**Repro**

Build for android a xamarin.forms app that uses both xamarin.essentials and microsoft.identity.client (most recent versions).
This results in a nuget version conflict caused by obsolete versions in microsoft.identity.client dependencies:

```
NU1107: Version conflict detected for Xamarin.Android.Support.Collections. Install/reference Xamarin.Android.Support.Collections 28.0.0.3 directly to project MyApp.Android to resolve this issue. 
 MyApp.Android -> MyApp.Core -> Xamarin.Essentials 1.4.0-pre2 -> Xamarin.Android.Support.CustomTabs 28.0.0.3 -> Xamarin.Android.Support.Collections (= 28.0.0.3) 
 MyApp.Android -> MyApp.Core -> Microsoft.Identity.Client 4.8.1-preview1 -> Xamarin.Android.Support.v7.AppCompat 28.0.0.1 -> Xamarin.Android.Support.Collections (= 28.0.0.1).
```
**Possible Solution**

Update xamarin.android.support.* dependencies to 28.0.0.3.

**Comment by bgavrilMS** [comment] 2020-01-29 11:23
We will take a look, but NuGet suggests an easy solution for this - take a dependnecy on Xamarin.Android.Support.Collections 28.0.0.3 directly from your app and this will be used to resolve the conflict.

**Comment by tranb3r** [comment] 2020-01-29 11:32
My app is using androidx, so it's kind of weird to add new dependencies to android support libs when I'm actually supposed to remove them.

**Comment by bgavrilMS** [comment] 2020-01-29 12:55
@jmprieur @henrik-me - I propose to take this one in 4.9 to be in sync with Xamarin.Essentials. Accordding to the SemVer spec, this is (arguably) not a breaking change:

https://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api

**Comment by jmprieur** [comment] 2020-01-29 22:54
I'm not oppposed  @bgavrilMS 
can we update the Xamarin sample at the same time (if needed) to undersstand what the customer pain will be?

**Comment by bgavrilMS** [comment] 2020-01-30 10:58
Tentatively assigned to 4.9 then, since we have a bunch of work on Android as well.

**Comment by tranb3r** [comment] 2020-02-15 17:44
Now that androidx has been officially released, could you please skip this task and migrate directly to androidx ?

**Comment by tranb3r** [comment] 2020-04-04 08:18
Any progress ?

**Comment by NunoBem** [comment] 2020-05-08 11:16
Looking forward for the migration to AndroidX.

**Comment by jmprieur** [comment] 2020-12-14 19:59
Closing as duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1841

**Closed by jmprieur** 2020-12-14 19:59 UTC
Labels: Feature Request, P2, scenario:Mobile-Android
