### ISSUE TITLE
[Feature Request] For MAM scenarios, check internally if broker is available

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-authentication-library-for-dotnet#3303] opened 2022-05-05 05:41 UTC
**Actual**
True MAM (Mobile App Management) implementation in iOS and Android requires broker to be installed on the device. If broker is not installed, it falls back to the browser which shows an error because it can't handle the scenario. User has to manually check if broker is available and let the user know.

**Expected**
Investigate if it's possible in the MSAL mobile code to determine if a MAM scenario is happening and if broker is installed; and if not, to throw a meaningful exception.

**Comment by bgavrilMS** [comment] 2023-02-20 16:13
How is this a feature and not a bug?

**Comment by bgavrilMS** [comment] 2023-02-20 16:13
Closing for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3966

**Comment by pmaytak** [comment] 2023-02-22 18:59
> How is this a feature and not a bug?

This issue is different from #3366. #3366 looks like an actual bug because we either don't handle the install broker URL in all scenarios or it's simply not sent from ESTS. This is a feature request to check if it's a True MAM scenario + broker is not installed,  immediately throw an error.

**Comment by bgavrilMS** [comment] 2023-02-23 14:34
Thanks for clarifying @pmaytak

**Comment by bgavrilMS** [comment] 2024-05-20 16:27
Rejected. Not asked by customers. Should be handled internally by msal_runtime.

**Closed by bgavrilMS** 2024-05-20 16:27 UTC
Labels: scenario:Mobile-iOS, scenario:Mobile-Android, Feature Request, public-client
