### ISSUE TITLE
[Bug] MultipleMatchingTokensDetected in AcquireTokenInLongRunningProcess for Service Principals

### ISSUE THREAD

**Issue by SameerK-MSFT** [AzureAD/microsoft-authentication-library-for-dotnet#3913] opened 2023-01-23 23:11 UTC
**Logs and network traces**
Received logs from partner. Cannot make them public.

**Which version of MSAL.NET are you using?**
4.47.2

**Platform**
Web

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [X] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

**Is this a new or existing app?**
Existing

**Repro**
In single partition, when user token expires and long running process attempts to acquire token by service principle (SP). The service principle does not have the home account id. As a result, both the expired user token and the new token acquired by SP are stored in the same partition in the cache.
This results in “MultipleMatchingTokensDetected” exception.
This can affect percentage of users in long running process whose token has expired.

**Expected behavior**
The keys should be filtered by home account id.

**Actual behavior**
Filtering by home account id is skipped. 

**Possible solution**
Use Microsoft.Identity.Web Token caching or use different token for custom cache keys.

**Comment by bgavrilMS** [comment] 2023-01-24 12:20
@SameerK-MSFT - please add @pmaytak 's investigation and test suggestion here.

**Comment by bgavrilMS** [comment] 2023-01-26 13:07
Ping on this @SameerK-MSFT. Can you please update this bug to make it more actionable?

- explain what is the actual problem and how it manifests
- explain the impact on the user
- ok to provide suggestion for fix, but the current suggestion might be wrong (filtering by home account id is not possible because where do you get the home account id from?)

**Comment by pmaytak** [comment] 2023-01-26 21:47
@bgavrilMS We add the client info param to OBO requests, so we should have home account id for user OBO flows?

**Comment by bgavrilMS** [comment] 2023-01-30 15:46
@pmaytak - maybe i'm not understanding this, but when you look in the cache you only have the initial assertion? You do not have client info.

**Comment by pmaytak** [comment] 2023-02-01 07:17
> @pmaytak - maybe i'm not understanding this, but when you look in the cache you only have the initial assertion? You do not have client info.

Yep. The account from request is null. I was just focusing on the other part of this, that we do get client info from AAD and cache it.

**Comment by bgavrilMS** [comment] 2023-02-01 10:32
Yes, we have the client_info and the hash(assertion) in the cache and can make use of that. 

But when the developers calls `AcauireTokenByOBO(assertion)` and we try to serve a token from the cache, we won't have `client_info`. So there's nothing to match the client_info from the cache to. We only have the assertion.

**Comment by pmaytak** [comment] 2023-02-01 22:49
Yea, so doesn't seem like we can do much here.

**Comment by bgavrilMS** [comment] 2023-02-02 12:57
Let's close this and follow up after the ICM is root caused.

**Comment by pmaytak** [comment] 2023-02-25 07:29
Update:
After further investigation, the primary cause is ESTS doesn't return an ID token for a refresh grant for service principal On-Behalf-Of flow. However, the ID token is returned for an OBO grant for service principal, which causes an inconsistency in cache keys and related logic (home account ID being empty).
Waiting on a fix on ESTS side.

**Comment by bgavrilMS** [comment] 2023-02-27 12:24
Once id token is issued on ESTS side, will this scenario "just work" i.e. without MSAL upgrade?

**Comment by pmaytak** [comment] 2023-02-27 21:28
If the existing cache is empty or there's only one token (with home account ID) then this will just work.
If the cache is already in invalid state (two ATs):
- if AcquireTokenForLROBO is called - FindAT method will still throw the multiple token exception, whether the ATs are expired or not, since the expiry is checked after the token count is checked.
- if InitiateLROBO is called, same result as above, since we check cache first.
- If Travis's changes are merged, then InitiateLROBO with a new assertion will immediately get new AT, replace one in the cache, and return it. But AcqurieTokenForLROBO will still fail, since the AT without the home account ID won't be overwritten or removed from the cache.

So manual steps would be needed to either expire/delete the cache entry or use a different cache key. If we add the RemoveLROBO API, then we could update the calling pattern, if exception happens, call RemoveLROBO(key), then call Initiate again or something like that.

cc @trwalke

**Comment by pmaytak** [comment] 2023-04-19 09:08
The fix is in the progress of being deployed to prod.

General call pattern idea is to call `AcquireTokenInLongRunningProcess` first to check the cache for the token, call `StopLongRunningProcessInWebApiAsync` to clear the cache from the tokens that cause the error, then call `InitiateLongRunningProcessInWebApi` to retrieve updated tokens (which doesn't check the cache).

I don't think there's a way to remove specific access tokens in this case except for clearing the cache.

**Comment by pmaytak** [comment] 2023-05-11 02:28
The fix deployment to prod is complete.

**Closed by pmaytak** 2023-05-11 02:28 UTC
Labels: bug, P2, external, cache, ICM, long-running-obo
