### ISSUE TITLE
[Feature Request] Enable legacy username and password authentication

### ISSUE THREAD

**Issue by weitzhandler** [AzureAD/microsoft-authentication-library-for-dotnet#1898] opened 2020-06-20 23:13 UTC
Please add functionality to MSAL.NET so that it can operate on its own to authenticate legacy username/password users, JWT tokens and other scenarios outside the scope of Azure.

**Describe the solution you'd like**
Allow MSAL to work outside the scope of Azure AD too.

- IdentityServer/IDentityModel
- Custom implementation

**Comment by jmprieur** [comment] 2020-06-21 14:45
MSAL.NET supports username/password authentication on public client applications. See

Though, considering your question, proposing to close this issue as a duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1538

**Closed** 2020-10-13 00:58 UTC
Labels: Feature Request, duplicate, enhancement
