### ISSUE TITLE
[Bug] Integrated Windows Auth with Conditional Access

### ISSUE THREAD

**Issue by Toukiletoukan** [AzureAD/microsoft-authentication-library-for-dotnet#1880] opened 2020-06-11 15:14 UTC
**Which Version of MSAL are you using ?**
MSAL 4.14.0

**Platform**
.Net 4.7.2

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [X] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

**Is this a new or existing app?**
new app

**Repro**

```csharp
        static void Main(string[] args)
        {
            string clientid = "xxx";
            string authority = "https://login.microsoftonline.com/xxx/v2.0";
            string[] apiScope = new string[1] { "api://xxx/Api.Access" };

            IPublicClientApplication app = PublicClientApplicationBuilder.Create(clientid)
                                          .WithAuthority(authority)
                                          .Build();

            var accounts = app.GetAccountsAsync().Result;
            AuthenticationResult result;
            try
            {
                result = app.AcquireTokenSilent(apiScope, accounts.FirstOrDefault())
                            .ExecuteAsync().Result;
            }
            catch (MsalUiRequiredException)
            {
                result = app.AcquireTokenByIntegratedWindowsAuth(apiScope)
                    .ExecuteAsync()
                    .Result;
            }

            var token = result.AccessToken;

            Console.WriteLine(token);
            Console.Read();
        }

```

**Expected behavior**
The code should get an access token to access the Api and print it

**Actual behavior**
AcquireTokenByIntegratedWindowsAuth generate an exception:

AADSTS53001: Device is not in required device state: domain_joined. Conditional Access policy requires a domain joined device, and the device is not domain joined.
Trace ID: 6c36a62f-1eb1-4db6-9d2a-2a0588c1f300
Correlation ID: aaf204f3-d967-44ce-b7a6-a6fb40482f50
Timestamp: 2020-06-11 15:00:23Z

**Additional context/ Logs / Screenshots**

Conditional Access policy is activated on our AAD tenant but the code is executing on a compliant device. This code works if we try to get an access token for the graph api, using the scope "User.read".

Thanks for your help

**Comment by bgavrilMS** [comment] 2020-06-12 16:36
@trwalke - thoughts?

**Comment by trwalke** [comment] 2020-06-12 21:29
It looks like this is working for graph because it does not have the same conditional access policy applied to it. The apiScope however required device auth from the looks of it. 

My understanding is that the only way to do device auth on windows is with PKeyAuth on windows 8.1 and below or with WAM which I think is limited to V1 only. 

@bgavrilMS I would reach out to someone from conditional access or intune. There are contacts in our .NET oneNote

**Comment by Toukiletoukan** [comment] 2020-06-19 10:03
Thanks for your help @trwalke and @bgavrilMS 

Is there any samples of WAM usage in console app ?
@bgavrilMS have you been able to reach out to someone from conditional access or intune ?

**Comment by alextok** [comment] 2020-07-12 00:45
[WAMDesktop.zip](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/4907822/WAMDesktop.zip)
This is example how to integrate with WAM. Feel free to ask any questions.

**Comment by bgavrilMS** [comment] 2020-08-03 12:12
Closing as duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/643

**Closed by bgavrilMS** 2020-08-03 12:12 UTC
Labels: bug, duplicate
