### ISSUE TITLE
Does this library support Shared Device Mode?

### ISSUE THREAD

**Issue by carmalou** [AzureAD/microsoft-authentication-library-for-dotnet#2387] opened 2021-02-03 18:00 UTC
### Documentation Related To Component:
Shared Device Mode in Microsoft.Identity.Client

### Please check those that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [x] needs example

### Description Of The Issue
I have been tasked with implementing shared device mode into a Xamarin app, using this MSAL library to interface back with Azure. I have reviewed [this documentation on Shared Device Mode](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-android-shared-devices). However this documentation is for Java android apps and refers to JSON config files.

I checked in the `PublicClientApplicationBuilder` class to see if any properties matched the java documentation, but none appear to. (Looking for something like `"shared_device_mode"` similar to the Java docs.)

At this moment, I have not been able to confirm if this is a feature supported by this library, or if so, how to implement it as I cannot find any of the props I'm searching for.

TIA!

**Comment by jmprieur** [comment] 2021-02-03 18:03
@carmalou : no it does not yet.
We are looking at providing a wrapper around the native iOS and Android libraries to support the same as all they do. Would you like this solution?

**Comment by carmalou** [comment] 2021-02-03 18:04
It would be very helpful for my project, yes!

**Comment by carmalou** [comment] 2021-02-03 18:21
@jmprieur is there any sort of work-around you could recommend for the meantime? We have a scenario where front-line workers are using shared devices, and are expected to use microsoft authenticator on the same shared device for MFA. The concern is that the users won't want to sign in twice (sign in to authenticator, sign in the app, then use authenticator for MFA).

Is there any sort of existing solution for this?

**Comment by jmprieur** [comment] 2021-02-08 13:21
@trwalke, @bgavrilMS @henrik-me what would you suggest?

**Comment by henrik-me** [comment] 2021-02-10 23:35
There is no good workaround to get all the capabilities needed for this scenario (also named FLW) however you can enforce only one account in the app at all times, and that way you will be able to mimic some of the behaviors of shared device mode.

**Comment by carmalou** [comment] 2021-02-14 06:07
@henrik-me both android and iOS, no desktop functionality needed that I am aware of.

**Comment by carmalou** [comment] 2021-02-14 06:08
@henrik-me Just Android and iOS. No desktop functionality needed.

**Comment by bgavrilMS** [comment] 2023-08-23 15:27
Closing as duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2910

**Closed by bgavrilMS** 2023-08-23 15:27 UTC
Labels: scenario:Mobile-iOS, scenario:Mobile-Android
