### ISSUE TITLE
[Bug] (maybe) Login error with external IDP

### ISSUE THREAD

**Issue by AnthonyGiretti** [AzureAD/microsoft-authentication-library-for-dotnet#4488] opened 2024-01-08 20:33 UTC
### Library version used

8.0.0

### .NET version

.NET 8

### Scenario

ConfidentialClient - web site (AcquireTokenByAuthCode)

### Is this a new or an existing app?

This is a new app or experiment

### Issue description and reproduction steps

have an issue with my Blazor application which uses MSAL and Azure AD.
When I use an external identity provider where Azure refers to for authentication, the redirection works fine, BUT, while redirecting, my Blazor apps says "User cancelled the flow" and the authentication fails, then I try to log again (Since i'm authenticated to my external provider, whatever the previous error), and I'm able to connect to my session and issue an ID token and Access Token. It happens whatever the login mode I use : Popup or redirect.

It does not happen when Azure AD is the Identity provider, everything is working fine.

Does somebody know what's going on?

![image](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/21200167/06f098c4-dbe6-41a5-9036-f9e39541dc85)

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by jmprieur** [comment] 2024-01-09 00:56
@AnthonyGiretti : are you using Microsoft.Identity.web?

**Comment by neha-bhargava** [comment] 2024-01-09 04:49
Are you using ConfidentialClient - web site (AcquireTokenByAuthCode) and ManagedIdentityClient - managed identity?

Can you share the code where you are using MSAL?

**Comment by AnthonyGiretti** [comment] 2024-01-09 14:48
I'm using the Implicit flow with Blazor, so it's made via the website:
For the rest of the code i'm using the Blazor template here:
https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/hosted-with-microsoft-entra-id.md

public class Program
{
    public static async Task Main(string[] args)
    {
        var builder = WebAssemblyHostBuilder.CreateDefault(args);
        builder.RootComponents.Add<App>("app");

        builder.Services.AddScoped(sp => new HttpClient { BaseAddress = new
Uri(builder.HostEnvironment.BaseAddress) });

        // Provides support for authenticating the users.
        builder.Services.AddMsalAuthentication(options =>
        {
            builder.Configuration.Bind("AzureAd",
options.ProviderOptions.Authentication);
            options.ProviderOptions.DefaultAccessTokenScopes.Add("
https://graph.microsoft.com/User.Read"); // This is in the Microsoft doc
            options.ProviderOptions.Cache.CacheLocation = "sessionStorage";
        });

        await builder.Build().RunAsync();
    }
}


[image: created with MySignature.io]
<https://mysignature.io/?utm_source=logo>
Anthony Giretti
Blogger, Speaker MVP, MCSD
mobile: +1 514 557 1380 <+1+514+557+1380>
website: https://anthonygiretti.com
email: ***@***.***


Le lun. 8 janv. 2024 à 23:49, Neha Bhargava ***@***.***> a
écrit :

**Comment by AnthonyGiretti** [comment] 2024-01-09 14:59
@jmprieur No. I'm using the default Blazor template (Microsoft example) which implements Implicit Flow.

**Comment by neha-bhargava** [comment] 2024-01-09 21:33
Looks like you are using the [Authentication Package](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/hosted-with-microsoft-entra-id.md#authentication-package-1) section of the tutorial. For some reason the link is broken for MSAL. Not sure if MSAL.Net is used here. Seems more like MSAL.js

**Comment by AnthonyGiretti** [comment] 2024-01-09 22:05
What should I do if the Microsoft sample doesn't work? It used to work in previous version

**Comment by neha-bhargava** [comment] 2024-01-09 22:41
I think you can open an issue on the github repo for [Microsoft.Authentication.WebAssembly.Msal](https://www.nuget.org/packages/Microsoft.Authentication.WebAssembly.Msal) since you are referencing it directly and they might be able to suggest further. 

Are there any specific logs that suggest the issue is on the MSAL's side? If there are then can you share those logs?

**Comment by AnthonyGiretti** [comment] 2024-01-09 23:02
I'm confused.
What's the difference between microsoft-authentication-library-for-dotnet
<https://github.com/AzureAD/microsoft-authentication-library-for-dotnet> repo
and MASL, isn't the same team?
[image: created with MySignature.io]
<https://mysignature.io/?utm_source=logo>
Anthony Giretti
Blogger, Speaker MVP, MCSD
mobile: +1 514 557 1380 <+1+514+557+1380>
website: https://anthonygiretti.com
email: ***@***.***


Le mar. 9 janv. 2024 à 17:41, Neha Bhargava ***@***.***> a
écrit :

**Comment by bgavrilMS** [comment] 2024-01-10 11:50
@pmaytak - can you please help re-route this issue to the correct team? Afaik Blazor scenarios are implemented with MSAL JS.

**Comment by AnthonyGiretti** [comment] 2024-01-10 15:12
Thanks


Anthony Giretti
Blogger, Speaker MVP, MCSD
mobile: +1 514 557 1380
website: https://anthonygiretti.com
email: ***@***.***

**Comment by jmprieur** [comment] 2024-01-10 17:56
> @jmprieur No. I'm using the default Blazor template (Microsoft example) which implements Implicit Flow, so I guess via ConfidentialClient - web

Hello @AnthonyGiretti 
Unless you are still on ASP.NET Core 3.1, Blazorwasm does no longer use the implicit flow but the auth code flow. This might be the problem. Your app registration should use a **Web** redirect URI (not a SPA one)

To give a bit of context, Blazorwasm is not using MSAL.NET, but MSAL.js called by the ASP.NET core libraries.

**Comment by AnthonyGiretti** [comment] 2024-01-10 23:25
Thanks, I hear what you say but,

There is something I don’t understand:
1- I took the Microsoft example on GitHub which is in .NeT 8
2- it works fine when the IDP is Azure Entra ID, it does not when the IDP
is external such as go daddy

Can you clarify on this please?


Anthony Giretti
Blogger, Speaker MVP, MCSD
mobile: +1 514 557 1380
website: https://anthonygiretti.com
email: ***@***.***

**Comment by AnthonyGiretti** [comment] 2024-01-10 23:28
@jmprieur

Does it help if I capture in video my scenario? It’s literally the
Microsoft example



Anthony Giretti
Blogger, Speaker MVP, MCSD
mobile: +1 514 557 1380
website: https://anthonygiretti.com
email: ***@***.***

**Comment by pmaytak** [comment] 2024-01-11 06:24
@AnthonyGiretti Microsoft.Authentication.WebAssembly.Msal uses MSAL JavaScript. You can create an issue in their [MSAL JS repo](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues). They would know the details of the implementation.

**Comment by bgavrilMS** [comment] 2024-01-11 11:58
I'm going to close this as moving issues between repos is not very helpful.

**Closed by bgavrilMS** 2024-01-11 11:58 UTC
Labels: requires more info, external
