### ISSUE TITLE
[Feature Request] Add information about proactive refresh to AuthenticationResultMetadata

### ISSUE THREAD

**Issue by rymeskar** [AzureAD/microsoft-authentication-library-for-dotnet#2926] opened 2021-10-01 14:52 UTC
Recently, proactive token refresh (refresh_in) has been introduced to MSAL. In the [AuthenticationResultMetadata](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/master/src/client/Microsoft.Identity.Client/AuthenticationResultMetadata.cs#L9), we would like to know whether the given request triggered a pro-active refresh or not. This way, we could have more extensive information about the behavior and performance of our cache.

**Comment by bgavrilMS** [comment] 2021-10-01 14:55
I am going to close this as a duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2832 which is in progress right now

**Closed by bgavrilMS** 2021-10-01 14:55 UTC
Labels: enhancement, Feature Request
