### ISSUE TITLE
Logout on device

### ISSUE THREAD

**Issue by harmjonker** [AzureAD/microsoft-authentication-library-for-dotnet#1593] opened 2020-01-23 09:48 UTC
I have been looking at a proper way to implement a signout feature, meaning, remove all tokens for a given account from a device.
From browsing the internet I conclude this is problematic because of the session token the system webview caches in a cookie. It is prossible to remove all tokens from the cache but because of the session token cookie new tokens will be issued without new login.
Does MSAL.net offer any solution for this?

**Comment by harmjonker** [comment] 2020-01-23 09:50
Additionally:  In my use cases we have Xamarin built apps on Android devices that consume api's in Azure.

**Comment by bgavrilMS** [comment] 2020-01-23 11:40
Hi @harmjonker - you have a bit of control over how the browser behaves. The [OAuth2 spec](https://tools.ietf.org/id/draft-hunt-oauth-v2-user-a4c-01.html#Authentication_Request) specifies the concept of prompt for this purpose and MSAL exposes this. 

```csharp
var pca = PublicClientApplicationBuilder.Create(<client_id>).Build();
var authResult = await pca.AcquireTokenInteractive(scopes).WithPrompt(Prompt.ForceLogin).ExecuteAsync();
```

This ensures that the user gets prompted for a password even if there is a browser session that could authenticate him / her. Will this work?

Otherwise, there is no way to clear the browser cookies and we do not recommend. There's some low-level code where you can delete all cookies from a .NET app using an embedded browser, but we don't recommend using that. 

@jmprieur - do you have any other suggestion here?

**Comment by jspuij** [comment] 2020-11-27 08:16
@bgavrilMS A common way (although not an ideal UX experience, especially on the apple OSes if you use [ASWebAuthenticationSession](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession)), is to use the same flow as sign in, but with the logout URL instead of the authorize URL and a logout-callback instead of the normal redirect url.
After confirmation of the redirect you can rely on the cookies being cleared and you can empty the token cache afterwards.

The "do you want to login" prompt that ASWebAuthenticationSession produces can be prevented by using a [private browsing session](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession/3237231-prefersephemeralwebbrowsersessio).

**Comment by jspuij** [comment] 2020-11-30 12:34
There was a bit of discussion about this in https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/425 as well.

**Comment by bgavrilMS** [comment] 2020-11-30 12:40
Hi @jspuij - I think the main question here is "what are you trying to achieve"? 

There are a set of scenarios collectively known as "First Line Worker" scenarios, where the idea is that the device is passed on from worker to worker, for example in a shop where employees pass it on as their shit ends. It is not ok for employee 2 to be able to login as emploee1 via the browser session. Is this what you are tying to achieve?

https://techcommunity.microsoft.com/t5/azure-active-directory-identity/new-identity-features-help-empower-essential-firstline-workers/ba-p/1257356

MSAL.Xamarin does not have support for this scenarios, but MSAL.Android and MSAL.iOS do. We are trying to see what's the best way to bring these scenarios to Xamarin as well, we are experimenting with creating Xamarin wrappers over the native libraries instead of reimplementing features. But I do not have an ETA for this yet.

The other scenario I can think of is that you want users to re-login (i.e. re-enter their creds) every X hours. This can be achieved via the "sign-in frequency" from Conditional Access (details [here](https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/howto-conditional-access-session-lifetime#user-sign-in-frequency))

Finally, if all else fails, you can implement your own UI logic via [ICustomWebUi](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.extensibility.icustomwebui?view=azure-dotnet) extensibility point.

**Comment by bgavrilMS** [comment] 2020-11-30 12:41
CC @jmprieur

**Comment by Strifex** [comment] 2021-08-02 21:26
@bgavrilMS hey just curious if there is any ETA for this? My team is currently working on a shared device scenario where the ability to logout properly from the mobile device would be very useful

**Comment by jennyf19** [comment] 2021-08-02 23:37
@Strifex we currently have no ETA for shared device mode. @SameerK-MSFT is looking into a binding library so c# customers can use our native libraries, which do support shared device mode, but we are not able to give an ETA at this time. If you're interesting in testing anything at some point, please let @SameerK-MSFT know.

**Comment by TheXenocide** [comment] 2022-10-24 23:50
Comment migrated from #589 

Wouldn't it be more appropriate for a sign out request to actually use the browser to tell Azure AD that it intends to sign the current user out (with token), so that Azure AD can also remove any service-side data associated with the issued token (e.g. invalidate the token so that if it has already been compromised it can no longer be used)? The response/handshake that takes place in the browser would be able to remove cookies from whatever system/embedded browser was used to sign the user in too, without any hacky manual cookie manipulation on the client-side.

We're migrating a mobile app right now that had sign out functionality built in previously when it was based around a custom identity broker which would delete the refresh token and such but the functionality doesn't appear to have an equivalent that we can map to during this migration to Azure AD without the broker. I know there's existing functionality in the Azure AD portal and Graph API to revoke refresh tokens, but it seems like it would be sensible to allow an application to intentionally request the refresh token that it acquired be revoked if it knows it should no longer be valid.

**Comment by bgavrilMS** [comment] 2022-10-25 14:42
@TheXenocide - I am not aware of this capability at the app level in AAD. AAD prefers to solve this problem with [Conditional Access](https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/concept-conditional-access-policy-common) and with manual refresh token and session revocation.

You can also bridge the gap between a "bad" event and AT expiration (a cached AT will still be usable even if employee gets fired for example) by using Continuous Access Evaluation - https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/concept-continuous-access-evaluation

**Comment by TheXenocide** [comment] 2022-10-25 19:19
Fair enough. The authentication broker we were using was based on the open source IdentityServer packages, but the source was at least in our control so it's quite feasible that the functionality was only in the broker, not something it passed along upstream to the Azure AD or other 3rd party providers. I can see the merit in removing the locally cached token and understand that there are other strategies to mitigate potentially compromised tokens, I was mostly thinking about the request to clear cookies/browser-based AAD state from the first ticket I stumbled on, since it seems like the most effective way to control cookies in a cross-platform way would just be to send the user to a URL that removed them (and possibly invalidated the associated data server-side). It's also easier to follow than trying to store some flag of whether the user explicitly clicked Logout the last time they were in the application so that you can force them to be prompted the next time they open the app.

**Comment by bgavrilMS** [comment] 2022-10-25 20:59
@jmprieur - do you know more about global / cookie sign-out?

**Comment by bgavrilMS** [comment] 2023-12-14 14:42
Will close this as duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1593

**Closed by bgavrilMS** 2023-12-14 14:42 UTC
Labels: scenario:Mobile-iOS, scenario:Mobile-Android, Feature Request, public_client

**Comment by adamgf1** [comment] 2023-12-14 16:53
Hi @bgavrilMS , this issue is issue #1593, did you mean to mark it as a duplicate of a different issue?

**Comment by bgavrilMS** [comment] 2023-12-14 17:46
Yes, sorry, duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4470

**Comment by suchithm** [comment] 2024-01-09 11:32
@bgavrilMS Looks like this issue is not a duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4470.  
`WithPrompt(Prompt.ForceLogin)` provides workaround for MSAL. Same option doent work for B2C.

**Comment by akozmic** [comment] 2024-07-08 18:51
@suchithm  do you by chance know why the "Same option does work for B2C"?

I'm using Azure AD B2C as the IDP and using MSAL in dotnet Maui and it seems like with the Embedded Web View, passing `.WithPrompt(Prompt.ForceLogin)` has no effect.  If the user has an active session in B2C, it bounces right back, even though we've confirmed that the `prompt=login` parameter is properly passed across.

Is this a B2C bug? I've been unable to reproduce it during login to our web app (which uses Authorization Code Flow), so I'm wondering if its a B2C bug with PKCE.  That's the only discernible difference I can see.

Any thoughts you'd have would be most appreciated.

**Comment by ahmedhasanmotiwala** [comment] 2025-05-19 22:01
> [@suchithm](https://github.com/suchithm) do you by chance know why the "Same option doesn't work for B2C"?
> 
> I'm using Azure AD B2C as the IDP and using MSAL in dotnet Maui and it seems like with the Embedded Web View, passing `.WithPrompt(Prompt.ForceLogin)` has no effect. If the user has an active session in B2C, it bounces right back, even though we've confirmed that the `prompt=login` parameter is properly passed across.
> 
> Is this a B2C bug? I've been unable to reproduce it during login to our web app (which uses Authorization Code Flow), so I'm wondering if its a B2C bug with PKCE. That's the only discernible difference I can see.
> 
> Any thoughts you have would be most appreciated.

======================================================================

I tried this, it works for me

#if IOS
using Foundation;
using WebKit;
#endif



#if ANDROID
Android.Webkit.CookieManager.Instance.RemoveAllCookies(null);
Android.Webkit.CookieManager.Instance.Flush();
#elif IOS
var dataTypes = WKWebsiteDataStore.AllWebsiteDataTypes;

WKWebsiteDataStore.DefaultDataStore.FetchDataRecordsOfTypes(dataTypes, (records) =>
{
    var recordList = new List<WKWebsiteDataRecord>();

    // Convert NSArray to List<WKWebsiteDataRecord>
    for (nuint i = 0; i < records.Count; i++)
    {
        var record = records.GetItem<WKWebsiteDataRecord>(i);
        if (record != null)
            recordList.Add(record);
    }

    if (recordList.Any())
    {
        WKWebsiteDataStore.DefaultDataStore.RemoveDataOfTypes(
            dataTypes,
            recordList.ToArray(),
            () => Console.WriteLine("✅ iOS cookies and WebView data cleared.")
        );
    }
    else
    {
        Console.WriteLine("ℹ️ No WebKit data found to clear.");
    }
});
#endif
