### ISSUE TITLE
AcquireTokenSilentAsync Is not working as expected after updating MSAL 2.0.0-preview (Xamarin Forms with B2C)

### ISSUE THREAD

**Issue by crazynitha** [AzureAD/microsoft-authentication-library-for-dotnet#606] opened 2018-08-30 10:08 UTC
I tried to update the below line of code based on the new documentation.

```
var authResult = await _authenticationClient.AcquireTokenSilentAsync(
                   Settings.Scopes,
                   _authenticationClient.GetUser(AuthenticatedUser.Id),
                   Settings.B2CAuthority(Settings.DefaultB2CTenant, Settings.DefaultB2CPolicy),
                   true);
```
This is all about calling AcquireTokenSilentAsync() but I am getting the response of GetAccountsAsync() always null.

```
IEnumerable<IAccount> accounts = await _authenticationClient.GetAccountsAsync();
IAccount firstAccount = accounts.FirstOrDefault();
var authResult = await _authenticationClient.AcquireTokenSilentAsync(
                    Settings.Scopes,
                    accounts,
                    Settings.B2CAuthority(Settings.DefaultB2CTenant, Settings.DefaultB2CPolicy),
                    true);
```

**Comment by jmprieur** [comment] 2018-08-30 10:38
Thanks for reporting @crazynitha 
This is actually a duplicate of #604. Closing it as such. I also renamed the title slightly as this is a B2C issue

See also my answer in [active-directory-xamarin-native-v2 issue #38](https://github.com/Azure-Samples/active-directory-xamarin-native-v2/issues/38)

**Closed** 2018-08-30 10:39 UTC
Labels: duplicate
