### ISSUE TITLE
[Bug] XCode + GCM fails to read tokens from the cache

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#4117] opened 2023-05-05 11:10 UTC
Issue reported by some folks in Office. 

Folks internal to Microsoft have started seeing many prompts for auth from GCM. It is either an XCode or a MacOS change. The root cause seems to be the cache extension's interaction with KeyChain, which now fails.

The same does **not** happen when Git / GCM is invoked from the terminal, so folks are not entirely blocked, but this is unpleasent.

Assumption is that MacOS made some changes to enforce app identity for non-terminal apps. XCode is a proper Mac app, with bundle id etc. But GCM / MSAL use KeyChain APIs that are agnostic of app identity. 

A solution would be to add support for new KeyChain APIs, however this is not trivial: 

- what bundle Id would GCM use? 
- will GCM be able to read from the old cache? If not, SSO will be broken.
- will GCM be able to write to both caches?

**Comment by bgavrilMS** [comment] 2023-05-05 11:10
CC @mjcheetham

**Comment by bgavrilMS** [comment] 2023-05-15 12:05
This is not a WAM issue, Sam. It's to do with MSAL reading / writing data from the KeyChain. 

Issue seems to lie with Apple, who've made a change to either OS or XCode and prevents GCM / MSAL from reading the KeyChain. GCM folks are investingating with Apple.

**Comment by mjcheetham** [comment] 2023-09-06 15:38
@bgavrilMS this can be closed. The issue was root caused to some issue in Xcode 14.3, which is fixed in Xcode 15 betas. There are no changes needed in MSAL.

**Closed** 2023-09-07 04:17 UTC
Labels: bug, P2, external, cache-extensions, scenario:Desktop, public_client
