### ISSUE TITLE
[Bug] Cannot use Custom Tabs with Android 29+

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#2418] opened 2021-02-17 18:44 UTC
**Logs and Network traces**
Without logs or traces, it is unlikely that the team can investigate your issue. Capturing logs and network traces is described at https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging

**Which Version of MSAL are you using ?**
MSAL 4.24.0 +

**Platform**
xamarin android

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App 
    * [ ] Authorization code
    * [ ] OBO
* Daemon App 
    * [ ] Service to Service calls

**Repro**
Ensure the app is targeting android 10 (API 29) in the project properties.
Ensure that the system browser is enabled in MSAL.NET (Should be on by default)
Try to acquire a token interactively

**Expected behavior**
MSAL should launch the custom tab browser for authentication

**Actual behavior**
The system browser is launched without custom tabs.

**Possible Solution**
Try modifying the browser tab packages that are used in the interactive auth.
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/d451b16a9ae66742047b0ba37fb74d875a69056d/src/client/Microsoft.Identity.Client/Platforms/Android/SystemWebview/AuthenticationActivity.cs#L37-L45

**Comment by jmprieur** [comment] 2021-02-17 21:28
@trwalke. is it a duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2139 ?

**Comment by bgavrilMS** [comment] 2021-02-25 11:10
Closing as duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2139

**Comment by trwalke** [comment] 2021-02-26 16:59
Not a duplicate. this is the second issue identified in https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2139

**Comment by trwalke** [comment] 2021-03-26 17:45
@tipa it appears that there is a new way to implement the custom tabs in android 29. Ive been playing around with it to see if there is a way to adapt our code with it to make it work. I managed to get the custom tab to show up but the responses do not return to our code at the moment. I was also able to get the legacy support for custom tabs to work so I think it will be ok for us to use that for now.

**Comment by tipa** [comment] 2021-03-26 17:51
Not sure what you mean with legacy support buty ou can test the file attached if you need it. I am using it successfully to authenticate to many services, like Dropbox, Google Drive etc.
[AuthorizationManagementActivity.zip](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/6213490/AuthorizationManagementActivity.zip)

You can start the auth flow with `AuthorizationManagementActivity.AuthenticateAsync(url);` and the `WebAuthenticationCallbackActivity` will be called if the scheme is set correctly.

**Comment by trwalke** [comment] 2021-03-26 18:05
@tipa I was referring to using 
"android.support.customtabs.action.CustomTabsService"

as opposed to 
"androidx.browser.customtabs.action.CustomTabsService".

which would require us to use the custom tab intent here
https://developer.android.com/reference/androidx/browser/customtabs/CustomTabsIntent

this appears to be the way to implement customtabs in android 29+

Perhaps legacy is the wrong word.

**Comment by tipa** [comment] 2021-03-30 08:33
Yay, looks fixed with 4.29.0 - thanks!

**Closed** 2021-03-30 09:00 UTC
Labels: Fixed, P2, regression?, scenario:Mobile-Android

**Comment by bgavrilMS** [comment] 2021-03-30 09:12
Thank you for patience @tipa !
