### ISSUE TITLE
Access cached IdToken offline

### ISSUE THREAD

**Issue by Kritarie** [AzureAD/microsoft-authentication-library-for-dotnet#717] opened 2018-12-10 23:26 UTC
**Which Version of ADAL are you using ?**
Note that to get help, you need to run the latest preview or non-preview version
For MSAL, please log issues to https://github.com/AzureAD/microsoft-authentication-library-for-dotnet
MSAL 2.5.0-preview

**Which platform has the issue?**
Verified on Xamarin.Android, but it does not seem platform specific

**What authentication flow has the issue?**
* Desktop / Mobile
    * [X] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

**Repro**
I'm working on supporting offline functionality for our Android and iOS app, and one of the features requires that we display the user's name in the UI. Currently we are getting the user's name from the deserialized JWT from the `IdToken` property of `AuthenticationResult`. Unfortunately, when we call `AcquireTokenSilentAsync` to get our `AuthenticationResult` while offline, an exception is thrown from `AadInstanceDiscovery` fetching metadata from the network. We are able to successfully call `GetAccountsAsync` without network connectivity, but the `IAccount` returned doesn't provide us with the info we need.

**Possible Solution**
Perhaps the cached JWT could be exposed on `IAccount` so that we could read from it without requiring any network calls?

**Comment by jmprieur** [comment] 2018-12-11 10:59
@Kritarie : isn't the `Username` property of `AuthenticationResult.Account` enough ? (See  [IAccount](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Acquiring-Tokens#iaccount-msal-2x))

Also we'd like to understand better the offline scenarios, which we had not optimized for. What do you do offline?

**Comment by Surfrat** [comment] 2018-12-11 13:37
This looks like a duplicate of my [issue](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/630)....

**Comment by Kritarie** [comment] 2018-12-11 14:24
@jmprieur the `Username` property in our case is the user's email. During sign up we also have the user enter their given name and family name, which is delivered back to us via the `IdToken`. Ideally we would like to provide most or all of the same functionality offline as we do online (assuming some prior online connectivity for caching). Right now we want to access the user's given name in order to display some UI on the home page such as "Welcome, {name}.". We also have an account page where we display the user's account information, including given name, family name, and email.

@Surfrat I saw your issue, but I think they're a bit different. We are not having any issues calling `GetAccountsAsync` offline, because it does not make any network requests. However, calling `AcquireTokenSilentAsync` calls into the `AadInstanceDiscovery` service to fetch metadata, which causes an exception to be thrown when offline. This is a problem because `AcquireTokenSilentAsync` is currently the only way to retrieve an `AuthenticationResult`, which is the only way to read the `IdToken`, which is the only way (that I can tell) to get the user's given and family name.

**Comment by Surfrat** [comment] 2018-12-11 15:51
My issue is the same. This is in my post "I think we are half way there. GetAccountsAsync() now returns the account while offline but the next line (AcquireTokenSilentAsync) causes an exception".

**Comment by shoatman** [comment] 2018-12-11 16:17
Assuming this is related....There's working happening in MSAL to cache Azure AD cloud instance discovery document.  

[https://login.microsoftonline.com/common/discovery/instance?authorization_endpoint=https://login.microsoftonline.com/common/oauth2/v2.0/authorize&api-version=1.1](https://login.microsoftonline.com/common/discovery/instance?authorization_endpoint=https://login.microsoftonline.com/common/oauth2/v2.0/authorize&api-version=1.1)

Ignoring the planned work for a moment.

In this case.... the scenario doesn't actually need to make a subsequent call using an access token so the fact that network call failed to retrieve the instance metadata is not important.  They simply want to retrieve the id_token that's currently only available via AuthenticationResult.  The problem is without the cached azure ad cloud metadata.  The code doesn't know which authority alias the tokens are stored under.  So the silent request fails.

For this scenario we can investigate the feasibility of associating the id_token with the account object in the OM.  In that way the authority would not matter since currently we retrieve accounts for all authorities...at least I think that's right.  I think this is likely worth doing anyway regardless of the pending work on caching.  

With that said id_tokens are are also credentials (have expiration etc...) so we'll need to give some thought to how developers will use these tokens.  Outside of this scenario where they just want to display it's contents.

**Comment by Mephisztoe** [comment] 2019-05-29 12:09
After calling AcquireTokenSilentAsync, I extract the idToken from the AuthenticationResult, but what's more important to me is the AccessToken which I encapsulate in a JObject to be passed to MobileServiceClient.LoginAsync as zumoPayload. This way I can make use of MSAL for easy authentication against AADB2C and MobileServiceClient for easy working against Azure App Services Tables.

However, since AcquireTokenSilentAsync throws an exception when the client is offline, this scenario does not work.

**Comment by jmprieur** [comment] 2019-10-24 11:15
@Mephisztoe : we've improved the offline scenario. do you still see this issue?
Proposing to close, but feel free to reopen if you still see it

**Closed by jmprieur** 2019-10-24 11:15 UTC
Labels: enhancement, question
