### ISSUE TITLE
[Engineering Task] Validate all tests are running for all the test frameworks

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#4233] opened 2023-07-12 17:06 UTC
- [ ] make sure datarows have datatestmethod 
- [ ] verify test logs for skipped tests and if the test has coverage in a different framework
- [ ] verify if test logs are slowing down builds and turn off logs where not required

**Comment by gladjohn** [comment] 2023-08-01 16:47
This will be done once we have OneBranch running tests

**Comment by bgavrilMS** [comment] 2023-09-06 17:27
If `datarows` doesn't have `datatestmethod` does it mean the test won't run?

**Comment by gladjohn** [comment] 2023-09-06 20:57
tests should have at least `[DataTestMethod]` or `[TestMethod]`. If you take `WithTenantIdAtRequestLevel_Noop_AdfsGeneric` for example, it has none.

**Comment by pmaytak** [comment] 2023-09-07 04:10
Partial dupe of this: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4052? I wrote some thoughts there on how to make sure we run tests only for unique code paths. Most of the tests should run either on netstandard or net6.

**Comment by bgavrilMS** [comment] 2024-05-08 15:04
Not sure this is actionable.

**Closed by bgavrilMS** 2024-05-08 15:04 UTC
Labels: Feature Request, internal, Engineering Excellence
