### ISSUE TITLE
[Testing Request] Hybrid WAM and Not-WAM account access token requests.

### ISSUE THREAD

**Issue by JPWilli** [AzureAD/microsoft-authentication-library-for-dotnet#2979] opened 2021-10-26 16:05 UTC
**Is your feature request related to a problem? Please describe.**
One of the scenarios we're looking at is when a user signs into our product without using WAM, and then later we inspect the msal cache for accounts and request access tokens to ARM for every account using WAM. In this scenario we're concerned that the WAM broker might ignore the refresh token in the cache and go to Windows, discover no account there that matches, and fail to get the access token that IS readily available.

**Describe the solution you'd like**
Ideally, WAM should fail, then fallback to MSAL, observe the valid refresh token there, and use that.

**Describe alternatives you've considered**
Failing the ideal solution, we'd be able to self-service this scenario if we knew which accounts were WAM backed, vs browser.

**Additional context**
This is still a hypothetical situation, which I haven't been able to produce. The request is to test this corner-case, and take action if a problem exists.

**Comment by bgavrilMS** [comment] 2022-09-29 12:36
Closing as duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3709

**Closed by bgavrilMS** 2022-09-29 12:36 UTC
Labels: enhancement, Feature Request, WAM
