### ISSUE TITLE
[Bug] Cache Miss on upgrade from .net MSAL 4.46.0 to 4.46.2

### ISSUE THREAD

**Issue by katariapankaj** [AzureAD/microsoft-authentication-library-for-dotnet#3815] opened 2022-11-21 09:43 UTC
**Logs and network traces**
Without logs or traces, it is unlikely that the team can investigate your issue. Capturing logs and network traces is described in [Logging wiki](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging).

We recently upgraded our Microsoft.Identity.Client from 4.46.0 to 4.46.2 and Microsoft.Identity.Web.TokenCache from 1.21.1 to 1.25.1. 
Post upgrade we see that caching is not being used by new library. This is causing our roles to hit AAD endpoint and get throttled.

Sample Error Trace:

Getting AuthenticationContext failed. Correlation id: '5dcfe234-3573-47cb-9269-928b0bbf535a. Will try 00:00:05 seconds. Retry attempt 1. | Exception: MSAL.Desktop.4.46.2.0.MsalServiceException: 
    ErrorCode: temporarily_unavailable
Microsoft.Identity.Client.MsalServiceException: AADSTS90055: The server has terminated the request due to excessive request rate. Please wait a few seconds and try again.
Trace ID: 269a2976-0c11-4dae-9328-062d91b96c00
Correlation ID: 5dcfe234-3573-47cb-9269-928b0bbf535a
Timestamp: 2022-11-18 07:28:12Z

**Which version of MSAL.NET are you using?**
 4.46.2

**Platform**
.NET Framework 4.6.2

**What authentication flow has the issue?**
* AAD base authentication from desktop server.

Other?

**Is this a new or existing app?**

Add any other context about the problem here, such as logs and screenshots, and even links to code.

**Comment by morgars** [comment] 2022-11-22 16:01
I have the same error.

**Comment by bgavrilMS** [comment] 2022-11-28 18:52
Does not reproduce with 4.48.x but we are still waiting for logs for 4.46.2 (@morgars - if you can share some logs, that would be great)

**Comment by morgars** [comment] 2022-11-29 14:34
I have upgraded to 4.48.x and now i can not reproduce the error. Seems to be fixed with the newer version.

**Comment by bgavrilMS** [comment] 2022-11-29 15:22
Thanks for confirming @morgars. Any chance you can get us verbose logs from 4.46.2 ? We are not able to repro locally. Feel free to email logs to me at - bogavril at microsoft .com

**Comment by morgars** [comment] 2022-11-29 17:31
Hello @bgavrilMS. I downgraded to 4.46.2 to try to get logs for you, but now it seems to work with the 4.46.2. I'm confused, maybe it was some other local problem on the machine or some Assembly mismatch.

**Comment by bgavrilMS** [comment] 2022-11-30 14:28
Thanks for trying @morgars , we are also unable to repro the issue ...

**Closed** 2022-12-12 18:46 UTC
Labels: P2, Investigate
