### ISSUE TITLE
[Bug] JAVA/Python Cache integration tests are failing.

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#1499] opened 2019-11-13 01:45 UTC
Java/Python cache tests have been failing with the following errors:

>AADSTS50057: User account is disabled.

>ResultsFilePath does not exist: >C:\Users\VssAdministrator\AppData\Local\Temp\adalcachecompattestdata\msal_java_results.json

>Assert.AreEqual failed. Expected:<idlab@msidlab4.onmicrosoft.com>. Actual:<(null)>

[Link to build](https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=426633&view=ms.vss-test-web.build-test-results-tab&runId=1144168&resultId=100001&paneView=debug)

The lab team has stated that they have not made any changes recently to cause this to happen. All lab accounts are enabled and that can be verified by simply signing to office.com with the lab account.

This will require some investigation. Perhaps there was an update to the azure devops hosted agents that changed the Python, JAVA and Maven installation settings

**Comment by bgavrilMS** [comment] 2019-11-13 11:00
It seems to me that all cache tests are failing. The AADSTS error suggest the issue is with app registration. My 2c is that the the cache tests do not use the latest lab api and hardcode a bunch of clientIDs. I'll take a look.

**Comment by bgavrilMS** [comment] 2019-11-13 11:17
There's a problem with the lab account 

![image](https://user-images.githubusercontent.com/12273384/68759224-31e74800-0607-11ea-9f6e-26eb5054cafd.png)

**Comment by jmprieur** [comment] 2019-11-22 16:04
Fixed in MSAL.NET 4.7.1. released today

**Closed by jmprieur** 2019-11-22 16:04 UTC
Labels: Fixed, P2, bug, internal
