### ISSUE TITLE
[Feature Request]     Add Shared Device functionality that is in MSAL for Java/Android to MSAL for .NET

### ISSUE THREAD

**Issue by LoveJL-5600** [AzureAD/microsoft-authentication-library-for-dotnet#4470] opened 2023-12-14 13:48 UTC
### MSAL client type

Public

### Problem Statement

The SingleAccountPublicClientApplication and MultipleAccountPublicClientApplication subclasses of PublicClientApplication are not available in MSAL for .NET libraries.  

These subclasses are available in MSAL for Java/Android:
[https://learn.microsoft.com/en-us/java/api/com.microsoft.identity.client.singleaccountpublicclientapplication?view=azure-java-stable](https://urldefense.us/v2/url?u=https-3A__learn.microsoft.com_en-2Dus_java_api_com.microsoft.identity.client.singleaccountpublicclientapplication-3Fview-3Dazure-2Djava-2Dstable&d=DwQFAg&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=q4Gkg1MxI1SjeysxDch-Ng&m=ZB1MoJZQeNax4KmKog-jwY790jg37-f3hHOOd8vUxcRQmW7n1ARM4HPPd__Qi_ro&s=mU-ciUqO8T_2UnUFHuAQYK7CuDm-DUwCADW0AJqfRUo&e=)
[https://learn.microsoft.com/en-us/java/api/com.microsoft.identity.client.multipleaccountpublicclientapplication?view=azure-java-stable](https://urldefense.us/v2/url?u=https-3A__learn.microsoft.com_en-2Dus_java_api_com.microsoft.identity.client.multipleaccountpublicclientapplication-3Fview-3Dazure-2Djava-2Dstable&d=DwQFAg&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=q4Gkg1MxI1SjeysxDch-Ng&m=ZB1MoJZQeNax4KmKog-jwY790jg37-f3hHOOd8vUxcRQmW7n1ARM4HPPd__Qi_ro&s=O4k_qxuWn11Kbh3gQYnDpPnax5td3Vqjn3UMFSmAIFk&e=)

These are apparently meant to work with Android Shared Device mode as per MS docs: 
[https://learn.microsoft.com/en-us/entra/identity-platform/msal-android-shared-devices](https://urldefense.us/v2/url?u=https-3A__learn.microsoft.com_en-2Dus_entra_identity-2Dplatform_msal-2Dandroid-2Dshared-2Ddevices&d=DwQFAg&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=q4Gkg1MxI1SjeysxDch-Ng&m=ZB1MoJZQeNax4KmKog-jwY790jg37-f3hHOOd8vUxcRQmW7n1ARM4HPPd__Qi_ro&s=lkniuUJrX9Bbh-y7r7QRgyxyUZvYnLTm4waCDv1HewU&e=)
[https://learn.microsoft.com/en-us/entra/identity-platform/single-multi-account](https://urldefense.us/v2/url?u=https-3A__learn.microsoft.com_en-2Dus_entra_identity-2Dplatform_single-2Dmulti-2Daccount&d=DwQFAg&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=q4Gkg1MxI1SjeysxDch-Ng&m=ZB1MoJZQeNax4KmKog-jwY790jg37-f3hHOOd8vUxcRQmW7n1ARM4HPPd__Qi_ro&s=aYrNM75Btomncr-TaiGuWP_-mgc5z8R0ewkejRowPQE&e=)

We feel they should be available in MSAL for .NET since .NET can and does target Android: [https://dotnet.microsoft.com/en-us/apps/mobile](https://urldefense.us/v2/url?u=https-3A__dotnet.microsoft.com_en-2Dus_apps_mobile&d=DwQFAg&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=q4Gkg1MxI1SjeysxDch-Ng&m=ZB1MoJZQeNax4KmKog-jwY790jg37-f3hHOOd8vUxcRQmW7n1ARM4HPPd__Qi_ro&s=sQIJYDgcKHtOzI9xb1akITJk1dQMCkMBcmhq99IJrhE&e=)

We are developing a .NET MAUI app for Android where we need to target Android devices that are in shared device mode and need to use MultipleAccountPublicClientApplication so that multiple users can log in. We have made this work using a native Java Android app using the MSAL for Java/Android SDK and MultipleAccountPublicClientApplication as a POC, but need to have this working in a .NET MAUI app as that is our development platform.

### Proposed solution

Make the functionality and classes that are available in MSAL for Java/Android in MSAL for .NET as well.

### Alternatives

As a workaround, we are attempting to bind the MSAL for Java library to C# so it can be called from .NET MAUI for Android code. This work is not yet complete.

**Comment by bgavrilMS** [comment] 2023-12-14 14:45
We have tried to alternative you proposed and found it very difficult about 2 years ago :( - the tooling didn't work well with the structure of MSAL Android, because the SDK is actually made up of 2 libraries. 

We do not have an ETA for adding new features to MSAL .NET mobile functionality.

**Comment by LoveJL-5600** [comment] 2023-12-14 15:45
It is very disappointing to get this kind of response within minutes of submitting the request especially since we have made a significant commitment to Microsoft by implementing Azure for our infrastructure.

**Comment by bgavrilMS** [comment] 2023-12-14 15:54
Please do escalate so as to help the team prioritize better. 

Currently, "Shared Device Mode" is only supported in MSAL Android (Java) and MSAL iOS (ObjC), and this is the best path forward for implementing the scenarios today.

**Comment by localden** [comment] 2023-12-14 17:28
Thank you for the feedback, @LoveJL-5600 - while I understand that it's disappointing to hear that this feature is not prioritized, our resources are currently limited with a number of high priority projects within the MSAL ecosystem. This feedback is definitely helpful for us to prioritize future work.

**Comment by LoveJL-5600** [comment] 2023-12-14 19:23
I have been trying to get this issue resolved since December 6, 2021.  28700388, 2201180040009412, 2201070040007323, 2112030040006644, 2201180040009412, 2204060040007549.  Is this truly what we should expect when we have Microsoft Premier Support?

**Comment by localden** [comment] 2023-12-14 19:30
This is actually a duplicate request - we also have been tracking this feature with #2910 and #3795. @LoveJL-5600 - I understand the frustration, but also to set expectations, support doesn't necessarily translate to feature implementation. Our team currently doesn't have the bandwidth to address this particular gap.

Our current recommendation, and has been for some time for folks who want to use Shared Device Mode, is to use native MSALs for the mobile platforms they are targeting ([Android](https://github.com/AzureAD/microsoft-authentication-library-for-android) and [Objective-C](https://github.com/AzureAD/microsoft-authentication-library-for-objc)), which both have the right level of support for this functionality.

**Comment by LoveJL-5600** [comment] 2023-12-14 19:51
This Microsoft Cloud Skills Challange still as of 12/14/2023 doesn't mention this limitation or recommend using native MSALs and the dates at the top left seem to indicate that it is applicable from Nov 15, 2023 - Jan 15, 2024.. https://learn.microsoft.com/en-us/entra/identity-platform/msal-net-use-brokers-with-xamarin-apps#brokered-authentication-for-android. 
![Capture](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/146112809/1391dfb5-8e23-42ec-b1aa-78bf1111f7f9)

**Comment by localden** [comment] 2023-12-14 20:49
@LoveJL-5600 can you please clarify what is the relation of Cloud Skills Challenge above to the request for support for Shared Device Mode in MSAL.NET with MAUI? Brokered authentication is a separate aspect of the library.

**Comment by LoveJL-5600** [comment] 2023-12-14 20:59
The Microsoft Identity Client NuGet package is used for both Xamarin and MAUI MSAL. https://learn.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/quickstarts/maui/authentication?pivots=vs2022-windows

**Comment by localden** [comment] 2023-12-14 21:07
Indeed, but not all MSAL packages are equal in functionality. Shared Device Mode is not supported in MSAL.NET scenarios for Xamarin/MAUI, and if there is documentation anywhere stating that it is, we need to update that.

**Comment by LoveJL-5600** [comment] 2023-12-14 21:10
It was demonstrated at the 2022 .NET Conf https://www.youtube.com/watch?v=QO8XKsJ51Gc

**Comment by localden** [comment] 2023-12-14 21:44
We do support MAUI. We do not support Shared Device Mode in the library.

**Comment by localden** [comment] 2024-01-17 02:13
Closing this as duplicate of #2910. Please add any further comments in that issue!

**Closed by localden** 2024-01-17 02:13 UTC
Labels: scenario:Mobile-iOS, scenario:Mobile-Android, Feature Request, public-client
