### ISSUE TITLE
[Bug] WebView2 fails to load and WebBrowser does not change the title

### ISSUE THREAD

**Issue by mjcheetham** [AzureAD/microsoft-authentication-library-for-dotnet#2633] opened 2021-05-17 11:58 UTC
**Logs and Network traces**
N/A

**Which Version of MSAL are you using ?**
MSAL 4.31.0

**Platform**
net472

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive

**Is this a new or existing app?**
c. This is a new app or experiment

**Repro**

```csharp
using Microsoft.Identity.Client;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var clientId = "872cd9fa-d31f-45e0-9eab-6e460a02d1f1";
            var scopes = new[] { "User.Read" };

            var webViewOptions = new EmbeddedWebViewOptions
            {
                Title = "Hello, World!"
            };

            var pca = PublicClientApplicationBuilder.Create(clientId).Build();

            var result = await pca.AcquireTokenInteractive(scopes)
                .WithUseEmbeddedWebView(true)
                .WithEmbeddedWebViewOptions(webViewOptions)
                .ExecuteAsync();
        }
    }
}
```

**Expected behavior**
The embedded web view browser window appears with the title of "Hello, World!".

**Actual behavior**
The webpage title is shown (default).
![image](https://user-images.githubusercontent.com/5658207/118484724-775e6700-b70f-11eb-945d-592ce3489553.png)

**Possible Solution**
Unknown.

**Additional context/ Logs / Screenshots**
None.

**Comment by bgavrilMS** [comment] 2021-05-17 12:12
Works with WebView2 - see https://aka.ms/msal-net-webview2 but not with the old WebBrowser

**Comment by mjcheetham** [comment] 2021-05-17 12:25
Aha.. so after adding the `Microsoft.Identity.Client.Desktop` package, and adding `.WithDesktopFeatures()`, _and_ installing the **evergreen WebView2 Runtime** from [here (clicking "download" on the bootstrapper option)](https://developer.microsoft.com/en-us/microsoft-edge/webview2/)... I get this error:

![image](https://user-images.githubusercontent.com/5658207/118487547-bb9f3680-b712-11eb-807b-53a7646d6dd1.png)

Looks like the MSBuild SDK defaults to platform target x86..

Project file:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Identity.Client" Version="4.31.0" />
    <PackageReference Include="Microsoft.Identity.Client.Desktop" Version="4.31.0" />
  </ItemGroup>
</Project>
```

VS UI:
![image](https://user-images.githubusercontent.com/5658207/118487652-d96c9b80-b712-11eb-972f-7cb5182dd35e.png)

Note that with the evergreen bootstrapper link, I never got asked about which architecture (x86 or x64) to install.

Changing the .NET project target to `AnyCPU` from the VS project UI changes my project file like this (what a mess):
![image](https://user-images.githubusercontent.com/5658207/118487877-1042b180-b713-11eb-878b-24f034b7e3bd.png)

```diff
     <TargetFramework>net472</TargetFramework>
   </PropertyGroup>
+  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
+    <PlatformTarget>AnyCPU</PlatformTarget>
+  </PropertyGroup>
   <ItemGroup>
     <PackageReference Include="Microsoft.Identity.Client" Version="4.31.0" />
```

..then I get another sort of error!!!!

![image](https://user-images.githubusercontent.com/5658207/118488006-349e8e00-b713-11eb-9e66-bb45b8427dcf.png)


Only changing the platform target to match the running machine directly (`x64` in my case) does this work...
![image](https://user-images.githubusercontent.com/5658207/118488094-4bdd7b80-b713-11eb-93b3-11318528c2db.png)

```diff
     <TargetFramework>net472</TargetFramework>
   </PropertyGroup>
+  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
+    <PlatformTarget>x64</PlatformTarget>
+  </PropertyGroup>
   <ItemGroup>
     <PackageReference Include="Microsoft.Identity.Client" Version="4.31.0" />
```

![image](https://user-images.githubusercontent.com/5658207/118488182-631c6900-b713-11eb-9b6e-58510afc395c.png)

This experience is very poor.

**Comment by bgavrilMS** [comment] 2021-05-17 12:27
The loading is a bug.

**Comment by bgavrilMS** [comment] 2021-05-17 12:30
@trwalke @pmaytak - didn't you repro one of these loading exceptions as well? I don't remember if we contacted the WebView2 folks about it or not.

**Comment by pmaytak** [comment] 2021-05-17 22:09
@bgavrilMS @mjcheetham
DllNotFoundException is a bug on a WebView2 side. Our issue #2482 is tracking it. They describe a possible workaround [here](https://github.com/MicrosoftEdge/WebView2Feedback/issues/730#issuecomment-803132248) - the app's project file must have a `<PlatformTarget>` element. (Even if it's default `<PlatformTarget>AnyCPU</PlatformTarget>`). I think when I tried it, it didn't fix it. @mjcheetham seems like you added that element and it still didn't work?

BadImageFormatException, like you said, seems to be looking for a WebView2 platform that you don't have installed.

**Comment by bgavrilMS** [comment] 2021-05-18 10:40
Closing as duplicate of #2482

**Closed by bgavrilMS** 2021-05-18 10:40 UTC
Labels: GCM, P2, bug

**Comment by mjcheetham** [comment] 2021-05-18 13:34
> I think when I tried it, it didn't fix it. @mjcheetham seems like you added that element and it still didn't work?

@pmaytak, yes.
The only value for `<PlatformTarget/>` that worked for me (out of `unset`, `x86`, `x64`, or `AnyCPU`) was `x64` on my x64 system.

**Comment by pmaytak** [comment] 2021-05-19 07:25
@mjcheetham Thanks for clarifying. I'll add this to the wiki and add a descriptive message in MSAL.NET. Feel free to post your feedback in their (issue](https://github.com/MicrosoftEdge/WebView2Feedback/issues/730) too. I'll +1 it. :)
