### ISSUE TITLE
[Bug] Advertise OS on UWP

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2303] opened 2020-12-14 11:30 UTC
**Logs and Network traces**
Without logs or traces, it is unlikely that the team can investigate your issue. Capturing logs and network traces is described at https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging

**Which Version of MSAL are you using ?**
4.24

**Platform**
UWP

MSAL sends a bunch of headers related to ESTS, one of them being the OS. On UWP, MSAL doesn't send this because it is difficult to find the OS. We should at least send "Windows 10" but see this https://stackoverflow.com/questions/45480191/how-to-check-the-windows-10-os-version-in-an-uwp-app-so-as-to-eliminate-wack-tes issue for ideas on how to get the OS.

ESTS uses this field for some logic (e.g. do not send PKAuth challenge on Win10) and it is also useful for support.

**Comment by jmprieur** [comment] 2020-12-14 18:57
@bgavrilMS : is this also related to this issue?
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1824

**Comment by bgavrilMS** [comment] 2020-12-15 12:16
Yes, I think so. They can be merged.

**Comment by jmprieur** [comment] 2020-12-15 13:49
Closing a duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1824

**Closed by jmprieur** 2020-12-15 13:49 UTC
Labels: P2, Supportability, bug, duplicate, good first issue
