### ISSUE TITLE
[Bug] custom host redirect uri is not working for ConfidentialClientApplicationBuilder

### ISSUE THREAD

**Issue by flytiny** [AzureAD/microsoft-authentication-library-for-dotnet#2376] opened 2021-02-02 06:24 UTC
**Logs and Network traces**
Without logs or traces, it is unlikely that the team can investigate your issue. Capturing logs and network traces is described at https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging

**Which Version of MSAL are you using ?**
Microsoft.Identity.Client 4.24.0

**Platform**

netcore

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App 
    * [x] Authorization code
    * [ ] OBO
* Daemon App 
    * [ ] Service to Service calls

Other? - please describe;

We deploy our service to Azure app service, and we config an Azure Front Door with a custom cname.
Currently we only want user to access our cname not Azure Front Door uri or ASE uri.

So we config the ConfidentialClientApplicationBuilder reply uri with our cname uri not ASE uri, but the request to AAD login page will always be configed with the ASE redirect uri.

**Is this a new or existing app?**

It's a new app and we just deploy it to Azure app service.

**Repro**

```csharp
string redirectUri = "https://****.microsoft.com/signin-oidc";

var builder = ConfidentialClientApplicationBuilder
  .Create(this.configuration[IWConstants.ClientId])
  .WithClientName(Service)
  .WithClientVersion(version)
  .WithAuthority(uri, true)
  .WithLogging(this.LogCallback)
  .WithTenantId(tenantId)
  .WithCertificate(appCert)
  .WithRedirectUri(redirectUri);
```

**Expected behavior**
A clear and concise description of what you expected to happen (or code).

The redirect uri shoule be "https://****.microsoft.com/signin-oidc" in my code.

**Actual behavior**
A clear and concise description of what happens, e.g. exception is thrown, UI freezes  

![image](https://user-images.githubusercontent.com/6790396/106559300-2eb7df00-6560-11eb-84bf-e50c922c4e26.png)
The redirect uri is still ASE uri, not the cname redirectUri in my code.

**Possible Solution**

Currentlly I can only modify OpenIdConnectEvents RedirectToIdentityProvider function to change the redirect uri. But it's definitely a bad solution.
```csharp
string redirectUri = "https://****.microsoft.com/signin-oidc";
context.ProtocolMessage.RedirectUri = redirectUri;
```

**Additional context/ Logs / Screenshots**
Add any other context about the problem here, such as logs and screebshots.

**Comment by jmprieur** [comment] 2021-02-02 09:11
The redirect URI is never used by MSAL.NET in confidential client applications, except in [IConfidentialClientApplication.GetAuthorizationRequest](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.iconfidentialclientapplication.getauthorizationrequesturl?view=azure-dotnet). Indeed, ASP.NET Core sets the redirect URI where to get the auth code back. See details below.

Proposing to close this issue as a duplicate of https://github.com/AzureAD/microsoft-identity-web/issues/918, where I've already started asking you questions to narrow down the issue.

### About the auth code grant, and the redirect URI
In ASP.NET [Core] web apps, the ASP.NET Core middleware requests the auth code when you sign-in users (first leg of the [Auth Code grant](https://docs.microsoft.com/azure/active-directory/develop/v2-oauth2-auth-code-flow)), and this is the part that sets the redirect URI.  Then MSAL.NET is involved only for the second leg of the Auth Code Flow: the redemption of the code.
This means the redirect URI is never used by MSAL.NET in confidential client applications. ASP.NET Core does use it to decide where to get the auth code back.

**Comment by bgavrilMS** [comment] 2021-02-02 09:43
Yes, please continue to follow this up via  AzureAD/microsoft-identity-web#918

**Closed by bgavrilMS** 2021-02-02 09:43 UTC
Labels: duplicate, external
