### ISSUE TITLE
B2C login with federated identity is broken in 4.33

### ISSUE THREAD

**Issue by HWouters** [AzureAD/microsoft-authentication-library-for-dotnet#2749] opened 2021-07-07 09:08 UTC
**Logs and network traces**
Since version 4.33.0 I can not login anymore with federated identity in B2C. Login with username password is still working. The following errors occurs:
AADB2C90090: The provided JWE is not a valid 5 segment token. Correlation ID: b0e306ce-96f0-4c1f-a9a8-2dc0fc5b6dc2
or
AADB2C90090: The provided JWE contains a field that is not base64 compliant.
Correlation ID: 41e39615-4c52-4dea-939c-0e5e308fd24e
or
AADB2C90085: The service has encountered an internal error. Please reauthenticate and try again.
Correlation ID: e4251fe0-c946-4d68-b008-fd3e5a74748b

**Which version of MSAL.NET are you using?**
MSAL.NET 4.33.0, it works in 4.32.1

**Platform**
.net framework 4.7 windows forms application

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

**Is this a new or existing app?**
The app is in production, I haven't upgraded MSAL, but started seeing this issue.

**Repro**

```csharp
  app = PublicClientApplicationBuilder.Create(ClientId).WithParentActivityOrWindow(() => owner).WithB2CAuthority(SignInAuthority).WithDefaultRedirectUri().Build();

await app.AcquireTokenInteractive(scopes).ExecuteAsync();
```

**Expected behavior**
Can login with username/password and federated identities

**Actual behavior**
It throws MsalException in case of login with federated id.

**Comment by HWouters** [comment] 2021-07-07 09:25
I now think it has nothing to do with federated id. I think it has to do with the token size, if I remove claims it works. 
However, it's a regression issue, because in 4.32 it works without removing claims.

**Comment by jmprieur** [comment] 2021-07-07 09:58
Probably a duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2607
cc: @jennyf19 FYI

**Comment by pmaytak** [comment] 2021-07-13 05:15
Hi @HWouters 
Please see my investigation in https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2743#issuecomment-877583645
Could you try some of these workarounds?
- Use default system browser instead of the embedded ones [System browser wiki](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/System-Browser-on-.Net-Core#how-to-use-the-system-browser-ie-the-default-browser-of-the-os)
- Use WebView2 embedded browser [WebView2 wiki](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/WebView2#changes-to-call-pattern)
  - WebView2 works better on .NET Core, so it would be better if you can upgrade.
  - Otherwise, if you run into WebView2 related issue in Net Fx, there's a workaround in https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2482#issuecomment-878619630

**Comment by bgavrilMS** [comment] 2021-07-15 13:36
@pmaytak - we should consider releasing as soon as you have a fix, at least a preview version for folks to try out.

**Comment by HWouters** [comment] 2021-07-15 18:19
@pmaytak that's a very nice investigation. I'm sure the default system browser will solve this issue. But I'm not keen on changing to different browser, we have many products out in the field and I'm afraid for potential other problems with the system browser. Especially if I see that port assigning is not supported in B2C... 
Question remains why it breaks in 4.33 and is working fine in 4.32.

**Comment by pmaytak** [comment] 2021-07-15 21:31
@HWouters Understandable. I'm working on a fix for the next release. Also, I was able to repro this on 4.32 and 4.30.

**Closed** 2021-07-20 10:54 UTC
Labels: B2C, bug, duplicate
