### ISSUE TITLE
[Bug] Blank login screen in embedded browser

### ISSUE THREAD

**Issue by hyc3z** [AzureAD/microsoft-authentication-library-for-dotnet#4186] opened 2023-03-28 03:39 UTC
**Which version of Microsoft Identity Abstractions for dotnet are you using?**
Note that to get help, you need to run the latest version. 

.NET SDK 6.0.310

MSAL:
```
<PackageReference Update="Microsoft.Identity.Client" Version="4.50.0"/>
```

**Repro**

```csharp
var interactiveResult = await clientApp.AcquireTokenInteractive(scopes)
               .WithAccount(account ?? accounts.FirstOrDefault())
               .WithPrompt(Prompt.SelectAccount)
               .ExecuteAsync();
```

**Expected behavior**

A login badge consisting user account info.

**Actual behavior**

The login badge is not showing user account info. However, it appears to be still clickable, like the accounts are still there listed:
![image](https://user-images.githubusercontent.com/31446768/228120773-87df706f-4b6b-4d61-8aa7-2785a8d5d265.png)

Not sure if this problem is related with the browser installed on the system
**Possible solution**

**Comment by pmaytak** [comment] 2023-06-22 23:02
Is this issue related: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4152?

MSAL doesn't control what the browser shows. We suggest using Windows broker: [https:\aka.ms\msal-net-wam](https:\aka.ms\msal-net-wam)

**Comment by localden** [comment] 2024-07-09 05:31
Closing this issue - it could've been an intermittent problem. I could not reproduce with any variations of the MSAL.NET interactive authentication flow.

**Closed by localden** 2024-07-09 05:31 UTC
Labels: external, scenario:Desktop, public-client
