### ISSUE TITLE
[Feature Request] Implement Single User Mode for Android

### ISSUE THREAD

**Issue by matt-goldman** [AzureAD/microsoft-authentication-library-for-dotnet#3795] opened 2022-11-09 00:50 UTC
**Is your feature request related to a problem? Please describe.**
I'm trying to build a shared-device mode application in .NET (Xamarin or MAUI), as per these docs:
https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-android-shared-devices
https://learn.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-shared-device-mode

However, `Microsoft.Identity.Client` does not expose the `ISingleAccountPublicClientApplication` interface that you get with the Android version of MSAL.

**Describe the solution you'd like**
I'd like the `ISingleAccountPublicClientApplication` interface to be available on Android in the .NET MSAL abstraction.

**Describe alternatives you've considered**
The alternative is to not use .NET and just build the app in Kotlin.

**Comment by bgavrilMS** [comment] 2022-11-11 13:54
Closign as duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2387

**Closed by bgavrilMS** 2022-11-11 13:54 UTC
Labels: enhancement, Feature Request
