### ISSUE TITLE
[Bug] How can I opt out of including GUI libraries in my console projects?

### ISSUE THREAD

**Issue by R2D221** [AzureAD/microsoft-authentication-library-for-dotnet#4523] opened 2024-01-17 22:48 UTC
### Library version used

4.56.0

### .NET version

.net8.0-windows

### Scenario

Other - please specify

### Is this a new or an existing app?

The app is in production, and I have upgraded to a new version of MSAL

### Issue description and reproduction steps

I'm using the SqlClient library provided by https://www.nuget.org/packages/Microsoft.Data.SqlClient/5.1.4 . Apparently MSAL has been a dependency for this new SqlClient despite me not explicitly using it to connect to my SQL Server instances.

Everything was fine and dandy until this new version, which now takes a dependency on the WebView2 component. My projects, despite being console apps, use the target framework `net8.0-windows` because I use a couple Windows-specific APIs. MSAL didn't cause me any troubles until SqlClient decided to upgrade to version 4.56.0 which brings the unwanted packages.

I reported this in the SqlClient's repo (https://github.com/dotnet/SqlClient/issues/2298), but apparently it was closed as not planned, bringing me here instead.

### Expected behavior

Not to include any GUI dependencies on console projects.

### Identity provider

Other

**Comment by pmaytak** [comment] 2024-01-18 02:29
@R2D221 This is a known behavior. We're looking into this. See the updates in #4468.

Closing this as a duplicate of #4468.

**Closed by pmaytak** 2024-01-18 02:29 UTC
Labels: untriaged, needs attention, Windows Forms dependency
