### ISSUE TITLE
Azure Devops / VSTS build fails with given error - Xamarin Forms

### ISSUE THREAD

**Issue by stezma** [AzureAD/microsoft-authentication-library-for-dotnet#752] opened 2019-01-02 13:12 UTC
**Version using  - Microsoft.Identity.Client Version 2.6.2**
After updating the package VSTS build fails with below error.

C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2053,5): Error MSB4018: The "LinkAssemblies" task failed unexpectedly.
Mono.Linker.MarkException: Error processing method: 'Microsoft.Identity.Json.Schema.JsonSchema Microsoft.Identity.Json.Schema.JsonSchemaBuilder::ResolveReferences(Microsoft.Identity.Json.Schema.JsonSchema)' in assembly: 'Microsoft.Identity.Client.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.String System.String::TrimStart(System.Char)
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
Process 'msbuild.exe' exited with code '1'.

Note
The local build works without any issue

**Comment by bgavrilMS** [comment] 2019-01-02 13:34
Hi @stezma  - where does the build take place? Are you using a VSTS hosted agent - which one (the VS 2017 one, the Mac one). Or an on-prem agent (is your VS up to date on it?)

**Comment by bgavrilMS** [comment] 2019-01-02 13:37
In any case, this looks like a duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/745 - see the solution there: 

Update VS to 15.9.4

**Comment by stezma** [comment] 2019-01-02 13:37
VS 2017 - Android. I haven't try in iOS

**Comment by bgavrilMS** [comment] 2019-01-02 13:38
Closi

**Closed by bgavrilMS** 2019-01-02 13:38 UTC
