### ISSUE TITLE
SDK is not compatible with AndroidX libraries. (Azure AD B2C) Xamarin Android 

### ISSUE THREAD

**Issue by stezma** [AzureAD/microsoft-authentication-library-for-dotnet#1963] opened 2020-07-29 09:01 UTC
SDK Version - 4.17.0

I am using all the latest Android X libraries in my Xamarin Forms application. And when I try to update update the **Microsoft.Identity.Client** SDK from **4.14.0** to **4.17.0.** I am getting the below errors during compilation.

_/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(3,3):_ Error _XA0121:_ Assembly 'Xamarin.Android.Support.CustomTabs' is using '[assembly: _Java.Interop.JavaLibraryReferenceAttribute]',_ which is no longer supported. Use a newer version of this NuGet package or _notify_ the library author. (XA0121) 

  _/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(3,3):_ Error _XA0121:_ Assembly 'Xamarin.Android.Support.CustomTabs' is using '[assembly: _Android.IncludeAndroidResourcesFromAttribute]',_ which is no longer supported. Use a newer version of this NuGet _package_ or notify the library author. (XA0121) 

Please fix this issue.

**Comment by bgavrilMS** [comment] 2020-07-29 09:05
We have added an Android X target framework recently, and I think those assemblies are not used at all. Can you confirm that your project in build against MonoAndroid 10 ?

**Comment by stezma** [comment] 2020-07-29 09:08
Yes!! I am using TargetFrameworkVersion 10

`  <TargetFrameworkVersion>v10.0</TargetFrameworkVersion>`

**Comment by bgavrilMS** [comment] 2020-07-29 09:10
So ... you are using an XForms app, built against MonoAndroid 10 and you are upgrading from MSAL 4.14 to 4.17? Is that the scenario? 

I'm marking this as external as the upgrade to Android X is a Xamarin experience, but let's try to get a repro first before involving them.

**Comment by stezma** [comment] 2020-07-29 09:13
@bgavrilMS . Yes you are right till 4.14 everything working fine even with my AndroidX libraries. Something happed after that.!

**Comment by talk2stephan** [comment] 2020-07-29 09:16
I believe i was also having the same issue and reverted back to old version.

**Comment by bgavrilMS** [comment] 2020-07-29 09:16
Can you confirm that you are using the latest Visual Studio and Xamarin SDKs?

**Comment by stezma** [comment] 2020-07-29 09:19
Yes I am using the latest version of Visual studio for Mac. Please find the below details taken from my VS.
[VS details.txt](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/4993892/VS.details.txt)

**Comment by bgavrilMS** [comment] 2020-07-29 09:19
I can offer a potential workaround to override the NuGet behavior of targetting Android 10 version of MSAL and relying on the older Android 9 version. 

```xml
<ItemGroup>
    <PackageReference Include="Microsoft.Identity.Client" GeneratePathProperty="true">
      <Version>4.17.0</Version>
    </PackageReference>
    <Reference Include="Microsoft.Identity.Client">
      <HintPath>$(PkgMicrosoft_IdentityModel_Tokens)\lib\MonoAndroid9.0\Microsoft.Identity.Client.dll</HintPath>
    </Reference>
</ItemGroup>
```

**Comment by stezma** [comment] 2020-07-29 09:27
This means latest version of SDK referencing  previous version of MonoAndroid (9.0) ?
So this is going to be a temporary fix right?

**Comment by talk2stephan** [comment] 2020-07-29 09:33
> I can offer a potential workaround to override the NuGet behavior of targetting Android 10 version of MSAL and relying on the older Android 9 version.
> 
> ```
> <ItemGroup>
>     <PackageReference Include="Microsoft.Identity.Client" GeneratePathProperty="true">
>       <Version>4.17.0</Version>
>     </PackageReference>
>     <Reference Include="Microsoft.Identity.Client">
>       <HintPath>$(PkgMicrosoft_IdentityModel_Tokens)\lib\MonoAndroid9.0\Microsoft.Identity.Client.dll</HintPath>
>     </Reference>
> </ItemGroup>
> ```
> 
> From a functional perspective there is no difference, it just uses different assemblies

I can confirm that this fix also not working. I am getting the same error. Not sure why. :(

**Comment by bgavrilMS** [comment] 2020-07-29 16:52
@talk2stephan  - I updated the workaround .. it should be using `$(PkgMicrosoft_Identity_Client)`, this is based on the technique described [here](https://duanenewman.net/blog/post/a-better-way-to-override-references-with-packagereference/) but it might not work. 

@stezma - I tried the following upgrade path and it all worked fine for me :( - could someone you try to isolate some repro steps ?


1. create new xforms project using VS 2019 (it uses MonoAndroid 9) 
2. add MSAL 4.14 reference (which has bidnings for Android 9 only) and add it in the code as well  ... builds OK
3. update xforms android project to Android 10 ... builds with warnings because of Xamarin.Essentials
3.1. Update Xamarin.Essentials ... no more warnings
4. Update to MSAL 4.17 (which has bindings for both Android 9 and Android 10)... builds ok.

The error message is pointing to `Xamarin.Android.Support.CustomTabs` but MSAL for Android 10 no longer uses this. So is it possible that NuGet didn't clean up the old references? Can you try to rebuild from a clean repo?

**Comment by stezma** [comment] 2020-08-03 08:17
Thanks for the support :)
I am travelling right now. I will try to create a sample app and share with you as soon as I can.

**Comment by bgavrilMS** [comment] 2020-08-13 16:49
Sure, please revive this thread if we can repro.

**Closed by bgavrilMS** 2020-08-13 16:49 UTC
Labels: Investigate, P1, external
