### ISSUE TITLE
Unhandled exception while calling Azure ADB2C

### ISSUE THREAD

**Issue by ImadElayyan** [AzureAD/microsoft-authentication-library-for-dotnet#657] opened 2018-10-25 05:46 UTC
---
name: Bug report
about: Create a report to help us improve

---

**Which Version of MSAL are you using ?**
MSAL 2.3.0 - preview

**Which platform has the issue?**
Xamarin android

**What authentication flow has the issue?**
* Mobile
    * [X ] Xamarin.Android

**What is the identity provider ?**
Azure AD B2C

If B2C, what social identity did you use?

Facebook
Microsoft
Username and password

**Repro**

```csharp
PublicClientApplication PCA = new PublicClientApplication(BL.Constants.ClientID, BL.Constants.Authority);

			PCA.RedirectUri = BL.Constants.RedirectUri;

			try
			{

				//IEnumerable<IAccount> accounts = await PCA.GetAccountsAsync();

				//var authenticationResult = await PCA.AcquireTokenAsync(BL.Constants.Scopes, new UIParent(this.Activity));

				var authenticationResult = await PCA.AcquireTokenAsync(
					BL.Constants.Scopes,
					"",
					UIBehavior.SelectAccount,
					"",
					null,
					BL.Constants.Authority,
					new UIParent(this.Activity));
			}
			
			catch (MsalException ex)
			{
				if (ex.Message != null && ex.Message.Contains("AADB2C90118"))
				{
					//await OnForgotPassword();
				}
				if (ex.ErrorCode != "authentication_canceled")
				{
					//await DisplayAlert("An error has occurred", "Exception message: " + ex.Message, "Dismiss");
				}
				else
				{
				}
			}
			catch (Exception ex)
			{
				string test = ex.Message;
				throw ex;
			}

namespace BL
{
	public class Constants
	{
		// Replace strings with your own values
		// Azure Active Directory B2C
		public static readonly string Tenant = "tenantname.onmicrosoft.com"; // Domain/resource name from AD B2C
		public static readonly string ClientID = "clientid"; // Application ID from AD B2C
		public static readonly string PolicySignUpSignIn = "B2C_1_SiUpIn"; // Policy name from AD B2C
		public static readonly string[] Scopes = { "" }; // Leave blank unless additional scopes have been added to AD B2C
		public static string AuthorityBase = $"https://login.microsoftonline.com/tfp/{Tenant}/"; // Doesn't require editing
		public static string Authority = $"{AuthorityBase}{PolicySignUpSignIn}"; // Doesn't require editing
		public static readonly string URLScheme = $"msal{ClientID}"; // Custom Redirect URI from AD B2C (without ://auth/)
		public static readonly string RedirectUri = $"{URLScheme}://auth"; // Doesn't require editing
	}
}
```

**Expected behavior**
The sign-in/up page should be displayed and the user should select the account to sign in.

**Actual behavior**
A security exception is thrown as below.
10-25 08:43:57.924 I/MonoDroid( 2850): UNHANDLED EXCEPTION:
10-25 08:43:57.936 I/MonoDroid( 2850): System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: Error: TrustFailure (A call to SSPI failed, see inner exception.) ---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> Mono.Btls.MonoBtlsException: Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
10-25 08:43:57.936 I/MonoDroid( 2850):   at /Users/builder/jenkins/workspace/xamarin-android-d15-8/xamarin-android/external/mono/external/boringssl/ssl/handshake_client.c:1132
10-25 08:43:57.936 I/MonoDroid( 2850):   at Mono.Btls.MonoBtlsContext.ProcessHandshake () [0x00038] in <b78695579ed9422b8bc80218eeda782c>:0 
10-25 08:43:57.936 I/MonoDroid( 2850):   at Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake (Mono.Net.Security.AsyncOperationStatus status) [0x0003e] in <b78695579ed9422b8bc80218eeda782c>:0 An unhandled exception occured.

**Possible Solution**

**Additional context/ Logs / Screenshots**
Add any other context about the problem here, such as logs and screebshots. Logging is described at https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging

**Comment by AlexSchuetz** [comment] 2018-10-26 13:36
This seams to be caused by missing CAs (either not present or not configured for the HttpClient).
I don't know how to lookup the CAs installed, nor do I know which HttpClient-implementation uses which CAs. I suspect the Mono-HttpClient uses its own CAs.

Here are jsut some advices on how I would try to dig into this:

1. Do you get an error or warning if you open the login url in one of the installed browsers?
2. Do you get an error or warning if you open the login url in a WebView?
3. Use [TLSv1.2](https://docs.microsoft.com/de-de/xamarin/cross-platform/app-fundamentals/transport-layer-security?tabs=windows) for the HttpClient, if you don't use it already. Even if it doesn't solve your problem old TLS versions are not regarded save.

**Comment by ImadElayyan** [comment] 2018-10-27 11:09
I have tried it from desktop application and it is working fine , the WebView is presented and I was able to login. It is only failing from Xamarin android. I have captured the traffic via WireShark and it is using TLS 1.2

**Comment by AlexSchuetz** [comment] 2018-10-29 15:16
@ImadElayyan I suppose you have configured "native TLSv1.2+" in your android project then.

Probably the CA you require is not installed or not used on your android device. Unfortunately I don't know how to check or how to fix this.

**Comment by jmprieur** [comment] 2018-10-30 09:59
@ImadElayyan. Please see https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/tls-issues for a full description.
Which version of Android are you using?

**Comment by jmprieur** [comment] 2018-11-12 08:18
@ImadElayyan : I'm assuming the previous conversation unblocked you. Closing this issue for now, but fee free to reopen

**Closed by jmprieur** 2018-11-12 08:18 UTC
Labels: documentation, external, scenario:B2C, scenario:Mobile-Android
