### ISSUE TITLE
WAM tokens do not work with OnBehalfOf flow

### ISSUE THREAD

**Issue by Jeff-Bridges** [AzureAD/microsoft-authentication-library-for-dotnet#2611] opened 2021-05-06 23:33 UTC
We're passing an ID token obtained using AcquireTokenInteractive in our Xamarin app to our back end where we obtain an OBO token.  This works for ID tokens obtained with or without the broker on Android and iOS, and without the broker on UWP.  However when we pass an ID token obtained using the broker on UWP we get the following exception when attempting to obtain the OBO token on the back end:

AADSTS240002: Input id_token cannot be used as 'urn:ietf:params:oauth:grant-type:jwt-bearer' grant.

Is this the expected behavour?  The difference between the ID tokens seems to be those obtained from the broker on UWP don't have the aio or uti claims.

We're using v4.30.1 of the library.

Thanks
Jeff

**Comment by jmprieur** [comment] 2021-05-07 07:37
@Jeff-Bridges : I don't think that OBO is supposed to work with an ID Token. Adding @hpsin to confirm.
- Why don't you pass-in an access-token? 
- Has the back-end the sample client ID as your front end?
- broker on UWP: do you mean WAM?

**Comment by Jeff-Bridges** [comment] 2021-05-08 10:42
Thanks for the responses.  In answer to your questions:

I've tried passing the access token when calling AcquireTokenOnBehalfOf, but get the following exception:

AADSTS50013: Assertion failed signature validation. [Reason - The provided signature value did not match the expected signature value.

The front and back end both use the same client ID.

When I say broker on UWP - I'm calling WithExperimentalFeatures and WithBroker when building the public client application.

As above I've tried passing the access token, but without success.  How can I request a v2 ID token instead of a v1 when calling AcquireTokenInteractive with the broker enabled on UWP?

Any help would be much appreciated.

Thanks
Jeff

**Comment by bgavrilMS** [comment] 2021-05-10 12:30
I think the windows broker (WithBroker) will fetch v1 tokens. I don't think there is way to make it fetch v2 tokens. @iulico-1 if he knows of any such way.

@Jeff-Bridges - could you pass-in access token instead of id token for OBO?

**Comment by Jeff-Bridges** [comment] 2021-05-12 23:57
@bgavrilMS I've tried passing the access token when calling AcquireTokenOnBehalfOf, but get the following exception:

AADSTS50013: Assertion failed signature validation. [Reason - The provided signature value did not match the expected signature value.

Any idea why that would be happening?

Thanks
Jeff

**Comment by bgavrilMS** [comment] 2022-12-22 14:10
This is a WAM limitation.

**Comment by bgavrilMS** [comment] 2022-12-22 15:06
Closing as duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3230

**Closed by bgavrilMS** 2022-12-22 15:06 UTC
Labels: external, Investigate, WAM
