### ISSUE TITLE
[Bug] Microsoft.Identity.Client.WwwAuthenticateParameters does not work for MS DataVerse service

### ISSUE THREAD

**Issue by rurafiko** [AzureAD/microsoft-authentication-library-for-dotnet#3112] opened 2022-01-14 16:40 UTC
**Which version of MSAL.NET are you using?**
MSAL.NET 4.40.0 -->

**Platform**
.NET 4.7.2

**Repro**

```csharp
// Bearer authorization_uri=https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/authorize, resource_id=https://org1e971638.crm4.dynamics.com/
var crm = await Microsoft.Identity.Client.WwwAuthenticateParameters.CreateFromResourceResponseAsync("https://org1e971638.crm4.dynamics.com/api/data/version").ConfigureAwait(false);
```

**Expected behavior**
WwwAuthenticateParameters crm should be filled with Authority/Resource/Claims

**Actual behavior**
WwwAuthenticateParameters crm does not contains any data.

**Possible solution**
Looks like the issue in WwwAuthenticateParameters.ExtractWwwAuthenticateParametersFromHeaders
```csharp
if (httpResponseHeaders.WwwAuthenticate.Any()) // this part return false, but actually WWW-Authenticate header exists.
```

**Comment by bgavrilMS** [comment] 2022-01-14 17:27
I think this is a duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3026

**Comment by bgavrilMS** [comment] 2022-12-21 15:41
We should have fixed this now. The WWW-Authenticate parser has been signficantly changed in 4.49.1

**Closed by bgavrilMS** 2022-12-21 15:41 UTC
Labels: duplicate
