### ISSUE TITLE
[Bug] More scopes than requested

### ISSUE THREAD

**Issue by queequac** [AzureAD/microsoft-authentication-library-for-dotnet#2682] opened 2021-06-05 12:18 UTC
There is always the same two scopes in addition that have not been explictly requested through API calls.
There is always the following asked consent for (and shown in the user's account for app permissions afterwards):
- View your basic profile
- Maintain access to data you have given <app> access to

It has to be noted that these two scopes are NOT being asked for when I do not use the library but create the login URL with required scopes myself, doing the authentication flow manually.

Is that by design?

**Which version of MSAL.NET are you using?**
Microsoft.Identity.Client, version 4.32.0

**Platform**
UWP

**What authentication flow has the issue?**
* Desktop / Mobile
    * [X] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?

**Is this a new or existing app?**
c. This is a new app or experiment.

**Repro**

```csharp
PublicClientApp = PublicClientApplicationBuilder.Create(ClientId).WithTenantId("consumers").Build();
var authResult2 = await PublicClientApp.AcquireTokenInteractive(scopes).ExecuteAsync();
```

**Expected behavior**
Only the scopes I request shall be asked for consent and shown in the user's account. I don't want permissions for the other scopes and don't want to user the think I'd really read his profile, etc.

**Actual behavior**
While AuthenticationResult object after successfull login indeed carries only my requested scopes, user is asked for two additional scopes (see above) and these additional scopes are also shown in the user's account [(Manage App Permissions)](https://account.live.com/consent/manage)

**Comment by jmprieur** [comment] 2021-06-07 07:56
@queequac 
This is by design indeed, as those scopes are needed for the token cache to work.

See https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2465#issuecomment-811335966 where @bgavrilMS wrote down the impact analysis of not having these scopes.

Closing as duplicate of #2465

**Closed by jmprieur** 2021-06-07 07:56 UTC
Labels: answered, duplicate, question, wontfix

**Comment by 23W** [comment] 2021-06-13 10:27
@jmprieur 
Can you please share link to the documentation page where it's mentioned that MSAL always adds `offline_access` and `User.Read` scopes to request?

**Comment by jmprieur** [comment] 2021-06-21 14:18
#2465 (comment)

**Comment by queequac** [comment] 2021-06-28 07:57
@jmprieur My gut feeling is that @23W was talking more about official documentation. This should be somewhere on https://docs.microsoft.com, maybe along with the API documentation.
Currently this is just an information shard hidden within a github issue...
