### ISSUE TITLE
U/P flow account null reference on acquire token silent

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-authentication-library-for-dotnet#850] opened 2019-01-29 16:43 UTC
**Which Version of MSAL are you using ?**
v2

**Platform**
Desktop

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [x] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Repro**
Repro with MSAL desktop app:
-	AT with u/p
-	Confirm token is in the cache
-	AT silent (hooray)
-	Delete the account
-	AT with u/p
-	Confirm token is in the cache
-	AT silent (null ref…account is null)

**Expected behavior**
The account in the cache is used for the silent call. 

**Actual behavior**
A null reference during the silent call as the account is null

**Comment by jennyf19** [comment] 2019-02-05 22:45
update...w/a fix to our desktop app, I am no longer able to repro the issue. Our RefreshUserList() was not getting called on the u/p flow, which created the null account. 

I checked w/Cormac, and he is unable to repro now as well, but he is going to do more testing to see if he can repro it again. Leaving open for a few more days.
cc: @henrik-me

**Comment by henrik-me** [comment] 2019-02-06 01:43
@jennyf19 can you add a link to what you believe have addressed this? Is it about developer guidance more than anything? Not sure I fully understand, but happy that it seems to work :)

**Comment by jennyf19** [comment] 2019-02-06 02:08
@henrik-me - I could "repro" it because our test app wasn't [refreshing the user list](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/870) after the interactive call, so deleting/removing accounts and tokens was enough to show the behavior. So, right now, because Cormac cannot repro it either, we don't have a clear cause or reason. But Cormac and I agreed it was best to leave open while he conducts more testing to see if he can repro it again. He thought maybe he combined flows, like device code w/u/p in the same session.

**Comment by henrik-me** [comment] 2019-02-06 02:18
@jennyf19 : ack. thanks for the update. now I finally get it

**Comment by jmprieur** [comment] 2019-02-08 08:48
@jennyf19 @henrik-me can we close this one if we cannot repro?

**Comment by henrik-me** [comment] 2019-02-08 14:05
Issues can always be re-opened if it turns out they are reproducable.

**Closed** 2019-02-08 14:04 UTC
Labels: no-repro, scenario:Desktop
