### ISSUE TITLE
iOS calling AcquireTokenAsync after cancellation throws cancellation exception second time but still displays WebView

### ISSUE THREAD

**Issue by tomas-dainovec** [AzureAD/microsoft-authentication-library-for-dotnet#672] opened 2018-11-05 12:35 UTC
---
name: iOS calling AcquireTokenAsync after cancellation throws cancellation exception second time but still displays WebView
about: On iOS using embedded WebView after cancelling authentication and calling AcquireTokenAsync again it immediately re-throws previous exception but still presents a WebView.

---

**Which Version of MSAL are you using ?**
2.3.1-preview

**Which platform has the issue?**
xamarin iOS

**What authentication flow has the issue?**
* Desktop 
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username / Password
    * [ ] Device code flow (browserless)
* Mobile
    * [x] Xamarin.iOS
    * [ ] Xamarin.Android
    * [ ] UWP
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO
* Daemon App
    * [ ] Client credentials
    
Other? - please describe;

**What is the identity provider ?**
* [ ] Azure AD
* [x] Azure AD B2C

If B2C, what social identity did you use?

**Repro**

```csharp
var pca = new PublicClientApplication(ClientId, AuthoritySignUpSignIn) 
{
    RedirectUri = $"msal{ClientId}://auth"
});
AuthenticationResult ar = null;

try {
    ar = await pca.AcquireTokenAsync(App.Scopes, (IAccount)null, UIBehavior.ForceLogin, string.Empty, null, App.AuthoritySignUpSignIn, App.UIParent /* using embedded WebView */);
}
catch (MsalClientException ex) {

    if (ex.ErrorCode=="authentication_canceled") {
        /* Authentication cancelled */
    }
}

try {
    ar = await pca.AcquireTokenAsync(App.Scopes, (IAccount)null, UIBehavior.ForceLogin, string.Empty, null, App.AuthoritySignUpSignIn, App.UIParent /* using embedded WebView */);
}
catch (MsalClientException ex) {
    /* Get thrown before tapping cancel! */
    if (ex.ErrorCode=="authentication_canceled") {
        /* Authentication cancelled */
    }
}
```

**Expected behavior**
A WebView is presented twice and exception is thrown after tapping on cancel button on a WebView.

**Actual behavior**
Second exception is thrown immediately after calling AcquireTokenAsync

**Possible Solution**
I believe the issue is that the callback, which signals the semaphore, is invoked twice in this method:
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/dev/core/src/Platforms/iOS/EmbeddedWebview/AuthenticationAgentUIViewController.cs#L107

**Comment by jennyf19** [comment] 2018-11-05 21:04
@tomas-dainovec I am unable to reproduce the error. I tried with our dev app and with the [Xamarin b2c sample](https://github.com/Azure-Samples/active-directory-b2c-xamarin-native). When I hit "cancel" I get a UserCancelledAuth error and then I can hit acquire token again and get the sign-in page again. 

I'm using iOS 12.1 simulator. Can you try with the sample I linked above and see if you get the same results there? thanks.

**Comment by jennyf19** [comment] 2018-11-05 21:05
@tomas-dainovec Did you try with Android or UWP by chance?

**Comment by tomas-dainovec** [comment] 2018-11-06 10:55
Sorry for the poor repro, I rushed through it without checking... I've forked the sample and modified it to reproduce the issue. It doesn't happen on Android and I'm not targeting UWP. The key point of my approach is to keep presenting authentication WebView until user is authenticated. Modified sample is here https://github.com/tomas-dainovec/active-directory-b2c-xamarin-native

**Comment by jennyf19** [comment] 2018-11-06 20:18
@tomas-dainovec Thanks for the repro. So you want the Android behavior? (where the Wingtip Tops UI is displayed always, and you're never redirected back to the app, until after sign-in?)

**Comment by tomas-dainovec** [comment] 2018-11-06 21:07
@jennyf19  On Android instead of a cancel button you have an Android back button so by default the behaviour is same as iOS. In the actual app I'm working on I put the app in to the background when back button is pressed and when the app comes back to the foreground the Authenticaion is displayed again. On the iOS there is no way to do this and the user expectaions are different. It would be great if there would be a way to hide the cancel button on iOS but the behaviour is still weird. 

After taking a quick look through the source code I've noticed that at [AuthenticationAgentUIViewController.CancelAuthentication](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/dev/core/src/Platforms/iOS/EmbeddedWebview/AuthenticationAgentUIViewController.cs#L107) the `callbackMethod` is called twice and the callback is passed from [EmbeddedWebUI](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/dev/core/src/Platforms/iOS/EmbeddedWebview/EmbeddedWebUI.cs). I didn't have a chance to check it but I suspect that because the callback releases the semaphore and it happens twice during the short period of time, is why it missbehaves.

Hopefully this makes sense, let me know if I'm missing something.

**Comment by jennyf19** [comment] 2018-11-06 21:14
@tomas-dainovec thanks...that's what I thought. can you email me and I'll send you a package to try out? jeferrie@microsoft.com

**Comment by jennyf19** [comment] 2018-11-09 23:41
@tomas-dainovec 
Fixed in latest release [Msal2.4.0-preview](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/MSAL-v2.4.0).

**Closed by jennyf19** 2018-11-09 23:41 UTC
Labels: scenario:B2C, scenario:Mobile-iOS
