### ISSUE TITLE
Crash on UWP when saving AccessToken

### ISSUE THREAD

**Issue by bergmolch** [AzureAD/microsoft-authentication-library-for-dotnet#614] opened 2018-09-20 07:18 UTC
---
UWP App crashes after typing in the correct credentials
---

**Which Version of MSAL are you using ?**
MSAL 2.0.1-preview

**Which platform has the issue?**
UWP

**What authentication flow has the issue?**
* Mobile

**Repro**

* Open the WebView where the credentials can be typed in
* Type in the credentials correctly
* Press OK

**Expected behavior**
AccessToken gets created and stored, app-flow continues

**Actual behavior**
Exception gets thrown, app crashes

**Additional context/ Logs / Screenshots**
This only happens after updating from MSAL 2.0.0-preview --> MSAL 2.0.1-preview

> A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. 
(The length of the state manager setting name has exceeded the limit.
Error trying to write application data container value)
   at System.Runtime.InteropServices.WindowsRuntime.IMap`2.Insert(K key, V value)
   at System.Runtime.InteropServices.WindowsRuntime.MapToDictionaryAdapter.Insert[K,V](IMap`2 _this, K key, V value)
   at System.Runtime.InteropServices.WindowsRuntime.MapToDictionaryAdapter.Indexer_Set[K,V](K key, V value)
   at Microsoft.Identity.Core.TokenCacheAccessor.SaveAccessToken(MsalAccessTokenCacheItem item)
   at Microsoft.Identity.Core.Telemetry.TelemetryTokenCacheAccessor.SaveAccessToken(MsalAccessTokenCacheItem item, RequestContext requestContext)
   at Microsoft.Identity.Client.TokenCache.SaveAccessAndRefreshToken(AuthenticationRequestParameters requestParams, MsalTokenResponse response)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.SaveTokenResponseToCache()
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.PostTokenRequest()
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.PublicClientApplication.<AcquireTokenForUserCommonAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.PublicClientApplication.<AcquireTokenAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at xxx.yyyyy.zzzz.abc.def.<SignUpOrInAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at xxx.yyyy.zzzz.abc.def.<SignUpOrInAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at xxx.yyyy.zzzz.abc.def.<LoginAsync>d__15.MoveNext()

**Comment by jennyf19** [comment] 2018-09-24 17:55
@bergmolch - I am unable to reproduce the issue on UWP. Can you share the code you are using for the AcquireToken call? Thanks.

**Comment by bergmolch** [comment] 2018-09-26 11:04
This is the call we use in the PCL:

 > var signUpOrInResult = await this.publicClientApplication.AcquireTokenAsync(
>                     this.azureSettings.Scopes,
>                     user, // null
>                     UIBehavior.SelectAccount,
>                     string.Empty,
>                     null,
>                     authority,
>                     uiParent // null
> ).ConfigureAwait(false);

This works with v. 2.0.0-preview and does not in 2.0.1-preview

**Comment by bgavrilMS** [comment] 2018-09-26 11:53
@bergmolch - do you have all the auth code in your PCL library? How do you construct the PublicClientApplication ?

**Comment by bergmolch** [comment] 2018-09-26 12:18
Yes, it is all in the PCL except for the UIParent-Provider which is implemented on each Platform. Android returns a UIParent which uses the embeddedWebView if no chrome is installed. iOS and UWP return null.
```
public IPublicClientApplication CreatePublicClientApplication(string clientId, string redirectUri)
{
    Guard.ArgumentNotNull(clientId, nameof(clientId));
    Guard.ArgumentNotNull(redirectUri, nameof(redirectUri));

    return new PublicClientApplication(clientId)
    {
        RedirectUri = redirectUri
    };
}
```

**Comment by bergmolch** [comment] 2018-09-26 12:29
It is a NetStandard (1.4) project

`<TargetFramework>netstandard1.4</TargetFramework>`

**Comment by jmprieur** [comment] 2018-10-02 04:38
@bgavrilMS : can this be due to the long key issue?

**Comment by bgavrilMS** [comment] 2018-10-02 14:04
@jmprieur  - Yes, this seems to be the case. Easy to confirm though - @bergmolch - what scopes are you using (or how many, if you do not wish to disclose the exact scopes). 

Related issue: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/612

**Comment by bgavrilMS** [comment] 2018-10-02 14:06
Closing as duplicate, based on the stack trace 

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/612

**Closed by bgavrilMS** 2018-10-02 14:06 UTC

**Comment by bergmolch** [comment] 2018-10-08 11:54
Version 2.2-preview fixed that issue, thanks!

**Comment by bgavrilMS** [comment] 2018-10-08 17:33
Thank you for confirming Fabian, much appreciated!
