### ISSUE TITLE
[Bug] Big Problem! Vast difference between AuthenticationResult.ExpiresOn and JWT's ValidTo times causes protected APIs to return 401s for up to 30mins

### ISSUE THREAD

**Issue by Camios** [AzureAD/microsoft-authentication-library-for-dotnet#3292] opened 2022-04-26 07:33 UTC
**Which version of MSAL.NET are you using?**
4.32.1 and 4.43.1

**Platform**
.NET 6

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?
Also on AcquireTokenSilent

**Is this a new or existing app?**

This is an existing App. It used to target .NET Framework 4.7.2 but is now targeting .NET 6

**Repro**

```csharp
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Security.Cryptography;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Identity.Client;
using Newtonsoft.Json;
using RestSharp;
using RestSharp.Authenticators;

namespace AuthTest
{
	// RecordingHandler and HttpSnifferClientFactory are from https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/tree/5a61d0c7adb2d30ffd6c61ac75501f7af1bfa063/tests/Microsoft.Identity.Test.Common/Core/Helpers and have been left out for brevity
	
	public static class AzureAuth
	{
		private static readonly string s_clientId = "AppClientId";
		private static readonly string s_tenant = "AppTenantId";
		private static readonly string[] s_scopes = new string[] { "user.read" };
		
		private static readonly IPublicClientApplication s_clientApp;

		static AzureAuth()
		{
			s_clientApp = PublicClientApplicationBuilder.Create(s_clientId)
				.WithAuthority(AzureCloudInstance.AzurePublic, s_tenant)
				.WithDefaultRedirectUri()
				.WithHttpClientFactory(new HttpSnifferClientFactory())
				.WithLogging(MyLoggingMethod, LogLevel.Info,
					   enablePiiLogging: true,
					   enableDefaultPlatformLogging: false)
				.Build();
			// file-based cache from samples - class left out for brevity
			TokenCacheHelper.EnableSerialization(s_clientApp.UserTokenCache);
		}

		static void MyLoggingMethod(LogLevel level, string message, bool containsPii)
		{
			System.Diagnostics.Debug.WriteLine($"{level} {message}");
		}

		public static async Task<string> GetAuthToken()
		{
			AuthenticationResult authResult = null;
			var accounts = await s_clientApp.GetAccountsAsync();
			var firstAccount = accounts.FirstOrDefault();

			try
			{
				authResult = await s_clientApp.AcquireTokenSilent(s_scopes, firstAccount).ExecuteAsync();
				System.Diagnostics.Debug.WriteLine("Silently acquired new token");
			}
			catch (MsalUiRequiredException msalEx)
			{
				// This indicates you need to call AcquireTokenInteractive to acquire a token
				try
				{
					authResult = await s_clientApp.AcquireTokenInteractive(s_scopes)
						.WithAccount(firstAccount)
						.WithPrompt(Prompt.SelectAccount)
						.ExecuteAsync();
					System.Diagnostics.Debug.WriteLine("Interactively acquired new token");
				}
				catch (Exception ex)
				{
					Console.WriteLine($"Error Acquiring Token:{Environment.NewLine}{ex}");
					throw;
				}
			}
			catch (Exception ex)
			{
				Console.WriteLine($"Error Acquiring Token:{Environment.NewLine}{ex}");
				throw;
			}

			var authToken = authResult.IdToken;
			var tokenExpiry = authResult.ExpiresOn;
			var handler = new System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler();
			var token = handler.ReadJwtToken(authToken);			
			System.Diagnostics.Debug.WriteLine($"New token expires: {tokenExpiry}. ValidTo: {token.ValidTo} Currently: {DateTimeOffset.UtcNow}");
			return authToken;
		}
	}
}
```

**Expected behavior**
 AuthenticationResult.ExpiresOn should match JWT's ValidTo

**Actual behavior**
`AuthenticationResult.ExpiresOn` can have an expiry that is (randomly/significantly) longer than the JWT's `ValidTo`, As such the `ExpiresOn` cannot be relied upon. `Given AcquireTokenSilently` uses `ExpiresOn` then that means it won't refresh the token soon enough and expired tokens will be sent to protected APIs (resulting in 401s) until the `ExpiredOn` time has past. Here's one example showing 17mins delta where SDK incorrectly thinks the token is valid:
New token ExpiresOn: 27/04/2022 6:55:49 AM +00:00. 
JWT ValidTo: 27/04/2022 6:38:26 AM 
Currently: 27/04/2022 6:44:28 AM +00:00

Another example ( all dates local time, but expiries are a whole day different):
New token expires: 27/04/2022 8:59:03 PM +10:00. 
ValidTo: 28/04/2022 7:58:59 PM 
Currently: 27/04/2022 8:09:12 PM +10:00

**Additional context / logs / screenshots / links to code**

[MSAL log 4.43.1 interactive.txt](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/8560853/MSAL.log.4.43.1.interactive.txt)

I tried the sample https://github.com/Azure-Samples/active-directory-dotnet-desktop-msgraph-v2 and it is returning an ExpiredOn time that matches the JWT ValidTo value. So not sure if there's a BUG in the SDK for non-common tenant or some other reason, a bug in the above code or an environment problem with the tenant AD ?
I tried making my app use the common tenant and client id from the sample app, but the two expiry times still don't match. So that rules out the tenant.
I checked and the sample app is using .NET Framework 4.6.1 where as I'm using .NET 6 but converting the sample app over and sample app still has the same expiry.
Not sure what our app is doing any differently to the sample app to cause this expiry time delta.

**Comment by SameerK-MSFT** [comment] 2022-04-27 22:28
Please try w/o static constructor and using instance methods and see if that makes any difference.

**Comment by Camios** [comment] 2022-04-27 23:45
I found the difference, the code in this issue uses the IdToken whereas the code in the msgraph sample uses AccessToken.

**Comment by Camios** [comment] 2022-04-27 23:55
Seems this code was using IdToken when it should have been using AccessToken all this time. But it does raise the question, should the IdToken have the same expiry as the AuthenticationResult's ExpiresOn?

**Comment by Camios** [comment] 2022-04-28 00:52
Tried using the AccessToken but APIM validate-jwt policy fails with `JWT Validation Failed: IDX10511: Signature validation failed. Keys tried: 'Microsoft.IdentityModel.Tokens.X509SecurityKey, ...`

This is new (didn't happen for IdToken), not sure what do I need to do?

**Comment by bgavrilMS** [comment] 2022-05-02 13:31
Hi @Camios - thanks for figuring this out on your own :). When we designed MSAL, we assumed that IdToken expiration == Access Token expiration. It seems this is not really the case, and we'll need to rethink our API around this. 

But for now, let me try to clarify a few things: 

- You should not parse the access token. Only the protected resource should do this. Rely on ExpiresOn property in the AuthenticaionResult
- You can parse the IdToken (in fact MSAL does this for you - see the ClaimsPrincipal property on AuthenticaionResult). You can use this to figure out who the user is (we expose this as result.Account.Username). you can add optional claims to id token. Id Tokens are for your app to provide a basic "logged in" experience. 
- IdToken expiry is based on the `exp`, `nbf`, `iat` claims in the token. 

Similar issue tracked by MSAL js: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4206

**Comment by Camios** [comment] 2022-05-02 21:58
Hi @bgavrilMS, 
I'm looking to protect a custom, non-Graph API, the documentation says to use the access token is that correct?
Regarding your first two points "always use the access token to access a protected resource" and "You should not parse the access token", I might be confused:  if the protected resource is a non-Graph API, then surely some kind of parsing must be performed by the non-Graph protected API to validate the access token? 
Are two (or possibly more) different access token types generated (e.g. if asking for Graph scope then you get a Graph access token? if asking for a non-Graph (custom) API then do you get a regular JWT? There might be other scopes which generate different access token types?
If it is an Azure APIM API, then can't I take advantage of a validate-jwt policy to check claims like `scp`, `aud` and `acp` (it can optionally check `exp` automatically by default)? 
If it is a custom API, then wouldn't I have to validate some way too - which likely involves parsing the token?

**Comment by jmprieur** [comment] 2022-05-03 01:23
@Camios: Are you using ASP.NET Core or ASP.NET ?
See https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-protected-web-api-overview to protect a web API, and https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-api-call-api-overview if your web API calls a downstream web API.

**Comment by Camios** [comment] 2022-05-03 01:56
@jmprieur 
The frontend client is a WPF desktop and MSAL .NET SDK to acquire token interactively (auth code grant). 
The protected API is Azure APIM and will use `validate-jwt` policy

**Comment by bgavrilMS** [comment] 2022-05-03 11:13
@Camios - MSAL is used exclusively for token acquisition, not for token validation. Your WPF app will acquire an Id Token and an Access Token for the user. Your WPF app is expected to: 

- create an HTTP request with an Authenticate header containing the **access token** and use that to access your API. You should not attempt to parse the access token in your WPF app.
- optionally parse the id token in your WPF app to provide a "logged in" experience (e.g. show a button with "You are logged in as joe@contoso.com. Click here to sign out". Note that MSAL pre-parses this for you and if all you need is the username, just use `AuthenticationResult.Account.UserName`

Id Token format is described here: https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens (the v2 one, since MSAL hits AAD's v2 endpoint)


On the token validation part I'm afraid I don't know enough about APIM's model. We have a good solution for ASP.NET / ASP.NET Core and [Azure Functions](https://github.com/Azure-Samples/ms-identity-dotnet-webapi-azurefunctions). @jmprieur 
@jennyf19  - do you know of token validation guidance for APIM?

At a high level, you should: 

- do general validation of the token (probably validate-jwt does that for you)
- validate the scope (at this stage you should parse the token)
- then move on to authorization (this is mostly outside the scope of our libraries)

**Comment by bgavrilMS** [comment] 2022-07-26 12:32
Closing as duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3119

**Closed by bgavrilMS** 2022-07-26 12:32 UTC
Labels: Feature Request
