### ISSUE TITLE
[Bug] - MSAL.Desktop.4.36.0.0.MsalServiceException: User canceled authentication' - Account picker automatically closes on Windows Server 2016

### ISSUE THREAD

**Issue by sparkspriya** [AzureAD/microsoft-authentication-library-for-dotnet#2865] opened 2021-09-03 15:06 UTC
**Logs and network traces**
MSAL.Desktop.4.36.0.0.MsalServiceException: 
    ErrorCode: authentication_canceled
Microsoft.Identity.Client.MsalServiceException: Broker response returned error: User canceled authentication. 
   at Microsoft.Identity.Client.Internal.Broker.BrokerInteractiveRequestComponent.ValidateResponseFromBroker(MsalTokenResponse msalTokenResponse)
   at Microsoft.Identity.Client.Internal.Broker.BrokerInteractiveRequestComponent.<FetchTokensAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<FetchTokensFromBrokerAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<GetTokenResponseAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<ExecuteAsync>d__8.MoveNext()

**Which version of MSAL.NET are you using?**
MSAL.NET 4.36.0.0

**Platform**
NET 4.7.2

**What authentication flow has the issue?**
* Desktop
    * [ *] Interactive
  
**Repro**

```                                            
authResult = await app.AcquireTokenInteractive(scopes)
						.WithParentActivityOrWindow(Application.Current.MainWindow) 
						.WithPrompt(Prompt.SelectAccount)
						.ExecuteAsync();
```

**Expected behavior**
My Application works perfectly in local machine which runs on Windows 10. It needs to work in other windows platforms as well.

**Actual behavior**
My Application works perfectly in local machine which runs on Windows 10. When I moved the sources to VM which runs on Windows server 2016, It gives 'MsalServiceException: User canceled authentication' on the below code. Account picker is blinking and vanishing automatically. I haven't cancel anything.

**Comment by jmprieur** [comment] 2021-09-07 01:52
@bgavrilMS @trwalke @SameerK-MSFT @pmaytak : do you have an idea?

**Comment by bgavrilMS** [comment] 2021-09-07 08:04
Hi @sparkspriya - is this machine upgraded to R2 or not? Is it domain joined?

**Comment by bgavrilMS** [comment] 2021-11-18 12:38
Duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2946

**Closed by bgavrilMS** 2021-11-18 12:38 UTC
Labels: Investigate
