### ISSUE TITLE
[Bug] Exception using sign in with Apple Id with multiple apps

### ISSUE THREAD

**Issue by anandthirumala** [AzureAD/microsoft-authentication-library-for-dotnet#1971] opened 2020-08-03 21:24 UTC
**Which Version of MSAL are you using ?**
4.17.0.0

Platform
xamarin iOS

What authentication flow has the issue?
Desktop / Mobile

I'm getting the following exception, Kindly help;

The issue clearly is when using multiple apps. Can't get more than one app to work. If I make one work then the other one will break with this exception.

Microsoft.Identity.Client.MsalServiceException:

AADB2C90289: We encountered an error connecting to the identity provider. Please try again later.

Correlation ID: 18012cae-fff9-4860-88f5-d2fd863466d4

More Detail:

MSAL.Xamarin.iOS.4.17.0.0.MsalServiceException:
ErrorCode: server_error
Microsoft.Identity.Client.MsalServiceException: AADB2C90289: We encountered an error connecting to the identity provider. Please try again later.
Correlation ID: 18012cae-fff9-4860-88f5-d2fd863466d4
Timestamp: 2020-08-03 20:23:54Z
at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.VerifyAuthorizationResult (Microsoft.Identity.Client.UI.AuthorizationResult authorizationResult, System.String originalState) [0x000f4] in <7947183ece5641aeafbe279109f4072b>:0
at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.FetchAuthCodeAndPkceInternalAsync (Microsoft.Identity.Client.UI.IWebUI webUi, System.Threading.CancellationToken cancellationToken) [0x00165] in <7947183ece5641aeafbe279109f4072b>:0
at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.FetchAuthCodeAndPkceVerifierAsync (System.Threading.CancellationToken cancellationToken) [0x0007d] in <7947183ece5641aeafbe279109f4072b>:0
at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.GetTokenResponseAsync (System.Threading.CancellationToken cancellationToken) [0x00178] in <7947183ece5641aeafbe279109f4072b>:0
at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.ExecuteAsync (System.Threading.CancellationToken cancellationToken) [0x000fa] in <7947183ece5641aeafbe279109f4072b>:0
at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync (System.Threading.CancellationToken cancellationToken) [0x001dd] in <7947183ece5641aeafbe279109f4072b>:0
at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.ExecuteAsync (Microsoft.Identity.Client.ApiConfig.Parameters.AcquireTokenCommonParameters commonParameters, Microsoft.Identity.Client.ApiConfig.Parameters.AcquireTokenInteractiveParameters interactiveParameters, System.Threading.CancellationToken cancellationToken) [0x000d6] in <7947183ece5641aeafbe279109f4072b>:0
at SignInInteractively () [0x00113] in AzureAuthentication.cs:139
StatusCode: 0
ResponseBody:
Headers: }

**Comment by jennyf19** [comment] 2020-08-05 01:18
@anandthirumala I answered you on the [other issue](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1420#issuecomment-668256165). Not sure how to help you here, as Apple Sign-in is in preview w/B2C, and as I mentioned, you should try contacting Josh (jodougla@microsoft.com) for help with the configuration. Can you provide a repro w/two applications so we can try it out?

**Comment by bgavrilMS** [comment] 2020-08-05 15:11
Duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1420

**Closed by bgavrilMS** 2020-08-05 15:11 UTC
Labels: B2C, IdP: Apple, requires more info
