### ISSUE TITLE
[Bug] Windows Unity support missing.

### ISSUE THREAD

**Issue by najadojo** [AzureAD/microsoft-authentication-library-for-dotnet#2304] opened 2020-12-14 16:50 UTC
**Which Version of MSAL are you using ?**
MSAL 4.10.0.0

**Platform**
net45

**What authentication flow has the issue?**
* Desktop / Mobile
    * [X] Interactive
    * [X] Integrated Windows Auth
    * [ ] Username Password
    * [X] Device code flow (browserless)
* Web App 
    * [ ] Authorization code
    * [ ] OBO
* Daemon App 
    * [ ] Service to Service calls

Other? - please describe;

**Is this a new or existing app?**
This is a new app or experiment

**Repro**
We are creating a Unity app that uses MSAL for authentication. Currently we are running into [System.Security.Cryptography.SHA256Cng not implemented](https://forum.unity.com/threads/system-security-cryptography-sha256cng-not-implemented.614188/) exception. The project works fine in Editor mode but when the project is built for standalone the linked issue occurs.

**Expected behavior**
No not implemented exception

**Actual behavior**
Standalone application throws a not implemented exception for SHA256Cng.

**Possible Solution**
Fallback SHA265 implementation or other work around assembly that could be added to Unity?

**Comment by jmprieur** [comment] 2020-12-14 19:04
@najadojo : do you mind if we close this one as a dupe of #2305  ? We don't really test Unity.
See Also #2231 and #1991

**Closed** 2020-12-14 20:46 UTC
Labels: bug
