### ISSUE TITLE
Google IDP throwing "This browser or app may not be secure." (External Identities)

### ISSUE THREAD

**Issue by pottabathini** [AzureAD/microsoft-authentication-library-for-dotnet#1851] opened 2020-05-30 06:20 UTC
**Which Version of MSAL are you using ?**
Downloaded MSAL Desktop app from QuickStarts inside Portal AAD Applications blade. 
(Quickstart: Acquire a token and call Microsoft Graph API from a Windows desktop app)

**Platform**
net45

**What authentication flow has the issue?**
*  Desktop
    * [ Yes] Interactive

**Is this a new or existing app?**
New App. Created for Testing

**Repro**

1. Follow below doc to enable self-service signup and add Google IDP
2. https://docs.microsoft.com/en-in/azure/active-directory/b2b/self-service-sign-up-user-flow
3. Download the MSAL desktop app from quick start (Inside AAD -> Application) and start running the application. 
4. Choose Google IDP and it will throw exception

**Expected behavior**
Desktop App should allow to login with Google IDP.

**Actual behavior**
![image](https://user-images.githubusercontent.com/11867309/83260029-b0d45480-a1d6-11ea-9504-6bc0337968bc.png)

**Comment by bgavrilMS** [comment] 2020-06-01 14:20
Root cause for this is that MSAL uses an embedded IE browser on .net desktop. 

I think the main out of this today is to try to use the use the system web browser (details [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/System-Browser-on-.Net-Core#system-browser-experience))

Otherwise, we need to find a way to use a more modern embedded browser. I don't think this is possible for .net classic 4.5, but we should be able to make it work on .net core (Tracking issue [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1398)) or you can make it work from you app by providing your own ICustomWebUi implementation.

**Comment by jmprieur** [comment] 2020-06-02 09:05
Closing as this question is answered

**Comment by agrabhi** [comment] 2020-06-03 00:00
@jmprieur - shouldnt the solution work out of box? It seems customer needs to do extra steps to be able to use MSAL for desktop

**Comment by jmprieur** [comment] 2020-06-03 09:47
@agrabhi 
Indeed, the system web browser is used by default for mobile platforms (Xamarin.iOS / Android), but the embedded Web view is used for desktop as using the system web view does not give a very good user experience.

Adding @brandwe to comment as he owns the desktop scenarios.

Note that the work to be done for desktop apps using MSAL.NET is minimal: https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-desktop-acquire-token?tabs=dotnet#provide-a-great-experience-with-systemwebviewoptions

**Comment by bgavrilMS** [comment] 2020-06-03 11:38
Using the system browser on desktop apps + B2C is further hampered by the fact that some IdP, such as Facebook, do not allow redirect URIs of "http://localhost"

**Comment by bgavrilMS** [comment] 2020-06-03 12:31
We have worked planned for .net core to use a browser other than IE - https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1398

For .net classic, because we need to support .net 4.5, this solution will not work. You can however configure which browser is used by WebBrowser via a registry setting - see https://stackoverflow.com/questions/38514184/how-can-i-get-the-webbrowser-control-to-show-modern-contents

**Comment by agrabhi** [comment] 2020-06-03 16:32
@bgavrilMS @jmprieur  I am somehow not convinced with the solution here.

- Are we expecting all consumers of apps to make the registry change?
- #1398 is only for .net core, what about .net standard?

We need to support it out of box for .net standard as well.

**Comment by bgavrilMS** [comment] 2020-06-03 16:50
`Are we expecting all consumers of apps to make the registry change?` - we are expecting that IT admins can set this registry key via group admin policy.

`what about .net standard?` 
Our support for .NET Standard is minimal. We do not support web UIs from .net standard. The only motivation for .net standard is that so MSAL plays nice with Xamarin. If you think about it, webviews are framework specific - the webview on .net classic is significantly different than the one for Android etc. MSAL provides support for .net 45 +, .net core 2.1 +, UWP, Xamarin Android, iOS and Mac. We had to write webview code for each of these platforms.

But all in all, I agree the experience of having a sample not working out of the box is bad and we need to do more here. I believe @aiwangmicrosoft owns desktop scenarios and she can help plan this.

**Comment by bgavrilMS** [comment] 2020-06-09 19:00
I think the solution here is to upgrade our embedded webview to use Edge instead of IE. Will that work? 

@jmprieur for thoughts on this.

**Comment by jmprieur** [comment] 2020-06-10 10:08
I'm not sure @bgavrilMS : we'd need to try
it might be that Google only allows for system browser. @brandwe would you know?

**Comment by bgavrilMS** [comment] 2020-06-25 16:48
Closing in favour of #1398

**Closed by bgavrilMS** 2020-06-25 16:48 UTC
Labels: IDP: external identities, Investigate, bug
