### ISSUE TITLE
[Bug] SystemWebViewOptions.BrowserRedirectSuccess not working on iOS

### ISSUE THREAD

**Issue by weases** [AzureAD/microsoft-authentication-library-for-dotnet#4844] opened 2024-07-17 10:11 UTC
### Library version used

4.60.4

### .NET version

.NET Standard 2.1

### Scenario

PublicClient - mobile app

### Is this a new or an existing app?

The app is in production, I haven't upgraded MSAL, but started seeing this issue

### Issue description and reproduction steps

Trying to implement a workaround for the bug of iOS just showing the save password dialog briefly - see [here](https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/848) for more information.

As stated in this [comment](https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/848#issuecomment-790068352) one way to solve this would be to extend the flow and show a login success page.

Unfortunately this does not seem to work properly - the new page is never shown.

```
SystemWebViewOptions options = new()
{
	//HtmlMessageSuccess = "<p> You have successfully signed in. </p>"
	BrowserRedirectSuccess = new Uri("https://www.microsoft.com")
};

AuthenticationResult result = await authBuilder
.WithSystemWebViewOptions(options)
.ExecuteAsync().ConfigureAwait(true);
```

I am using this in a Xamarin.Forms application using iOS 17.5.1.

Any idea?

### Identity provider

Azure B2C Basic Policy

**Comment by bgavrilMS** [comment] 2024-07-21 09:52
This is by design. On ios the sdk is able to fully control the browser. There is no need to display a success message, the app will just close the browser. 

On windows, mac and Linux, the sdk cannot close the browser. So we display a message for the user to do it.

**Comment by weases** [comment] 2024-07-21 16:01
I see
Could you consider this issue as a feature request then please?
As mentioned above I would need this as a workaround for [this issue](https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/848). I guess there will be no fix for this in the foreseeable future...

**Comment by iulico-1** [comment] 2024-07-24 16:22
Closing the issue as by design.

**Closed** 2024-07-24 16:22 UTC
Labels: question, answered, untriaged, needs attention, public-client
