### ISSUE TITLE
[Bug] UWP App Fails Microsoft Certification due to restricted API

### ISSUE THREAD

**Issue by TheJoeFin** [AzureAD/microsoft-authentication-library-for-dotnet#3256] opened 2022-03-30 15:48 UTC
**Which version of MSAL.NET are you using?**
MSAL.NET 4.42.1

**Platform**
UWP

**What authentication flow has the issue?**
No issue in the app when using it. The package works well.

Other?
Fails the Microsoft Store certification due to restricted api:
`API RtlGetVersion in ntdll.dll is not supported for this application type. InkCalendar.dll calls this API.`

**Is this a new or existing app?**
The app is in production, and I have upgraded to a new version of MSAL.

**Possible solution**
Rolled back to 4.42.0 and the submission passed.

**Comment by TheJoeFin** [comment] 2022-03-31 18:59
Thanks for the update! Looking forward to it!

**Comment by bgavrilMS** [comment] 2022-04-04 12:40
duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3184

**Closed** 2022-04-04 18:11 UTC
Labels: bug, uwp
