### ISSUE TITLE
[Bug] After Log-out, "use another account" does not work correctly

### ISSUE THREAD

**Issue by mvancamp** [AzureAD/microsoft-authentication-library-for-dotnet#1341] opened 2019-08-14 13:38 UTC
**Which Version of MSAL are you using ?**
MSAL 4.1.0.0

**Platform**
.NET Framework 4.7.2

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Is this a new or existing app?**
Experimenting (using both samples from AzureAD MSAL samples: active-directory-dotnet-desktop-msgraph-v2 and ms-identity-aspnet-webapi-onbehalfof) to migrate existing WPF application logon scenarios to Azure AD authentication.
Running on a workstation which is joined a domain network where domain AD is synced with AzureAD.

**Repro**

```csharp
see samples (unchanged code from GitHub, except needed configuration for tenant, client and keys)
```

**Expected behavior**
Being able to logon different (own organisation) users on the application. After filling in the username (on the UI response from AcquireTokenInteractive call) an new UI should be presented requesting to fill in the password for this validated user.

**Actual behavior**
In stead of displaying the "Enter password" UI, the UI with the message "Taking you to your organisations  sign-in page" is displayed and the application is logged on with the account logged on to the workstation in the domain!!  Not being able to switch in the application from account.

**Possible Solution**
wish I had a solution 👯‍♂ 

**Additional context/ Logs / Screenshots**
sample code used: 
- git clone https://github.com/Azure-Samples/active-directory-dotnet-desktop-msgraph-v2.git
- git clone https://github.com/Azure-Samples/ms-identity-aspnet-webapi-onbehalfof.git

**Comment by bgavrilMS** [comment] 2019-08-14 14:09
I don't think OBO has anything to do here, because OBO is just getting a token based on another token. The first token you get is using interactive authentication, which is where you see the problem. 

The reason this happens is that AAD will actually store some browser cookies so it knows who you are and you don't need a password. This is because you have logged in before. 

You have some control over how the UI behaves by using the Prompt param - have look at the possible options and see what suits you best. Use .ForceLogin if you want to ensure that users always type a password. 

The current value Prompt.Select account should be pretty good for the general case since it is expected that a single user uses his own computer / OS account / browser.

**Comment by jmprieur** [comment] 2019-08-14 16:06
@mvancamp are you using a tenanted authority ? or common? do you sign-in with a guest account?

**Comment by bgavrilMS** [comment] 2019-08-14 16:15
He's using the sample as is Jean-Marc. 

https://github.com/Azure-Samples/active-directory-dotnet-desktop-msgraph-v2/blob/msal3x/active-directory-wpf-msgraph-v2/MainWindow.xaml.cs#L53

**Comment by mvancamp** [comment] 2019-08-14 16:37
Hi, Thx for commenting. @jmprieur it is with a tenanted authority. @bgravilMS I will try with the ForceLogin prompt option and I’ll come back. From now until Sunday 25th I’m in holidays, hence the earliest I can get to it will be Monday 26th.

**Comment by bgavrilMS** [comment] 2019-08-14 17:05
Sounds good. I'm going to close this because it's not a bug, but feel free to ask a question or reopen.

**Comment by Atvaark** [comment] 2019-08-26 09:35
Hey @bgavrilMS,

I also noticed this odd behaviour when trying to log in with another account of the same AAD tenant.
While using `Prompt.ForceLogin` does work as a workaround, I'd prefer not having to use it.

Currently `Prompt.SelectAccount` silently picks the account in this browser cookie. You can't even check afterwards if the selected account is the one returned in `AuthenticationResult.Account.Username`.
`Prompt.Consent` also skips the password prompt if a different account is selected, but at least displays the account the browser cookie belongs to instead of the selected account in the consent UI.

Shouldn't this browser cookie only be used if the account the cookie belongs to is selected in the prompt?

**Comment by bgavrilMS** [comment] 2019-08-26 09:57
@Atvaark - Have you tried passing in `.WithLoginHint` or `WithAccount` ? 

@jmprieur - the behavior of the browser cookie is becoming quite contentious, but MSAL does not own it. How can we funnel feedback back to the teams that owns it?

**Comment by Atvaark** [comment] 2019-08-26 11:29
> Have you tried passing in `.WithLoginHint` or `WithAccount` ?

Neither option fixes the behavior of the prompt for my use case.
`WithAccount` causes the exception described in #1031 if I pick the account that doesn't belong to the browser cookie.

Another observation I made is that if I first successfully log into multiple accounts (e. g. account *A* and account *B*) via `Prompt.ForceLogin` (and `IPublicClientApplication.GetAccountsAsync` returns two `IAccount` instances *A* and *B*) and then use `Prompt.SelectAccount` the resulting `AuthenticationResult.Account` is either:
- *A* or *B* if the selected account was one of the accounts I previously logged into
- *A*, the first account I previously logged into, if I enter the account *C*. There is once again no password prompt for account *C* after the redirect.

**Comment by mvancamp** [comment] 2019-08-26 13:09
Hi @bgavrilMS,

Tried the different set-ups.  None of them perform as it should be.  The application will always sign-in with current domain user logged on to the system. Even if "log on with different account" is selected and a different account name is filled in, it automatically logs on with the current domain user.

**Comment by jmprieur** [comment] 2019-09-23 07:37
Duplicate of #1365, fixed in MSAL.NET 4.4.0
@mvancamp, @Atvaark,  : can you please check that this now works for you?

**Closed** 2019-09-23 07:38 UTC
Labels: Fixed

**Comment by jmprieur** [comment] 2019-09-24 11:02
@Atvaark : you mean prompt.SelectAccount  (as shown in the samples) does not work? I retested them on Friday and they worked?
Do you have the possibility of deleting the cache to start from fresh?
