### ISSUE TITLE
[Bug] "MsalClientException: Non-HTTPS url redirect is not supported in webview"

### ISSUE THREAD

**Issue by omghb** [AzureAD/microsoft-authentication-library-for-dotnet#1264] opened 2019-07-11 07:02 UTC
**Which Version of MSAL are you using ?**
Microsoft.Identity.Client 4.1.0

**Platform**
xamarin android

**Expected behavior**
My app has implemented this: https://docs.microsoft.com/en-us/graph/tutorials/xamarin but with latest NuGet packages of Xamarin and MSAL.
Auth should work.

**Actual behavior**
Auth runs on iOS and UWP but on Android I get the following exception:
```
{Microsoft.Identity.Client.MsalClientException: Non-HTTPS url redirect is not supported in webview
  at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.VerifyAuthorizationResult () [0x000a9] in <9dca914e44c74ee3a9af8097cb2f5dfe>:0 
  at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest+<ExecuteAsync>d__9.MoveNext () [0x000f8] in <9dca914e44c74ee3a9af8097cb2f5dfe>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.Identity.Client.Internal.Requests.RequestBase+<RunAsync>d__14.MoveNext () [0x001d2] in <9dca914e44c74ee3a9af8097cb2f5dfe>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor+<ExecuteAsync>d__2.MoveNext () [0x000f2] in <9dca914e44c74ee3a9af8097cb2f5dfe>:0 
--- End of stack trace from previous location where exception was thrown ---
  at xx.Presentation.Services.MSAuthService+<SignIn>d__6.MoveNext () [0x0022b] in C:\xx.Presentation\Services\MSAuthService.cs:60 
--- End of stack trace from previous location where exception was thrown ---
  at xx.Applications.ViewModels.SyncSettingsModel+<Login>d__21.MoveNext () [0x0003a] in xx.Applications\ViewModels\SettingsViewModel.cs:100 
	ErrorCode: non_https_redirect_failed}
```

**Possible Solution**
Workaround: Downgrade Microsoft.Identity.Client from 4.1.0 to 4.0.0 and it works on Android.

**Comment by jmprieur** [comment] 2019-07-11 15:59
@bgavrilMS : do you think this is related to the web view customization changes?

**Comment by mfeingol** [comment] 2019-07-16 19:28
I am seeing the same issue with 4.1.0 on an Android app. 4.0.0 works.

**Comment by mfeingol** [comment] 2019-07-21 02:29
Do you need a repro?

**Comment by jmprieur** [comment] 2019-07-21 06:50
@mfeingol : yes please

**Comment by jennyf19** [comment] 2019-07-21 15:01
@mfeingol can you share the code you use for creating the public client and the acquire token calls? Thx.

**Comment by mfeingol** [comment] 2019-07-21 16:40
Your official Xamarin sample exhibits the issue with code almost identical to my app, so I've updated and attached that.

[active-directory-xamarin-native-v2.zip](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/3414803/active-directory-xamarin-native-v2.zip)

Let me know if you don't see the problem.

**Comment by jennyf19** [comment] 2019-07-21 17:11
@mfeingol thanks for the additional info. Will try the sample out

**Comment by jennyf19** [comment] 2019-07-25 14:25
@mfeingol @omghb I just tried with the repro you provided w/and Android device (pixel 2) and could not reproduce the issue. I updated to the latest version of MSAL 4.2.1.

I also have not run into this issue when testing w/our samples lately...can you try w/4.2.1?

**Comment by mfeingol** [comment] 2019-07-25 23:08
4.2.1 appears to work with my app on Android, so I'll consider this fixed.

That said, you might want to check with 4.1.0 just to make sure that you can reproduce the issue before calling it fixed.

**Comment by omghb** [comment] 2019-07-26 06:18
The version 4.2.1 seems to fix this issue in my App. Sign-in works again on Android.

**Comment by jennyf19** [comment] 2019-07-26 09:01
@mfeingol @omghb I tried w/4.1 and 4.2.0 w/embedded webview and system browser and could not reproduce the issue. Going to close this, as you've both confirmed that 4.2.1 works, but please reopen if you see this again. Thanks for bringing this to our attention.

**Comment by jennyf19** [comment] 2019-07-26 09:02
@mfeingol @omghb and I confirm this is working in 4.2.1. I was not able to reproduce in earlier versions, closing this issue.

**Comment by janschoelchAtOK** [comment] 2020-06-29 08:59
This might have reappeared somewhere after MSAL 4.2.1.
If I use MSAL 4.2.1, everything works as expected.
When using MSAL 4.2.15 (latest version), I receive the error @omghb described again:

```
Exception type: Microsoft.Identity.Client.MsalServiceException
, ErrorCode: non_https_redirect_failed
HTTP StatusCode 0
CorrelationId 

at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.VerifyAuthorizationResult (Microsoft.Identity.Client.UI.AuthorizationResult authorizationResult, System.String originalState) [0x000f4] in <5379e12126bf461d83f6959d6b241d45>:0 
  at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.FetchAuthCodeAndPkceInternalAsync (Microsoft.Identity.Client.UI.IWebUI webUi, System.Threading.CancellationToken cancellationToken) [0x00165] in <5379e12126bf461d83f6959d6b241d45>:0 
  at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.FetchAuthCodeAndPkceVerifierAsync (System.Threading.CancellationToken cancellationToken) [0x0007d] in <5379e12126bf461d83f6959d6b241d45>:0 
  at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.GetTokenResponseAsync (System.Threading.CancellationToken cancellationToken) [0x00178] in <5379e12126bf461d83f6959d6b241d45>:0 
  at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.ExecuteAsync (System.Threading.CancellationToken cancellationToken) [0x000fa] in <5379e12126bf461d83f6959d6b241d45>:0 
  at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync (System.Threading.CancellationToken cancellationToken) [0x0016e] in <5379e12126bf461d83f6959d6b241d45>:0
```

Still only appearing on Android.

**Comment by bgavrilMS** [comment] 2020-06-29 11:19
Looks like an error from the server, related to embedded browser: 

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/e60f336c410e696794dbc2dc25d22afa13113ba3/src/client/Microsoft.Identity.Client/Platforms/Android/EmbeddedWebview/AuthenticationAgentActivity.cs#L118

Workaround would be to use the system browser.

**Comment by bgavrilMS** [comment] 2020-06-29 11:20
@janschoelchAtOK - does this always happen?

**Comment by bgavrilMS** [comment] 2020-06-29 11:21
And can you get us some logs please? https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging Feel free to send them directly (bogavril at microsoft com) if needed.

**Comment by janschoelchAtOK** [comment] 2020-06-29 11:33
It indeed only happens when using the embedded browser as you suspected. I will send you the logs directly.

**Comment by bgavrilMS** [comment] 2020-07-08 11:58
Apologies for the long delay. From the logs I gather that the redirect uri configured is `msalXXXXXXXXXXXXXXX://auth` and this is fine. 

The embedded webview needs to understand when the browser navigated to the "final url" i.e. the redirect URI, so we use a callback named `ShouldOverrideUrlLoading` that gets invoked every time the url changes in the browser. It's normal for that URL to change several times, as the browser collects the username, the password etc. In this particular case, it looks like one of the URL changes is going to "http" which is unexpected. MSAL throws an exception in this case because it is a security concern (after all, you are sending passwords to this url). 

I tried this with AAD and it works fine, no redirect to http occurs. I am wondering if some sort of federation is used and the IDP is redirecting to http? If it is pure ADFS 2019, this is a bug on their side, although we have a lot of customers using MSAL + ADFS 2019 on mobile and this is the first time I see this issue./

A workaround would be to use the system browser - in this case MSAL has not idea of any redirects that occur and will not fail. But the flow should never go to HTTP.

Next steps would be to investigate the identity provider and then for MSAL to add more logging so as to log each url on redirect. Unfortunately this will need to be done on the device log instead of the normal logger, as I don't think we can marshal the logging function to the embedded webview activity as it is a different process.


Note: MSAL.Android logic is [here](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/blob/160936278bfe345e8a79546bf5e87de7192f112d/common/src/main/java/com/microsoft/identity/common/internal/ui/webview/AzureActiveDirectoryWebViewClient.java)

**Comment by janschoelchAtOK** [comment] 2020-07-08 14:53
Thank you very much for the detailed answer and insights, Bogdan! Your detailed logging PR will also help us to investigate further. I will check back with our infrastructure team as they are responsible for the IDP - I'll be back soon ;-)

**Comment by janschoelchAtOK** [comment] 2020-07-09 07:34
@bgavrilMS I pulled `bogavril/more_logs` (your changes will help a lot!) and ran `Microsoft.Identity.Client` locally next to our solution - debugging gave us more info on how the URI is built. Looks like in our test environment there is a redirect to `urn: XXXX` which might be related to federation or integrated Windows authentication (I have close to zero experience with this). We try to investigate the issue further with our infrastructure team, stay tuned.

**Closed** 2020-07-10 12:26 UTC
Labels: Fixed, Investigate, bug, scenario:Mobile-Android

**Comment by janschoelchAtOK** [comment] 2020-07-14 10:08
Just as follow-up and that you know what went wrong: Our infrastructure team indeed found a misconfiguration in their federation infrastructure. Error was completely on our side. Thank you @bgavrilMS for your time investigating and helping me out with the logging. They wouldn't have found the solution so quickly without your ideas!

**Comment by bgavrilMS** [comment] 2020-07-14 11:06
Thank you for following up @janschoelchAtOK , hopefully this will help other people facing the same problem!
