### ISSUE TITLE
[Enhancement] Resolve PKeyAuth Bypass on unsupported platforms for 301 Found Status

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#2026] opened 2020-09-03 16:19 UTC
**Which Version of MSAL are you using ?**
Current

**Platform**

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

**Repro**
Try to sign into an application interactively with a device auth conditional access policy. 

**Expected behavior**
MSAL.NET should try to bypass the PKey auth challenge by returning the generic PKey auth response. 

**Actual behavior**
MSAL does not rty to satisfy the challenge and throws an exception to the user.

**Possible Solution**

**Additional context/ Logs / Screenshots**
Should reach out to conditional access team to ensure we are following the latest specifications

**Comment by henrik-me** [comment] 2020-10-01 17:28
@trwalke : to investigate if is this a general issue based on your findings for Android

**Comment by jmprieur** [comment] 2020-10-15 10:42
@trwalke : do you have anything to share? do we want me to help?

**Comment by jmprieur** [comment] 2020-11-05 10:59
Blocked until we have some performance baseline, as this will impact performance

**Comment by henrik-me** [comment] 2020-12-12 19:30
@trwalke : it this still happening? I thought we had this done?

**Comment by bgavrilMS** [comment] 2020-12-14 10:52
IMO we need to stop advertising PKAuth just to later say "we don't support PKAuth", which is what we do today on a miriad of platforms: 

- UWP
- win32 on Win10
- mobile

**Comment by henrik-me** [comment] 2020-12-15 00:05
+1. I thought that's what was meant. Which platforms are missing?

**Comment by bgavrilMS** [comment] 2020-12-15 11:31
Afaik PKAuth is only supported on Win8 (and the equivalent WinServer). All our .NET framework and .NET core targets (4 of them) can exist there.

**Comment by jmprieur** [comment] 2020-12-15 11:34
I've the same understanding.

**Comment by henrik-me** [comment] 2020-12-15 23:43
@jmprieur @trwalke  copy of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2302 ?

**Comment by jmprieur** [comment] 2020-12-16 13:50
Closing as duplicate of #2302

**Closed by jmprieur** 2020-12-16 13:50 UTC
Labels: P2, duplicate, enhancement
