### ISSUE TITLE
PublicClientApplication constructor throws MissingMethodException exception 

### ISSUE THREAD

**Issue by sergioacortes** [AzureAD/microsoft-authentication-library-for-dotnet#744] opened 2018-12-23 16:06 UTC
**Which Version of ADAL are you using ?**
Microsoft.Identity.Client v.2.6.2

**Which platform has the issue?**
Android 9.0 (Api level 28) and visual studio 2017
iOS 11 and visual studio for mac

**Repro**
```csharp
With a blank xamarin forms project, add the package Microsoft.Identity.Client and create a new instance of the class PublicClientApplication, the result is an exception.

PublicClientApplication = new PublicClientApplication("00000000-0000-0000-0000-000000000000");

Where 00000000-0000-0000-0000-000000000000 -> ClientId

System.MissingMethodException: string[] string.Split(char,System.StringSplitOptions)


**Expected behavior**
The instance of the PublicClientApplication class should be created


**Actual behavior**
Throw exception
System.MissingMethodException: string[] string.Split(char,System.StringSplitOptions)

**Comment by bgavrilMS** [comment] 2018-12-24 12:51
I cannot repro this, I created a new Xamarin Forms app, and added that line to MainPage.xaml.cs in the MainPage() ctor of the shared app. I did not get any exceptions.

I used VS 2017 on a Win10 machine. I don't have acccess to a Mac right now. 

A few questions: 

- do you get this only with VS for Mac?
- Where is your code? In the shared assembly or in the Android / iOS assembly?
- If in shared, what platform is the shared assembly? netstandard2.0 ?

**Comment by narindermakin** [comment] 2018-12-24 20:04
I am having same issue when building with Microsoft.Identity.Client version 2.6.2 on android target. Version 1.1.12-preview008 works fine. 

12-24 14:18:57.775	Asus _Z01BDC	Error	4458	AndroidRuntime	android.runtime.JavaProxyThrowable: System.MissingMethodException: string[] string.Split(char,System.StringSplitOptions)
  at Microsoft.Identity.Client.Instance.Authority.CreateAuthority (Microsoft.Identity.Client.Core.IServiceBundle serviceBundle, System.String authority, System.Boolean validateAuthority) [0x00008] in <3a0d7b9b7b264ca4b01238262ec70e6d>:0 
  at Microsoft.Identity.Client.ClientApplicationBase..ctor (System.String clientId, System.String authority, System.String redirectUri, System.Boolean validateAuthority, Microsoft.Identity.Client.Core.IServiceBundle serviceBundle) [0x00025] in <3a0d7b9b7b264ca4b01238262ec70e6d>:0 
  at Microsoft.Identity.Client.PublicClientApplication..ctor (Microsoft.Identity.Client.Core.IServiceBundle serviceBundle, System.String clientId, System.String authority) [0x0000e] in <3a0d7b9b7b264ca4b01238262ec70e6d>:0 
  at Microsoft.Identity.Client.PublicClientApplication..ctor (System.String clientId, System.String authority) [0x00000] in <3a0d7b9b7b264ca4b01238262ec70e6d>:0 
  at LitMemMobApp.App..ctor () [0x0000f] in <b4a3b93b450546baa78b8933d3977240>:0 
  at LitMemMobApp.Droid.MainActivity.OnCreate (Android.OS.Bundle bundle) [0x00027] in <3532de2ec307448e96d1caf10426dda3>:0 
  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <a10f61e70eeb434e952fef884856c199>:0 
  at (wrapper dynamic-method) System.Object.7(intptr,intptr,intptr)
	at md5c99fffb181a473be865425d825907f19.MainActivity.n_onCreate(Native Method)
	at md5c99fffb181a473be865425d825907f19.MainActivity.onCreate(MainActivity.java:30)
	at android.app.Activity.performCreate(Activity.java:6758)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:159)
	at android.app.ActivityThread.main(ActivityThread.java:6139)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
  Force finishing activity com.lit.personalK/md5c99fffb181a473be865425d825907f19.MainActivity

**Comment by jennyf19** [comment] 2018-12-25 00:08
@narindermakin Thanks for the update. From [msal v.2.0](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/MSAL-v2.0.0) we've had support for embedded webview. I'll take a look at the issue your reported this week.

**Comment by vikram-ma** [comment] 2018-12-26 07:54
I am having same issue when building with Microsoft.Identity.Client version 2.6.2 on iOS target

**Comment by narindermakin** [comment] 2018-12-26 22:34
The issue also exists on iOS target for me too for Microsoft.Identity.Client version 2.6.2. The 1.1.12-preview008 works fine on iOS.
regards,Narinder.
    On Wednesday, December 26, 2018, 2:54:50 AM EST, Vikram.M.A <notifications@github.com> wrote:  
 
 
I am having same issue when building with Microsoft.Identity.Client version 2.6.2 on iOS target

**Comment by jmprieur** [comment] 2018-12-31 14:47
@sergioacortes @vikram-ma @narindermakin : did you add the MSAL.NET NuGet package both on the shared project and the platform specific projects? 
See https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/MSAL.NET-2.6.0-released#msalnet-helps-you-build-multi-platform-applications-more-easily

**Comment by jmprieur** [comment] 2018-12-31 14:47
(close by error)

**Comment by sergioacortes** [comment] 2018-12-31 14:52
I took this sample repo and fails. This sample repo use version 2.6.2
https://github.com/Azure-Samples/active-directory-xamarin-native-v2

Same code with version 2.4.1-preview works fine wth both platforms Android and iOs

Kind regards

**Comment by bukkabalakrishna** [comment] 2018-12-31 20:37
I am facing the below issue when trying to build xamarin ios project with nuget  Microsoft.Identity.Client version 2.6.2 on mac os . I have later tried building the below xamarin forms sample repo and was able to reproduce the issue. 
https://github.com/Azure-Samples/active-directory-b2c-xamarin-native


System.MissingMethodException: string[] string.Split(char,System.StringSplitOptions)
  at Microsoft.Identity.Client.Instance.Authority.CreateAuthority (Microsoft.Identity.Client.Core.IServiceBundle serviceBundle, System.String authority, System.Boolean validateAuthority) [0x00008] in <c9285469658e4d11a60917a7e137979b>:0 
  at Microsoft.Identity.Client.ClientApplicationBase..ctor (System.String clientId, System.String authority, System.String redirectUri, System.Boolean validateAuthority, Microsoft.Identity.Client.Core.IServiceBundle serviceBundle) [0x00025] in <c9285469658e4d11a60917a7e137979b>:0 
  at Microsoft.Identity.Client.PublicClientApplication..ctor (Microsoft.Identity.Client.Core.IServiceBundle serviceBundle, System.String clientId, System.String authority) [0x0000e] in <c9285469658e4d11a60917a7e137979b>:0 
  at Microsoft.Identity.Client.PublicClientApplication..ctor (System.String clientId, System.String authority) [0x00000] in <c9285469658e4d11a60917a7e137979b>:0 
  at NurseLine.Helper.ADB2CImplementaion..ctor () [0x00008] in /Users/balakrishnabukka/Documents/NurseLine/NurseLine/Helper/ADB2CImplementaion.cs:26 
  at NurseLine.iOS.ViewController+<login>d__4.MoveNext () [0x00018] 


Thanks,
Bala.

**Comment by bgavrilMS** [comment] 2019-01-01 16:09
@bukkabalakrishna @sergioacortes @narindermakin @vikram-ma 

1. Are you using Visual Studio 2017 on Windows or Visual Studio on Mac? 
2. Which version of the above? 
3. Which version of xamarin SDK is installed. You can get this by going to VS > About and scrolling down in the installed products 

![image](https://user-images.githubusercontent.com/12273384/50574378-9af31200-0ddf-11e9-9083-892ceaa553cc.png)

**Comment by bgavrilMS** [comment] 2019-01-02 14:44
This issue is a duplicate - https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/745

It looks like there is a bug in the .net fwk or in mono, as String.Split and String.TrimStart are actually available. 

If you use a linker, then you get into issue #745, because the linker does a static analysis of your code to try to remove parts of the framework to reduce app size. The linker fails when it encounters one of the 2 methods above. 

If you don't use a linker, then the app fails at runtime with a MissingMethod exception. 

Current workaround: 

- on Windows, make sure VS is updated to latest version (15.9.4 at time of writing). 
- on VSTS, note that the VSTS Hosted build agent is not up to date and uses a 15.8 version of VS, and encounters this bug. Workaround is to use an on-prem build agent. 
- still investigating on Mac

I'll follow up on this thread with more info and bugs to other teams.

**Comment by bgavrilMS** [comment] 2019-01-02 17:11
I have logged an issue https://github.com/mono/mono/blob/master/mcs/class/referencesource/mscorlib/system/string.cs#L1286 to the Xamarin folks to understand the root cause. 

The current workaround is to update Visual Studio to the latest version (15.9.4 on Windows, 7.7.2 build 21 for VS on Mac)

**Comment by bukkabalakrishna** [comment] 2019-01-02 20:57
@bgavrilMS Updating the vs for mac has fixed the issue. Thanks for your support.

**Comment by bgavrilMS** [comment] 2019-01-02 20:58
Thank you for confirming @bukkabalakrishna !

**Comment by sergioacortes** [comment] 2019-01-03 11:16
Hi @bgavrilMS,

Updated Visual Studio (windows and mac). Now it works on both platforms.

Tanks for your help

Regards

Sergio Antonio Cortés Ocampo

**Comment by bgavrilMS** [comment] 2019-01-09 16:01
Closing, I will update the thread when I hear back from the VSTS folk about hosted build image update

**Closed by bgavrilMS** 2019-01-09 16:01 UTC
Labels: Investigating, external

**Comment by bgavrilMS** [comment] 2019-02-07 14:21
Possible workaround for VSTS https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/852

**Comment by rubit0** [comment] 2020-07-14 20:13
On Unity with the Android Platform this problem is still here:

AndroidPlayer(ADB@127.0.0.1:34999) MissingMethodException: string string.TrimEnd(char)
  at Microsoft.Graph.BaseClient..ctor (System.String baseUrl, Microsoft.Graph.IAuthenticationProvider authenticationProvider, Microsoft.Graph.IHttpProvider httpProvider) [0x00006] in <82276935ca794febb71fef8639d57cdf>:0 
  at Microsoft.Graph.GraphServiceClient..ctor (System.String baseUrl, Microsoft.Graph.IAuthenticationProvider authenticationProvider, Microsoft.Graph.IHttpProvider httpProvider) [0x00000] in <34530de835954671b16f91b30fa2a4ee>:0 
  at Services.MsGraphAuthenticationService.GetAuthenticatedClient () [0x00001] in

Happens with .NET 4.X and .Net Standard 2.0.
