### ISSUE TITLE
[Feature Request] Allow non-interactive authentication using OIDC

### ISSUE THREAD

**Issue by dmprantz** [AzureAD/microsoft-authentication-library-for-dotnet#1312] opened 2019-08-01 02:41 UTC
**Is your feature request related to a problem? Please describe.**
When calling PublicClientApplication.AcquireTokenByUsernamePassword the behaviour is to call the IdP and get a User Assertion using WS-Trust and SAML.  This is not the same behaviour as PublicClientApplication.AcquireTokenInteractive, which uses OIDC directly.  This behaviour is inconsistent and leads to problems in situations where SAML/WS-Trust is not available.  This appears to be a carryover from ADAL.Net where the same logic exists for using UserPasswordCredentials.

**Describe the solution you'd like**
Have PublicClientApplication.AcquireTokenByUsernamePassword call OIDC flows just like PublicClientApplication.AcquireTokenInteractive does, at least with an override option.

**Describe alternatives you've considered**
I tried both MSAL.Net and ADAL.Net, and neither works.  Another option is to roll my own library or customize MSAL.Net.

**Additional context**
Please explain why this decision was made to implement inconsistent behaviour and why it should continue.

**Comment by bgavrilMS** [comment] 2019-08-01 09:38
What IdP do you use that doesn't work? Do you use AAD, ADFS or B2C? If you're using AAD, do you use it with an @outlook account or with a corporate account?

**Comment by dmprantz** [comment] 2019-08-01 11:44
> 
> 
> What IdP do you use that doesn't work? Do you use AAD, ADFS or B2C? If you're using AAD, do you use it with an @outlook account or with a corporate account?

We are using mixed mode AAD and ADFS.  The WS-Trust call goes into ADFS, and fails there.  I do not have control over the ADFS system and have asked the team who does to resolve through reconfiguration, however even if this can be resolved, I fail to see why it makes sense to authenticate using two different approaches depending on the where the password comes from.

**Comment by bgavrilMS** [comment] 2019-08-01 11:47
No I agree, MSAL should behave in a similar way across AAD and ADFS. 

When you say that you use ADFS: 

- is it ADFS 2019?
- do you interact with it directly? Meaning that you when you create the PublicClientApplicaiton object, do you set the authority as being the ADFS url?

**Comment by dmprantz** [comment] 2019-08-01 13:59
> No I agree, MSAL should behave in a similar way across AAD and ADFS.

Good :)

>     * is it ADFS 2019?

No.  ADFS 2016.

>     * do you interact with it directly? Meaning that you when you create the PublicClientApplicaiton object, do you set the authority as being the ADFS url?

PublicClientApplication is configured to use AAD (AzureCloudInstance = AzureCloudInstance.AzurePublic)  I believe the flow is that it looks up the authentication provider using QueryUserRealmDataAsync and then attempts WS-Trust for federated users.  When logging in interactive, users are still redirected to ADFS, but this succeeds.  I don't believe this is performing a WS-Trust lookup, but rather a Forms based authentication.  I guess the underlying issue is that MSAL does not perform Forms Authentication?

**Comment by dmprantz** [comment] 2019-08-01 14:22
I meant to include this article which documents the differences in behaviour.  

https://docs.microsoft.com/bs-latn-ba/azure/active-directory/develop/msal-net-adfs-support

It says it does not support direct communication with ADFS 2016.  Does that mean that my use case is not valid, or is a Federation partner not what is being discussed?  I have the same results (same code) with ADAL.net.

**Comment by bgavrilMS** [comment] 2019-08-01 14:34
No, it is a valid use case. If you set your authority to AAD (which you do), then AAD will federate the flows to your ADFS. 

In fact we even have integration tests for the ROPC flow for ADFS 2016 (UsernamePassword): 
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/b6cda49edbba9bb88f380ddf0b7e482e0bc727f9/tests/Microsoft.Identity.Test.Integration.net45/HeadlessTests/UsernamePasswordIntegrationTests.cs#L46

and 

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/b6cda49edbba9bb88f380ddf0b7e482e0bc727f9/tests/Microsoft.Identity.Test.Integration.net45/HeadlessTests/UsernamePasswordIntegrationTests.cs#L53

I don't fully understand why the ROPC grant is implement in a non standard way, but looking at the code I can see that: 

- if the user is "federated" (this is your case i.e. the ADFS via AAD case), then use a WS-Trust flow. I believe it is because with WS-Trust you don't actually need to give us the password, just the username.

- if the user is managed (pure AAD), the we will perform the standard compliant ROPC flow.

@rayluo @henrik-me @jmprieur  - comments on this?


Back to your issue - why isn't WS-Trust working? What error are you getting?

**Comment by dmprantz** [comment] 2019-08-01 16:22
>     Back to your issue - why isn't WS-Trust working? What error are you getting?

I am seeing two different issues, and I JUST figured out why the disparity, and it's due to internal DNS issues.  Let's skip the first issue itself, except for the potential bug that it uncovered:

"internal async Task<WsTrustResponse> GetWsTrustResponseAsync" sometimes returns a null.  When I force this to happen, I see that Authentication is failing with "MSIS7068: Access denied."  The null is returned from inside of Microsoft.Identity.Client.WsTrust.WsTrustResponse.CreateFromResponseDocument.  Since a null is being returned, the line after which attempts to log with a property of the null object gets a null reference exception.  This would appear to me to be a bug:  If NULL is a valid return value, the application should handle it gracefully.  If it's not a valid return value, then it should return a different value.  As it is, it's swallowing the underlying cause, which is the MSIS7068 above, and I lost time trying to find that information.

The other issue is that I get "AADSTS53000: Device is not in required device state: compliant." as a response.  This appears to happen when a valid (???) ADFS SAML WS-Trust Token is passed into AAD, so I am guessing that it is an AAD option related to my workstation, but my underlying point is that I can do this interactively just fine.  I pass in stored values, and the different flow doesn't work.

**Comment by trwalke** [comment] 2019-09-04 17:32
Hi @dmprantz, it looks like your ADFS instance is using conditional access policies to ensure device compliance based on the error you are getting back. However, the user name and password flow is not supported in environments with conditional access policies which is why you are getting the "Device is not in required device state: compliant" error instead of a successful sign in. [please see our wiki for more details](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Username-Password-Authentication). 

As bgavrilMS mentioned earlier, we perform WS-trust when the user account is considered federated. The reason we do this is because not all federated accounts will be able to perform OIDC to authenticate. (certain versions of ADFS do not support OIDC for example). 
Is there a reason that you need to use the username and password flow?
Are there any other authentication flows that you can use to resolve your issue? The reason I ask is because we typically do not recommend using the username password flow due to security concerns.

**Comment by dmprantz** [comment] 2019-09-04 18:28
Thank you @trwalke.  Since opening this, I have found much of the same information you describe.  CA Policy is preventing the authentication, and I have a note from MS that it is not supported to have a daemon authenticate as a user where CA is enabled.  I traced the code pretty closely to see that interactive login launches a browser which uses Forms, and is why you can authenticate with one vs the other, which is blocked as a thick client.  I left this ticket open in case there was an option I hadn't yet found, but our options at this point appear to be to either use the Client Credential Flow, or to stop using this CA Policy in some situations.

Username/password authentication seemed to be the most logical because the application currently uses that uid and password.  Switching to Client Crediential Flow is a new direction that I haven't tried before, where the Application can request a token and then open a mailbox on behalf of a specific user.  It requires R&D and potentially more code changes to implement.  (Do you have specific documentaton for that with either EWS or Graph?)  Frankly, I'm not sold that Client Credential is natively any more secure than user ID / password - You are just calling the User ID an AppID, and the password an App Secret.  Client Credentials have the ability to use certificates, but this just means that users should have the same capability to authenticate with certificates, and since the use of app secrets is not prohibited, it's not any more secure, just more complicated.  Thanks for the further confirmation.

**Comment by trwalke** [comment] 2019-09-04 20:08
@dmprantz We have documentation here that describes how to sign users to a service and then call other services with the user signed in. [MSAL Confidential Client sample](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/b96af3b62e8fb9eab8a0434c9ed0c7a5624078f6) 

In regards to your comments on the security of confidential clients, public clients are designed for applications that are distributed publicly and will run anywhere. Because of this, there is very little guarantee that something isnt gathering these credentials. These apps should try to minimize the instances in which passwords are entered directly into the app which is why we do not recommend username password flow. Alternatively, confidential clients are applications designed to run in a secure environment in which only an admin will have access, such as a back end web service. It is the responsibility of the admins ensure these applications are protected. So you are technically correct, however, in practice, server admins will have more control over the security of the environment to ensure secrets are stored safely. There is no way for admins to ensure the safety of credentials entered into public clients.

**Comment by dmprantz** [comment] 2019-09-04 20:33
I believe you have misunderstood my issue.  I do not want to authenticate on behalf of a live user.  I want a daemon to authenticate as a user.  I used the daemon sample, but it is not compatible with CA.  

I understand the difference between public and confidential apps, but, it's not really relavent.  It helps to explain the concept, but this is the same as it was with Adal.Net which didn’t differentiate like that.  I am looking to have an application to login with a UserID and password.  I would love to use MSI, but it is not compatible.  I would love to leverage user authentication with a certificate or key like ssh, but it is not possible.  My only option appears to be to redesign the application to use an app ID, under then implication that it is more secure, but when used with an App Secret when it is not.  I looked at samples and could not find one for this.

It's security through obscurity anyway.

**Comment by trwalke** [comment] 2019-09-04 21:13
I am not familiar with the scenario where you would want a daemon app to sign in as a user as opposed to on behalf of. 
Is this a scenario that you have working with ADAL?
@jmprieur are you familiar with this? Perhaps you can provide some insight as to how to achieve this or provide a different solution to solve this problem?

@dmprantz do you have any additional details on your scenario? The more info we have the better we can help.

While ADAL did not differentiate application types in the api like MSAL does, the underlying authentication flows are identical with MSAL having additional flows to handle new scenarios. Therefore, the scenarios you have with MSAL should be the same as what you had with ADAL except for a few changes we made to make authentication more secure (e.g. no longer exposing refresh tokens in MSAL).

Also, We are not sure how much our customers know about identity and oauth so I just like to add more details when I can.

**Comment by rayluo** [comment] 2019-09-04 22:46
@dmprantz, I think you are right about your following comment in bold:
> Frankly, I'm not sold that Client Credential is natively any more secure than user ID / password - **You are just calling the User ID an AppID, and the password an App Secret**. Client Credentials have the ability to use certificates, but this just means that users should have the same capability to authenticate with certificates, and since the use of app secrets is not prohibited, it's not any more secure, just more complicated.

It is true that the AppID and App Secret are just the "username and password" of that app. So, an app secret itself is not cryptographically more secure than an end user password. It is NOT about "security through obscurity", either. The real difference, is about the stake protected by such a password or secret. If your daemon app somehow possesses the end user's username and password, now from an authentication standpoint, your app BECOMES that user, and can gain access to EVERY information that end user owns. That defeats the purpose of the fine-grained consent framework which is the whole point of OAuth2. That's why we recommend using other flows whenever possible (more on this later). Also, if your daemon persists end user's password, it becomes an even-bigger potential risk. On the contrary, [an app authenticating as a confidential client, which acquires token for itself (rather than as any end user)](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Client-credential-flows), is expected to be granted (by admin) to access the minimal amount of information that it was designed to operate on.

Changing your app from using username password flow to confidential client, this adjustment alone may or may not solve your problem. If your daemon has to access some info belongs to one (or many) end users, and therefore need their consents, you will have to look into one of those flows that acquire a token for end user. Your options are:

* Username password flow. It is mentioned here for the sake of completeness, though it is not recommended and often limited (by such as those CA policies).
* Integrated Windows Auth, [if you can](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Integrated-Windows-Authentication#constraints).
* Interactive flow initially, and then use the refresh token that came after the initial authorization. This can either be a public client running on end user's desktop, or a confidential client running on a server in your control (though you would need to change your app's architecture to become a web app).
* You can probably take a look into the less well-known Device Flow. Your app does NOT even need to be a web app, so it might be more close to what you currently have, though (initial) end user interaction would still be needed.

**Comment by jmprieur** [comment] 2019-09-05 11:40
@dmprantz : do I understand that you'd like your application to use OBO with service principal? (that is OBO but with an application instead of a user?)
daemon applications, as @rayluo explained are about getting access to Web apis on behalf of the app itself, not of a user, and therefore daemons have access to informations for several/many users.

Can you please describe the architecture of your application you'd want (See https://docs.microsoft.com/en-us/azure/active-directory/develop/authentication-flows-app-scenarios for the supported architectures)
Also can you elaborate on how you'd want to use SSH. cc: @bgavrilMS @henrik-me

**Comment by dmprantz** [comment] 2019-09-05 14:24
> It is NOT about "security through obscurity", either. 

My point here was not clearly explained.  The "obscurity" is in the web-based authentication mechanism.  It seems that a person with enough motivation and time could emulate the HTTP calls that are required for web authentication and login with an HttpClient, thus defeating the "obscurity" introduced by requiring a Web Forms Login and differentiating between Web and thick client logins.


> The real difference, is about the stake protected by such a password or secret. If your daemon app somehow possesses the end user's username and password, now from an authentication standpoint, your app BECOMES that user, and can gain access to EVERY information that end user owns. That defeats the purpose of the fine-grained consent framework which is the whole point of OAuth2.

I understand.  In this case, we expect the daemon to have that access.  The account is an eMail only account, and we need to access EWS.  It's where "recommendation" becomes "We are going to force you" that problems can arise.

  
> Your options are

What about the Client Credentials Flow?  This seems to be where I am.  Short of removing CA, the only option appears to be "authenticating" as the application (MSI could be used), and then request a token which tells EWS that the daemon can interact as that user.  I haven't yet looked to see if delegated authority (Send As) can be granted to Service Principals.  I spent too much time yesterday looking for the EWS scopes, and while I found a JSON document which defines o365 Exchange Online scopes, it does not have EWS scopes.

Several people have said that by authenticating as an app we can bypass CA and eventually access the mailbox through EWS, but I have yet to see an example for how to do that.  Any advice would be appreciated.

**Comment by dmprantz** [comment] 2019-09-05 14:35
> Can you please describe the architecture of your application you'd want 

I don't believe the use case is a particularly unsual nor difficult one.  I have a daemon process (not run in a user session) which is required to send and receive mail as a specific user using Exchange Web Services (EWS).  We can login directly to EWS with UserID and Password of the user sending the eMails, but we would like to authenticate to EWS with an OAuth token instead.  This is supported by EWS and has been tested using interactive login of that user.  When we we request the OAuth token in an unattended state, using the same UserID and Password, it fails due to CA.

The story I am getting is that with CA enabled, we cannot use a userid and password to request an OAuth token for EWS.  I understand why it is felt that it is not a good idea, but it is an intermediary phase for us.  What is the solution for this use case which does not require repetitive user intervention to cache a token?

It sounds like this issue is not going to resolved.  The team is comfortable not allowing this in this case, however we do not appear to be able to proceed, and this may be a serious issue for existing applications when o365 disables Basic Auth.

**Comment by henrik-me** [comment] 2019-09-05 16:43
@dmprantz : This is interesting. Out of the box I don't believe we have a better option than the obo flow for your scenario. You will somehow need to have the end-user involved in the initial flow to be able to do consent. I'm not familiar enough with EWS to say what is possible and not possible in terms of delegated permissions however that is potentially what is needed. I currently only see obo (potentially with the option for admin consent) and an app specific approach where the user is not involved at all. Depending on your CA policy even the above may be challenging. 
I believe we understand your scenario but I also recognize that we don't have a good answer for you.

**Comment by dmprantz** [comment] 2019-09-05 16:48
> @dmprantz : This is interesting. Out of the box I don't believe we have a better option than the obo flow for your scenario.

> I believe we understand your scenario but I also recognize that we don't have a good answer for you.

Thank you.  That is the reason for this feature request.  I would be interested in knowing if there is a solution developed ultimately.  I will continue to investigate three options which have arisen here:  OBO, Client, or removing CA.

**Comment by jmprieur** [comment] 2019-09-23 07:42
@trwalke : I think you've been investigating this one. Would there be a fix in 4.4.1?

**Comment by trwalke** [comment] 2019-09-23 17:14
@jmprieur no fix for MSAL as it is performing the correct flow.

**Comment by jmprieur** [comment] 2019-09-23 17:52
and we are fixing ADAL.

**Comment by jmprieur** [comment] 2019-09-23 17:52
Closing as the is ADAL.NET that needs to be fixed (and we are doing it in the next release)

**Closed by jmprieur** 2019-09-23 17:52 UTC
Labels: Feature Request, enhancement

**Comment by dmprantz** [comment] 2019-09-24 19:54
> 
> 
> Closing as the is ADAL.NET that needs to be fixed (and we are doing it in the next release)

@jmprieur will you please point me to the "fix" which is going to be included in ADAL.Net?

**Comment by jmprieur** [comment] 2019-09-25 03:48
@trwalke 
cc; @henrik-me

**Comment by dmprantz** [comment] 2019-09-30 20:28
@trwalke, @henrik-me, @jmprieur:  Thank you all for your support on this issue, but our current resolution is only temporary.  You mentioned that this would be "fixed" in ADAL.  Will one of you please point me to the specific issue that is going to be "fixed" so that we can track it, analyze it, and determine if it will fit our needs?  Thanks again!

**Comment by trwalke** [comment] 2019-09-30 20:42
What was said earlier about the fix in ADAL was a mistake as the fixes added to ADAL were not related to this exactly. Currently, ADAL behaves the same way as MSAL does today and it is in alignment with how our other platforms behave. ROPC will perform OIDC for managed cloud accounts and WSTrust for federated accounts.

**Comment by dmprantz** [comment] 2019-09-30 20:47
> 
> 
> ROPC will perform OIDC for managed cloud accounts and WSTrust for federated accounts.

Thank you for the update.  We will continue to have the issue that that using WSTrust triggers CA Policy, and there is currently no solution to implement this within MSAL or ADAL.  Is it possible to have this added as a feature request, or is the position that you do not wish to add it?
