### ISSUE TITLE
Spike - implement DownstreamRestApi for a fictitious RP which supports POP (in public client world).

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#3713] opened 2022-09-28 17:47 UTC

**Comment by bgavrilMS** [comment] 2022-12-21 10:10
Closing as duplicate of [3237](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3237)

**Closed by bgavrilMS** 2022-12-21 10:10 UTC
