### ISSUE TITLE
[Bug] [Xamarin.iOS] Sign in with Apple is sometimes failing with error code AADB2C90289

### ISSUE THREAD

**Issue by kevcrooks** [AzureAD/microsoft-authentication-library-for-dotnet#2326] opened 2021-01-07 09:29 UTC
We have set up a "Sign in with Apple" user flow in B2C, and are using this from our client app with msal.

We do the same for multiple other sign-in methods, all of which are working fine. Furthermore "Sign in with Apple" is working fine for us, both in Debug mode and in TestFlight, but our app has been rejected multiple times during Apple review, with an error signing in.

We have a log of the error, but don't understand why this is failing only some of the time. I understand from related posts (e.g. https://github.com/azure-ad-b2c/samples/issues/104#issuecomment-678608721) that this error might be caused if the client *secret* was incorrect, but this should cause the sign-in to always fail. 

I've also refreshed the client secret, and this hasn't changed anything - the sign in still works for us, and is rejected by Apple.

**Error and stack trace
`Microsoft.Identity.Client.MsalServiceException: AADB2C90289: We encountered an error connecting to the identity provider. Please try again later. Correlation ID: 708958a3-ab9e-43a5-aa5e-ccf0f7535cee Timestamp: 2021-01-06 19:42:20Z`

```
Microsoft.Identity.Client.Internal
AuthCodeRequestComponent.VerifyAuthorizationResult (Microsoft.Identity.Client.UI.AuthorizationResult authorizationResult, System.String originalState)
Microsoft.Identity.Client.Internal
AuthCodeRequestComponent.FetchAuthCodeAndPkceInternalAsync (Microsoft.Identity.Client.UI.IWebUI webUi, System.Threading.CancellationToken cancellationToken)
Microsoft.Identity.Client.Internal
AuthCodeRequestComponent.FetchAuthCodeAndPkceVerifierAsync (System.Threading.CancellationToken cancellationToken)
Microsoft.Identity.Client.Internal.Requests
InteractiveRequest.GetTokenResponseAsync (System.Threading.CancellationToken cancellationToken)
Microsoft.Identity.Client.Internal.Requests
InteractiveRequest.ExecuteAsync (System.Threading.CancellationToken cancellationToken)
Microsoft.Identity.Client.Internal.Requests
RequestBase.RunAsync (System.Threading.CancellationToken cancellationToken)
Microsoft.Identity.Client.ApiConfig.Executors
PublicClientExecutor.ExecuteAsync (Microsoft.Identity.Client.ApiConfig.Parameters.AcquireTokenCommonParameters commonParameters, Microsoft.Identity.Client.ApiConfig.Parameters.AcquireTokenInteractiveParameters interactiveParameters, System.Threading.CancellationToken cancellationToken)
FSharp.Control.Tasks
TaskBuilder+bindTask@121[b,a].Invoke (Microsoft.FSharp.Core.Unit unitVar0)
FSharp.Control.Tasks
TaskBuilder.tryWith[a] (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] step, Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] catch)
```

This is an existing app that has previously been approved by Apple, but because we're not able to reproduce the failure locally, we don't have any ideas of how to diagnose or fix. Is there anything that could cause this exception only on some devices or some sign-ins - or any suggestions to diagnose/fix? Because of the error, it's not clear to us if we should look at the user flow, our use of msal to call the user flow, or the configuration in our Apple account?

**Comment by jmprieur** [comment] 2021-01-07 09:37
@kevcrooks: Is this a duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2296

**Comment by kevcrooks** [comment] 2021-01-07 09:44
@jmprieur it looks like that issue is when cancelling sign-in, whereas we understand from the Apple review that they are attempting to sign in, without cancelling - and the sign in is failing for them. We've asked Apple for some more information, but as we're not able to reproduce the problem ourselves, we only have the error message - which should be happening after a successful sign-in.

**Comment by charlesroddie** [comment] 2021-01-07 11:58
This is addditional information on https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2318

I will transfer the info

**Comment by charlesroddie** [comment] 2021-01-07 11:59
@kevcrooks  can you close this one

**Closed** 2021-01-07 12:00 UTC
Labels: B2C, Service Issue
