### ISSUE TITLE
[Bug] MSAL not working with MAUI in iOS

### ISSUE THREAD

**Issue by chrfin** [AzureAD/microsoft-authentication-library-for-dotnet#3093] opened 2022-01-07 11:41 UTC
**Logs and network traces**
https://pastebin.com/B7ux36cs (anonymized)
and then
https://pastebin.com/1tJTqDWE

**Which version of MSAL.NET are you using?**
Microsoft.Identity.Client 4.39.0

**Platform**
.NET MAUI preview 11 running on iOS

**What authentication flow has the issue?**
* Desktop / Mobile
    * [X] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

**Is this a new or existing app?**
This is a new app, but the same code does work in Xamarin.Forms/.iOS.

**Repro**

Create a .NET MAUI app from the default template, add MSAL and try to log in with AAD B2C.
I use the following code to bootstrap MSAL:
```
AuthClient = PublicClientApplicationBuilder.Create(AuthConstants.ClientId)
		.WithIosKeychainSecurityGroup(AuthConstants.IosKeychainSecurityGroups)
		.WithB2CAuthority($"{AuthConstants.Authority}{AuthConstants.SigninPolicy}")
		.WithRedirectUri($"msal{AuthConstants.ClientId}://auth")
		.Build();
```
and
```
var result = await AuthClient
				.AcquireTokenInteractive(AuthConstants.DefaultScopes)
				.WithPrompt(Prompt.SelectAccount)
				.WithUseEmbeddedWebView(true)
				.ExecuteAsync().ConfigureAwait(false);
```

**Expected behavior**
To get a `AuthenticationResult` like on Windows/Android.

**Actual behavior**
Browser is closed and the debug log logs the attached exception and no user is logged in. 

**Additional context / logs / screenshots / links to code**

**Comment by SameerK-MSFT** [comment] 2022-01-07 22:17
We are not supporting MAUI yet. Marked as Bug. So will keep on the radar.

**Comment by chrfin** [comment] 2022-01-07 22:18
Any ETA for official support?

**Comment by bgavrilMS** [comment] 2022-01-10 12:58
@chrfin - what is the target framework that you used ? This seems like an HttpClient bug. 

@SameerK-MSFT, @trwalke @pmaytak - I thought we tested Android and iOS with MAUI and it worked.

**Comment by chrfin** [comment] 2022-01-10 19:56
@bgavrilMS With a new `HttpClient` it seems to be working for that problem, but I'm getting new errors, e.g.:

> \[0:\] Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSRangeException Reason: \*\*\* -\[\_\_NSArrayM objectAtIndex:\]: index 4614066048 beyond bounds \[0 .. 0\]  
> Native stack trace:  
> 0   CoreFoundation                      0x00007fff203feba4 \_\_exceptionPreprocess + 242  
> 1   libobjc.A.dylib                     0x00007fff201a1be7 objc\_exception\_throw + 48  
> 2   CoreFoundation                      0x00007fff2047ef64 \_CFThrowFormattedException + 194  
> 3   CoreFoundation                      0x00007fff202fa29b -\[\_\_NSArrayM getObjects:range:\] + 0  
> 4   libxamarin-dotnet-debug.dylib       0x000000010b9406f9 xamarin\_dyn\_objc\_msgSend + 217  
> 5   libmonosgen-2.0.dylib               0x000000010ca43ac4 do\_icall + 276  
> 6   libmonosgen-2.0.dylib               0x000000010ca42a8d do\_icall\_wrapper + 253  
> 7   libmonosgen-2.0.dylib               0x000000010ca34caa interp\_exec\_method + 2970  
> 8   libmonosgen-2.0.dylib               0x000000010ca32f2f interp\_runtime\_invoke + 239  
> 9   libmonosgen-2.0.dylib               0x000000010c92acbb mono\_jit\_runtime\_invoke + 1227  
> 10  libmonosgen-2.0.dylib               0x000000010c84d438 mono\_runtime\_invoke\_checked + 136  
> 11  libmonosgen-2.0.dylib               0x000000010c865a55 start\_wrapper\_internal + 613  
> 12  libmonosgen-2.0.dylib               0x000000010c8657ce start\_wrapper + 62  
> 13  libsystem\_pthread.dylib             0x00007fff6da324f4 \_pthread\_start + 125  
> 14  libsystem\_pthread.dylib             0x00007fff6da2e00f thread\_start + 15
> 
>   at ObjCRuntime.Runtime.ThrowNSException(IntPtr ns\_exception)  
>   at ObjCRuntime.Runtime.throw\_ns\_exception(IntPtr exc)  
>   at Foundation.NSArray.GetAtIndex(IntPtr handle, nuint i)  
>   at Foundation.NSArray.ArrayFromHandleFunc\[SecRecord\](IntPtr handle, Func\`2 createObject)  
>   at Security.SecKeyChain.QueryAsRecord(SecRecord query, Int32 max, SecStatusCode& result)  
>   at Microsoft.Identity.Client.Platforms.iOS.iOSTokenCacheAccessor.GetPayloadAsString(Int32 type)  
>   at Microsoft.Identity.Client.Platforms.iOS.iOSTokenCacheAccessor.GetAllRefreshTokens(String optionalPartitionKey)  
>   at Microsoft.Identity.Client.TokenCache.GetAllRefreshTokensWithNoLocks(Boolean filterByClientId, String partitionKey)  
>   at Microsoft.Identity.Client.TokenCache.Microsoft.Identity.Client.ITokenCacheInternal.GetAccountsAsync(AuthenticationRequestParameters requestParameters)  
>   at Foundation.NSArray.GetAtIndex(IntPtr handle, nuint i)  
>   at Foundation.NSArray.ArrayFromHandleFunc\[SecRecord\](IntPtr handle, Func\`2 createObject)  
>   at Security.SecKeyChain.QueryAsRecord(SecRecord query, Int32 max, SecStatusCode& result)  
>   at Microsoft.Identity.Client.Platforms.iOS.iOSTokenCacheAccessor.GetPayloadAsString(Int32 type)  
>   at Microsoft.Identity.Client.Platforms.iOS.iOSTokenCacheAccessor.GetAllRefreshTokens(String optionalPartitionKey)  
>   at Microsoft.Identity.Client.TokenCache.GetAllRefreshTokensWithNoLocks(Boolean filterByClientId, String partitionKey)  
>   at Microsoft.Identity.Client.TokenCache.Microsoft.Identity.Client.ITokenCacheInternal.GetAccountsAsync(AuthenticationRequestParameters requestParameters)  
>   at Microsoft.Identity.Client.Cache.CacheSessionManager.GetAccountsAsync()  
>   at Microsoft.Identity.Client.ClientApplicationBase.GetAccountsInternalAsync(ApiIds apiId, String homeAccountIdFilter, CancellationToken cancellationToken)  
>   at Microsoft.Identity.Client.ClientApplicationBase.GetAccountsAsync(CancellationToken cancellationToken)  
>   at Microsoft.Identity.Client.ClientApplicationBase.GetAccountsAsync()  
>   at MyAPP.Authentication.Auth.GetTokenSilentAsync(String scope) 0   CoreFoundation                      0x00007fff203feba4 \_\_exceptionPreprocess + 242  
> 1   libobjc.A.dylib                     0x00007fff201a1be7 objc\_exception\_throw + 48  
> 2   CoreFoundation                      0x00007fff2047ef64 \_CFThrowFormattedException + 194  
> 3   CoreFoundation                      0x00007fff202fa29b -\[\_\_NSArrayM getObjects:range:\] + 0  
> 4   libxamarin-dotnet-debug.dylib       0x000000010b9406f9 xamarin\_dyn\_objc\_msgSend + 217  
> 5   libmonosgen-2.0.dylib               0x000000010ca43ac4 do\_icall + 276  
> 6   libmonosgen-2.0.dylib               0x000000010ca42a8d do\_icall\_wrapper + 253  
> 7   libmonosgen-2.0.dylib               0x000000010ca34caa interp\_exec\_method + 2970  
> 8   libmonosgen-2.0.dylib               0x000000010ca32f2f interp\_runtime\_invoke + 239  
> 9   libmonosgen-2.0.dylib               0x000000010c92acbb mono\_jit\_runtime\_invoke + 1227  
> 10  libmonosgen-2.0.dylib               0x000000010c84d438 mono\_runtime\_invoke\_checked + 136  
> 11  libmonosgen-2.0.dylib               0x000000010c865a55 start\_wrapper\_internal + 613  
> 12  libmonosgen-2.0.dylib               0x000000010c8657ce start\_wrapper + 62  
> 13  libsystem\_pthread.dylib             0x00007fff6da324f4 \_pthread\_start + 125  
> 14  libsystem\_pthread.dylib             0x00007fff6da2e00f thread\_start + 15

**Comment by chrfin** [comment] 2022-01-21 08:06
@bgavrilMS I just updated to MAUI preview 12 and now it does not compile anymore, as it does not find \`**AuthenticationContinuationHelper\`**.

I guess this is because MAUI does not support the Xamarin.iOS TFMs anymore (see [here](https://github.com/xamarin/xamarin-macios/issues/13087)) and uses another more common one, which does not have this class.

**Comment by chrfin** [comment] 2022-02-17 09:25
@bgavrilMS Any update on this? v4.41 still has no net6.0-ios TFM... 😢

**Comment by bgavrilMS** [comment] 2022-02-17 10:21
No, we are not working on this right now. We are waiting for a the net6.0-ios breaking changes to stabilize first. We will pick this up in a few weeks. Our goal is to get all of this working by May.

**Comment by chrfin** [comment] 2022-02-17 10:31
Thank you for the update. I will finish the Android version of the app first to get something out to testers and then look into iOS again and see if I'm able to contribute something 😊.

**Comment by bgavrilMS** [comment] 2022-04-04 15:07
Closing as duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3127

**Closed by bgavrilMS** 2022-04-04 15:07 UTC
Labels: bug, MAUI
