### ISSUE TITLE
ArgumentNullException on IOS if AccessToken is NULL

### ISSUE THREAD

**Issue by AlexSchuetz** [AzureAD/microsoft-authentication-library-for-dotnet#662] opened 2018-10-29 15:09 UTC
**Which Version of MSAL are you using ?**
Microsoft.Identity.Client v2.2.1-preview

**Which platform has the issue?**
xamarin iOS

**What authentication flow has the issue?**
* Desktop 
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username / Password
    * [ ] Device code flow (browserless)
* Mobile
    * [x] Xamarin.iOS
    * [ ] Xamarin.Android
    * [ ] UWP
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO
* Daemon App
    * [ ] Client credentials
    
**What is the identity provider ?**
* [ ] Azure AD
* [x] Azure AD B2C

If B2C, what social identity did you use?
Google

**Repro**

Trying to authenticate against a B2C-Tenant with google as IdentityProvider.
I am using `https://login.microsoftonline.com/tfe/<mytenant>/<my_policy>` as authority.

On android everything works as expected. On IOS I get a ArgumentNullException after specifying my google account:

Inspecting the AuthenticationResult on android I saw that the AccessToken is NULL. I don't know if this may be a vaild scenario or just a badly configured B2C tenant, but this is causing a NPE on IOS.

**Expected behavior**
Return the AuthenticationResult with AccessToken = NULL.

**Actual behavior**
The following exception is thrown:

```
System.ArgumentNullException: "Value cannot be null.\nParameter name: str"
  at Foundation.NSString..ctor (System.String str) [0x00009] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/Foundation/NSString.cs:139 
  at Foundation.NSData.FromString (System.String s, Foundation.NSStringEncoding encoding) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/Foundation/NSData.cs:208 
  at Foundation.NSData.op_Implicit (System.String s) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/Foundation/NSData.cs:214 
  at Microsoft.Identity.Core.TokenCacheAccessor.CreateRecord (System.String account, System.String service, System.String generic, System.Int32 type, System.String value) [0x00014] in <f077f6b3700d43e3adf74b7a06b732ac>:0 
  at Microsoft.Identity.Core.TokenCacheAccessor.Save (System.String account, System.String service, System.String generic, System.Int32 type, System.String value) [0x00000] in <f077f6b3700d43e3adf74b7a06b732ac>:0 
  at Microsoft.Identity.Core.TokenCacheAccessor.SaveAccount (Microsoft.Identity.Core.Cache.MsalAccountCacheItem item) [0x00033] in <f077f6b3700d43e3adf74b7a06b732ac>:0 
  at Microsoft.Identity.Core.Telemetry.TelemetryTokenCacheAccessor.SaveAccount (Microsoft.Identity.Core.Cache.MsalAccountCacheItem item, Microsoft.Identity.Core.RequestContext requestContext) [0x0001f] in <f077f6b3700d43e3adf74b7a06b732ac>:0 
  at Microsoft.Identity.Client.TokenCache.SaveAccessAndRefreshToken (Microsoft.Identity.Core.CorePlatformInformationBase platformInformation, Microsoft.Identity.Client.Internal.Requests.AuthenticationRequestParameters requestParams, Microsoft.Identity.Core.OAuth2.MsalTokenResponse response) [0x00179] in <f077f6b3700d43e3adf74b7a06b732ac>:0 
  at Microsoft.Identity.Client.Internal.Requests.RequestBase.SaveTokenResponseToCache () [0x00197] in <f077f6b3700d43e3adf74b7a06b732ac>:0 
  at Microsoft.Identity.Client.Internal.Requests.RequestBase.PostTokenRequest (System.Threading.CancellationToken cancellationToken) [0x00008] in <f077f6b3700d43e3adf74b7a06b732ac>:0 
  at Microsoft.Identity.Client.Internal.Requests.RequestBase+<RunAsync>d__49.MoveNext () [0x00378] in <f077f6b3700d43e3adf74b7a06b732ac>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:535 
  at Microsoft.Identity.Client.PublicClientApplication+<AcquireTokenForLoginHintCommonAsync>d__22.MoveNext () [0x00101] in <f077f6b3700d43e3adf74b7a06b732ac>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:535 
  at Microsoft.Identity.Client.PublicClientApplication+<AcquireTokenAsync>d__14.MoveNext () [0x000a1] in <f077f6b3700d43e3adf74b7a06b732ac>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:357 
...
```

**Comment by henrik-me** [comment] 2018-11-02 20:44
@AlexSchuetz : It is not expected that you get null back if the B2C tenant is setup correctly. 

It seems like the authority format you are using is fine. 
"https://login.microsoftonline.com/tfp/{Tenant}/{PolicySignUpSignIn}"

It seems relevant to examine your setup. I just validated our sample here with a google account and that works fine. Does the sample work for you (with and with-out your own Authority)?

**Comment by AlexSchuetz** [comment] 2018-11-02 21:15
As far as I know to get an Accesstoken you have to request a resource.

But there is none configured yet.

However on Android I get an AuthenticationResult with an Id-token. So it
doesn't seem right to drop that Id-token on IOS.

Maybe no resource is needed, since authentication and claims are
sufficient. Seems to be a supported scenario by B2C and should therefore
also be supported by msal.

Am Fr., 2. Nov. 2018, 22:00 hat henrikm <notifications@github.com>
geschrieben:

**Comment by henrik-me** [comment] 2018-11-02 21:38
@AlexSchuetz : Interestingly enough though this sample works for me:
https://github.com/Azure-Samples/active-directory-b2c-dotnet-uwp

Sure you need to have a resource/scope to get an AT. 

What would be your scenario for not having a scope?

**Comment by henrik-me** [comment] 2018-11-02 21:52
@AlexSchuetz 
I just cleared the cache for my account in the sample, and now it works. I'm no longer able to reproduce the error I saw initially.

Please validate using a scope.

**Comment by AlexSchuetz** [comment] 2018-11-02 21:55
I am not having a scenario. I just stumbled over it during the process of
registering my native in a b2c administrating by the customer.

Nevertheless: if the app doesn't use a resource, but needs authentication
would be one scenario.

Am Fr., 2. Nov. 2018, 22:38 hat henrikm <notifications@github.com>
geschrieben:

**Comment by henrik-me** [comment] 2018-11-02 21:59
I believe for no resource you should use the client id. Will need to validate this though. 
In most cases the API/service you are protected is registered and thus you will be able specify the scope.

**Comment by AlexSchuetz** [comment] 2018-11-02 22:10
I remember specifying the client ID as scope raised exceptions well.

Sending no scope is the use case and at least works on android. I don't know about UWP.

On IOS an ANE is thrown. This is not meaningful. Looking at the stacktrace and the sources it seems to be a missing null check.

**Comment by henrik-me** [comment] 2018-11-03 00:51
Thanks. We will look into it.

**Comment by jennyf19** [comment] 2018-11-05 23:47
@AlexSchuetz Have you tried with [2.3.1-preview](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/MSAL-v2.3.1)? 
Which AcquireToken method are you using?

**Comment by jennyf19** [comment] 2018-11-08 18:57
@SravanthiKare - Can you share your acquire token call w/the overloads you are using? 
Also, did you set up the [UIParent](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Acquiring-tokens-interactively#controlling-the-location-of-the-dialog-with-the-parent-parameters-uiparent)?
If you want, you can email me the [MSAL logs](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging#sample-for-logging-in-msal-2x). - jeferrie@microsoft.com

**Comment by jennyf19** [comment] 2018-11-09 01:57
@AlexSchuetz @SravanthiKare - This is fixed in our next release.

**Comment by SravanthiKare** [comment] 2018-11-09 02:46
@jennyf19 
AccesToken Call - App.PCA.AcquireTokenAsync(B2CConstants.Scopes, LoginHelper.GetUserByPolicy(accounts, B2CConstants.PolicySignUpSignIn), App.UiParent)

I am setting up UIParent in iOS AppDelegate.cs class.
App.UiParent = new UIParent();

Can you please let me know the release date for 2.4.0-preview. We are planning to release our app in mid of November, but we are blocked with this issue. We have been using older version of MSAL component before, as it is not working on Amazon Fire tablets(no chrome) we upgraded to 2.3.1. It worked on Android, but on iOS we are facing this issue.

**Comment by bgavrilMS** [comment] 2018-11-09 13:03
@SravanthiKare - the current plan to do a release today or early next week.

**Comment by jennyf19** [comment] 2018-11-09 23:42
@AlexSchuetz @SravanthiKare 
Fixed in latest release [Msal2.4.0-preview](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/MSAL-v2.4.0).

**Closed by jennyf19** 2018-11-09 23:42 UTC
Labels: P1, bug, scenario:B2C, scenario:Mobile-iOS
