### ISSUE TITLE
Azure AD device Code Flow with personal accounts

### ISSUE THREAD

**Issue by reneschulte** [AzureAD/microsoft-authentication-library-for-dotnet#728] opened 2018-12-14 08:07 UTC
Azure AD v2 recently added support for device code flow for login but only for tenanted endpoints, but not personal accounts which are not supported at the moment (or only via a workaround that won’t work for us).
See docs here: 
https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-device-code

Is support for personal accounts planned and if so what is the timeline?

**Comment by jmprieur** [comment] 2018-12-15 14:16
@teichgraf : the library is ready, whenever the service implements it.
What is your scenario (to help pushing up the priorities on the service side)? are you building command line tools or portable tools and want to sign-in MSA accounts? can you please share more with us?

**Comment by teichgraf** [comment] 2018-12-17 07:46
We are trying to implement a login-flow for the HoloLens in order to access M365 Graph APIs and load data from there. For the HoloLens and it's limited text input UX we a need a login scenario without a browser on the HoloLens. For that we developed a companion website where the user logs in on his mobile or desktop computer, after that it shows a QR code and the HoloLens user just has to look at it to login (passing the token).

Is there (even a coarse) timeline when the service will support it? 

Let me know if you need more info @jmprieur

**Comment by paule96** [comment] 2019-01-09 17:47
hi @jmprieur,

I have a simular issue. I write a dotnet tool to list and download the onedrive albums. (because the website and the client can't handle big albums download (2000 Items and more per album))
But in a dotnet tool I can't open a browser. So I must use the device code flow.

**Comment by paule96** [comment] 2019-01-09 19:54
Oh and I have missed one detail. A dotnet core tool can only be build with dotnet core and not with full framework. :(

**Comment by StephenHodgson** [comment] 2019-01-22 21:33
Looking down into the code I noticed that we're [forcing the replacement of common with organizations for some reason](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/master/src/Microsoft.Identity.Client/Features/DeviceCode/DeviceCodeRequest.cs#L82). 

Could we get clarification if the discovery endpoint is online and availible to use so this work can be completed?

**Comment by 0k1** [comment] 2019-01-23 09:53
Authenticating all account users with device code flow is something of great interest. Hoping to have this [limitation](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Device-Code-Flow#Constraints) resolved soon.

**Comment by jmprieur** [comment] 2019-01-23 10:24
We hope that it will be available in this Quarter.

**Comment by 0k1** [comment] 2019-01-24 15:51
@jmprieur Will domain accounts also work within a different tenant then? Will we be able to sign in an external user without adding him to our tenant?

**Comment by jmprieur** [comment] 2019-01-24 16:31
@0k1 : I believe that this is already the case. If your app is multi-tenant (audience = organizations), this works already.
Did you see: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Device-Code-Flow#constraints ?

**Comment by 0k1** [comment] 2019-01-24 18:12
Confirmed. Thank you.

**Comment by paule96** [comment] 2019-04-20 19:53
@jmprieur was this issue fixed in the last Quarter? I need this feature so often and I can't use this so often...

**Comment by jmprieur** [comment] 2019-04-21 07:02
@paule96 : it's not a question of build/library. 
Work is currently happening service side (Azure AD v2.0 enpoint) to enable it

**Comment by paule96** [comment] 2019-05-18 19:31
@jmprieur any updates here? Is there any timeline or preview or something?

**Comment by jmprieur** [comment] 2019-05-21 09:46
@paule96 : the work is still in progress on the service. this will take a few months to come to production.

**Comment by paule96** [comment] 2019-06-19 07:12
Thx for your feedback :) I will stay tuned.

**Comment by rayluo** [comment] 2019-09-03 04:22
What changes are needed from client-side to use Device Flow with personal accounts (MSA)?

**Comment by jmprieur** [comment] 2019-09-03 07:02
@rayluo : When this is "fixed", just change the authority to be common instead of organizations
Today MSAL.NET core replaces common by organizations (for supportability reasons MSAL.NET replaces common by organizations internally: this is because the default authority is common, and until the service implements Device Code Flow for personal accounts, every single developer using MSAL with device code flow had an issue)

**Comment by bgavrilMS** [comment] 2019-09-03 07:16
@paule96 - you can use Interactive authentication in .Net core for a while now. MSAL will open whatever browser the OS defaults to to perform auth. Much better experience than device code flow for .NET Core.

**Comment by ashikns** [comment] 2019-09-03 07:48
@bgavrilMS I agree that addition of interactive to .Net core is great. Particularly for us it was a lifesaver since we managed to make it work in Unity as well. But it's hardly a replacement for a native flow.

**Comment by bgavrilMS** [comment] 2019-09-03 10:11
Thanks for the feedback @ashikns - we'll look at adding an embedded browser experience when .net core 3 ships. Not sure if that will help with Unity though.

**Comment by jennyf19** [comment] 2019-10-16 00:32
@reneschulte @rayluo @ashikns @0k1 @paule96 
This is included in the [4.5.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.5.0).

**Closed by jennyf19** 2019-10-16 00:32 UTC
Labels: Fixed, enhancement, question, scenario:Browserless device, service-enhancement

**Comment by StephenHodgson** [comment] 2019-10-16 12:20
Awesome 😎
