### ISSUE TITLE
[Bug] Bad magic number exception when signing in

### ISSUE THREAD

**Issue by timdriever** [AzureAD/microsoft-authentication-library-for-dotnet#2467] opened 2021-03-10 10:59 UTC
**Logs and Network traces**
```
Info	1-3-2021 10:35:06 +01:00	AzureAdAuthService	Attempting to sign in silently
Debug	1-3-2021 10:35:06 +01:00	AzureAdAuthService	Starting RequestTokenSilentWithTimeoutAsync
Info	1-3-2021 10:35:06 +01:00	AzureAdAuthTokenProvider	RequestTokenSilentAsync with scopes: api://****.default
Info	1-3-2021 10:35:06 +01:00	AzureAdAuthTokenProvider	RequestTokenSilentAsync with account: ***@***.nl
Error	1-3-2021 10:35:08 +01:00	AzureAdAuthTokenProvider	MsalException: MSAL.Xamarin.Android.4.27.0.0.MsalClientException: 
	ErrorCode: android_broker_operation_failed
Microsoft.Identity.Client.MsalClientException: Bad magic number for Bundle: 0x139193 ---> Java.Lang.IllegalStateException: Bad magic number for Bundle: 0x139193
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0008e] in <8b3b636835d84984ba4604c1f57b1983>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001f] in <8b3b636835d84984ba4604c1f57b1983>:0 
  at Android.Content.ContentResolver.Query (Android.Net.Uri uri, System.String[] projection, System.String selection, System.String[] selectionArgs, System.String sortOrder) [0x000aa] in <44e54a86dea24313a2bdb807df77c27a>:0 
  at Microsoft.Identity.Client.Platforms.Android.Broker.AndroidContentProviderBroker+<>c__DisplayClass23_0.<PerformContentResolverOperationAsync>b__0 () [0x00041] in <0e26de906a8248dd9fddc4acb51c8aca>:0 
  at System.Threading.Tasks.Task`1[TResult].InnerInvoke () [0x0000f] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:534 
  at System.Threading.Tasks.Task.Execute () [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2319 
--- End of stack trace from previous location where exception was thrown ---

  at Microsoft.Identity.Client.Platforms.Android.Broker.AndroidContentProviderBroker.PerformContentResolverOperationAsync (Microsoft.Identity.Client.Platforms.Android.Broker.ContentResolverOperation operation, System.String OperationParameters) [0x000dd] in <0e26de906a8248dd9fddc4acb51c8aca>:0 
  at Microsoft.Identity.Client.Platforms.Android.Broker.AndroidContentProviderBroker.AcquireTokenSilentFromBrokerInternalAsync (Microsoft.Identity.Client.Platforms.Android.Broker.BrokerRequest brokerRequest) [0x0008d] in <0e26de906a8248dd9fddc4acb51c8aca>:0 
  at Microsoft.Identity.Client.Platforms.Android.Broker.AndroidContentProviderBroker.AcquireTokenSilentViaBrokerAsync (Microsoft.Identity.Client.Platforms.Android.Broker.BrokerRequest brokerRequest) [0x00137] in <0e26de906a8248dd9fddc4acb51c8aca>:0 
  at Microsoft.Identity.Client.Platforms.Android.Broker.AndroidContentProviderBroker.AcquireTokenSilentInternalAsync (Microsoft.Identity.Client.Platforms.Android.Broker.BrokerRequest brokerRequest) [0x00075] in <0e26de906a8248dd9fddc4acb51c8aca>:0 
   --- End of inner exception stack trace ---
  at Microsoft.Identity.Client.Platforms.Android.Broker.AndroidBrokerHelper.HandleBrokerOperationError (System.Exception ex) [0x0002c] in <0e26de906a8248dd9fddc4acb51c8aca>:0 
  at Microsoft.Identity.Client.Platforms.Android.Broker.AndroidContentProviderBroker.AcquireTokenSilentInternalAsync (Microsoft.Identity.Client.Platforms.Android.Broker.BrokerRequest brokerRequest) [0x00093] in <0e26de906a8248dd9fddc4acb51c8aca>:0 
  at Microsoft.Identity.Client.Platforms.Android.Broker.AndroidContentProviderBroker.AcquireTokenSilentAsync (Microsoft.Identity.Client.Internal.Requests.AuthenticationRequestParameters authenticationRequestParameters, Microsoft.Identity.Client.ApiConfig.Parameters.AcquireTokenSilentParameters acquireTokenSilentParameters) [0x000f1] in <0e26de906a8248dd9fddc4acb51c8aca>:0 
  at Microsoft.Identity.Client.Internal.Requests.BrokerSilentStrategy.SendTokenRequestToBrokerAsync () [0x000b9] in <0e26de906a8248dd9fddc4acb51c8aca>:0 
  at Microsoft.Identity.Client.Internal.Requests.BrokerSilentStrategy.ExecuteAsync (System.Threading.CancellationToken cancellationToken) [0x00079] in <0e26de906a8248dd9fddc4acb51c8aca>:0 
  at Microsoft.Identity.Client.Internal.Requests.Silent.SilentRequest.ExecuteAsync (System.Threading.CancellationToken cancellationToken) [0x00235] in <0e26de906a8248dd9fddc4acb51c8aca>:0 
  at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync (System.Threading.CancellationToken cancellationToken) [0x0016a] in <0e26de906a8248dd9fddc4acb51c8aca>:0 
  at Microsoft.Identity.Client.ApiConfig.Executors.ClientApplicationBaseExecutor.ExecuteAsync (Microsoft.Identity.Client.ApiConfig.Parameters.AcquireTokenCommonParameters commonParameters, Microsoft.Identity.Client.ApiConfig.Parameters.AcquireTokenSilentParameters silentParameters, System.Threading.CancellationToken cancellationToken) [0x000d5] in <0e26de906a8248dd9fddc4acb51c8aca>:0 
  at ***.Droid.Services.AzureAdAuthTokenProvider.RequestTokenSilentAsync (System.Collections.Generic.IEnumerable`1[T] scopes, Microsoft.Identity.Client.IAccount account, System.Threading.CancellationToken cancellationToken) [0x00092] in <f62df1b4527c4c63bcd9a4d76cb45420>:0 
  at ***.AzureAd.Droid.Services.AzureAdAuthTokenProvider.RequestTokenSilentAsync (System.Collections.Generic.IEnumerable`1[T] scopes, System.String username, System.Threading.CancellationToken cancellationToken) [0x00192] in <f62df1b4527c4c63bcd9a4d76cb45420>:0 
Inner Exception: Java.Lang.IllegalStateException: Bad magic number for Bundle: 0x139193
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0008e] in <8b3b636835d84984ba4604c1f57b1983>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001f] in <8b3b636835d84984ba4604c1f57b1983>:0 
  at Android.Content.ContentResolver.Query (Android.Net.Uri uri, System.String[] projection, System.String selection, System.String[] selectionArgs, System.String sortOrder) [0x000aa] in <44e54a86dea24313a2bdb807df77c27a>:0 
  at Microsoft.Identity.Client.Platforms.Android.Broker.AndroidContentProviderBroker+<>c__DisplayClass23_0.<PerformContentResolverOperationAsync>b__0 () [0x00041] in <0e26de906a8248dd9fddc4acb51c8aca>:0 
  at System.Threading.Tasks.Task`1[TResult].InnerInvoke () [0x0000f] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:534 
  at System.Threading.Tasks.Task.Execute () [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2319 
--- End of stack trace from previous location where exception was thrown ---

  at Microsoft.Identity.Client.Platforms.Android.Broker.AndroidContentProviderBroker.PerformContentResolverOperationAsync (Microsoft.Identity.Client.Platforms.Android.Broker.ContentResolverOperation operation, System.String OperationParameters) [0x000dd] in <0e26de906a8248dd9fddc4acb51c8aca>:0 
  at Microsoft.Identity.Client.Platforms.Android.Broker.AndroidContentProviderBroker.AcquireTokenSilentFromBrokerInternalAsync (Microsoft.Identity.Client.Platforms.Android.Broker.BrokerRequest brokerRequest) [0x0008d] in <0e26de906a8248dd9fddc4acb51c8aca>:0 
  at Microsoft.Identity.Client.Platforms.Android.Broker.AndroidContentProviderBroker.AcquireTokenSilentViaBrokerAsync (Microsoft.Identity.Client.Platforms.Android.Broker.BrokerRequest brokerRequest) [0x00137] in <0e26de906a8248dd9fddc4acb51c8aca>:0 
  at Microsoft.Identity.Client.Platforms.Android.Broker.AndroidContentProviderBroker.AcquireTokenSilentInternalAsync (Microsoft.Identity.Client.Platforms.Android.Broker.BrokerRequest brokerRequest) [0x00075] in <0e26de906a8248dd9fddc4acb51c8aca>:0 
  --- End of managed Java.Lang.IllegalStateException stack trace ---
java.lang.IllegalStateException: Bad magic number for Bundle: 0x139193
	at android.os.Parcel.createException(Parcel.java:1974)
	at android.os.Parcel.readException(Parcel.java:1934)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
	at android.content.ContentResolver.query(ContentResolver.java:809)
	at android.content.ContentResolver.query(ContentResolver.java:759)
	at android.content.ContentResolver.query(ContentResolver.java:717)
```
**Which Version of MSAL are you using ?**
MSAL 4.27.0

**Platform**
Xamarin.Android

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [x] Silent
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App 
    * [ ] Authorization code
    * [ ] OBO
* Daemon App 
    * [ ] Service to Service call

**Is this a new or existing app?**
The app is in production (MSAL 4.24.0), and I have upgraded to a new version of MSAL (4.27.0)

**Repro**
Happens sometimes when signing in. When it happens it keeps happening.

This is the code we use for aquire token silent:

```
var accounts = await _client.GetAccountsAsync().ConfigureAwait(false);
var account = accounts?.FirstOrDefault(x => x.Username == username);

var authResult = await _client
                .AcquireTokenSilent(scopes, account)
                .ExecuteAsync(cancellationToken)
                .ConfigureAwait(false);
```

**Comment by bgavrilMS** [comment] 2021-03-10 11:31
Android error messages are funny ... 

We changed the method of communication between MSAL and Authenticator from AccountManager to ContentProvider. This exception seems related to Content Provider. 

If you catch this exception and login interactively, do subsequent silent calls fail?

**Comment by timdriever** [comment] 2021-03-10 12:35
> Android error messages are funny ...
> 
> We changed the method of communication between MSAL and Authenticator from AccountManager to ContentProvider. This exception seems related to Content Provider.
> 
> If you catch this exception and login interactively, do subsequent silent calls fail?

Thanks for your response. I don't know what will happen if we catch this exception. Unfortunately that is now difficult, because we have already rolled back the code.

**Comment by trwalke** [comment] 2021-03-12 07:28
This looks to me like it may be a result of a malformed request bundle. Might be a good idea to start looking here. (https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/7dc1b3c0510c306c19fba6cfb73c984d829cc83c/src/client/Microsoft.Identity.Client/Platforms/Android/Broker/AndroidContentProviderBroker.cs#L218)
More investigation needed.

**Comment by trwalke** [comment] 2021-03-22 15:56
@timdriever 
So far I cannot reproduce, can you perform an interactive sign in, then try using acquire token silent and sending the broker logs (https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Broker-Troubleshooting)

I want to see what account data is being returned from the broker and used for the silent call

**Comment by bgavrilMS** [comment] 2021-04-08 17:21
Closing as cannot repro, please send us broker logs if you manage to repro yourself.

**Closed** 2021-04-08 17:21 UTC
Labels: P2, android-broker, bug, scenario:Mobile-Android
