### ISSUE TITLE
AcquireTokenAsync throws exception after the WebBrowser Intent redirects to the application scheme uri

### ISSUE THREAD

**Issue by ameem85** [AzureAD/microsoft-authentication-library-for-dotnet#601] opened 2018-08-14 19:33 UTC
When I use `FormsAppCompatActivity ` instead of `FormsApplicationActivity`, the exception is thrown at the following line of code:

`var result = await App.AcquireTokenAsync(new string[]{"User.Read"}, associatedActivityUiParent);`

The above call does launch the web browser intent, and I am able to complete the authentication flow in the browser. But when the browser redirects back to the android activity, the above awaited function call throws the exception, with the following stack trace:

 ```
at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.VerifyAuthorizationResult () [0x0009f] in <83f99aa6884c4981bdf70ccbec168bcb>:0 
  at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest+<PreTokenRequestAsync>d__9.MoveNext () [0x000dd] in <83f99aa6884c4981bdf70ccbec168bcb>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at Microsoft.Identity.Client.Internal.Requests.RequestBase+<RunAsync>d__33.MoveNext () [0x0032e] in <83f99aa6884c4981bdf70ccbec168bcb>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at Microsoft.Identity.Client.PublicClientApplication+<AcquireTokenForLoginHintCommonAsync>d__10.MoveNext () [0x000d3] in <83f99aa6884c4981bdf70ccbec168bcb>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at Microsoft.Identity.Client.PublicClientApplication+<AcquireTokenAsync>d__2.MoveNext () [0x0009b] in <83f99aa6884c4981bdf70ccbec168bcb>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at RetailData.Client.Core.Authentication.AuthenticationService+<GetAuthenticationTokenAsync>d__6.MoveNext () [0x001b3] in C:\dev\retail-data\RetailData.Client.Core\Authentication\AuthenticationService.cs:60 
	ErrorCode: unknown_error
	StatusCode: 0
	Claims: 
```

The application works fine if `FormsApplicationActivity` is used instead of `FormsAppCompatActivity`.

**Comment by jennyf19** [comment] 2019-07-05 23:45
@ameem85 Sorry this issue was not responded to faster. I was not able to reproduce this using `FormsAppCompatActivity` . If it's still relevant, please try w/the latest release of MSAL 4.1, and see if it still repros there. Here's [how to update from msalv2 to v3](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/MSAL.NET-3-released#configuring-an-app-got-simpler) and there will, most likely be no further changes for you targeting [v4](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/msal-net-4#msalnet-40-released).

**Comment by jmprieur** [comment] 2019-07-16 17:48
Moving to 4.3. We need more info.

**Comment by henrik-me** [comment] 2019-07-16 20:54
@ameem85 : Closing, please provide additional info an re-open. Moving out of milestone.

**Closed by henrik-me** 2019-07-16 20:54 UTC
Labels: bug, no-repro, requires more info, scenario:Mobile-Android
