### ISSUE TITLE
[Bug] UWP Hololens application stopped getting past entering email and shows a blank UI

### ISSUE THREAD

**Issue by XRMech** [AzureAD/microsoft-authentication-library-for-dotnet#4747] opened 2024-05-07 16:30 UTC
### Library version used

uap 10.0 vesion 4.16.0.0

### .NET version

Unity 2019.4.14f, .Net 4.X

### Scenario

Other - please specify

### Is this a new or an existing app?

The app is in production, I haven't upgraded MSAL, but started seeing this issue

### Issue description and reproduction steps

In our unity UWP hololens application, once we enter the email address, the UI changes to a white screen and does not proceed to entering the password.  When using device code, it presents the device code, but once authenticating on another device and approving, it no longer finishes logging in.  Our android version off the application and the editor versions both still work using device code.  Only the UWP version has stopped working. 

### Relevant code snippets

```csharp
the code never gets past this line.
var authResult = await identityClientApp.AcquireTokenInteractive(grantScopes).ExecuteAsync();
```

### Expected behavior

Once the email is entered, the password UI should show up.

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

### Regression

4.16.0.0

### Solution and workarounds

None found

**Comment by bgavrilMS** [comment] 2024-05-13 08:36
This is typically a service error. I recommend you open a ticket via Azure.

**Comment by localden** [comment] 2024-05-19 01:54
@XRMech to echo what @bgavrilMS is saying, this does not sound like an issue with MSAL - the library does not handle rendering of the authentication content. Can you confirm whether the issue is still reproducible?

**Comment by bgavrilMS** [comment] 2024-05-20 08:42
Closing as we no longer support UWP and this would not qualify for a hotfix.
Please use net8 in Unity

**Closed by bgavrilMS** 2024-05-20 08:42 UTC
Labels: bug, requires more info, public-client

**Comment by XRMech** [comment] 2024-05-28 19:56
I am still having the problem, and have a ticket in with Azure (2405160050004719).  I am trying to see what other options I have before sinking 80 hours into migrating versions and working through the package dependency issues I saw when I tried importing the Microsoft.Graph package into the latest Unity Editor version.
