### ISSUE TITLE
Bump Xamarin.Android.Support Libraries to 25.4.0.2+ to prevent Mono Linker issues

### ISSUE THREAD

**Issue by JonDouglas** [AzureAD/microsoft-authentication-library-for-dotnet#476] opened 2017-10-02 16:07 UTC
Because the current `1.1.0-preview` version of `Microsoft.Identity.Client` has a loose dependency on Xamarin.Android.Support libraries of `>= 23.3.0`, the `LinkAssemblies` task within Xamarin will fail because it expects a definition of:

`LaunchUrl(Activity context, Uri url)`

instead of the newer definition which is typically installed (i.e. 25+):

`LaunchUrl(Context context, Uri url)`

In other words, the following line fails by the Linker because the method definition does not exist as it has changed between `23.3.0` and `26.0.2-beta1` (I have not looked to see exactly where it changed): 

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/d4bf6084e92091a8c89ce08a068a0a98103ff983/src/Microsoft.Identity.Client/Platforms/Android/AuthenticationActivity.cs#L145

Thus the following should be bumped higher:

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/master/src/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj#L134-L135

**Context:**
https://bugzilla.xamarin.com/show_bug.cgi?id=59886

**Comment by kpanwar** [comment] 2017-10-02 16:10
@JonDouglas - this is a duplicate of #443. We already have a 1.1.1-alpha out on myget with the fix

**Closed by kpanwar** 2017-10-02 16:10 UTC
