### ISSUE TITLE
[Feature Request] Improve the error message when people use .WithAzureRegion(region) locally.

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#2739] opened 2021-07-02 13:30 UTC
**Is your feature request related to a problem? Please describe.**
Partners try to run their services locally, and get the following exception:

```Text
AADSTS100007: Regional Cache Auth Service token requests for audience App that is not MSI are forbidden
```

and they are confused as this is not actionable.

**Describe the solution you'd like**
- work with EVO to improve the error message and have it more actionable (with an aka.ms link) | my preferred option. @hpsin can we do that?

**Describe alternatives you've considered**
MSAL.NET could catch this particular error code and throw a more meaningful exception with an aka.ms link ... but that's not ideal

**Additional context**
Partners are also confused by the following message when debugging:

False MSAL 4.33.0.0 MSAL.Desktop Windows 10 Enterprise [07/01 18:26:29.13 - 2a8dbdf4-426d-41ee-b387-be0a650d1a00] [Region discovery] Auto-discovery failed.

we need to document that this is this a normal behavior.

**Comment by bgavrilMS** [comment] 2021-09-17 14:24
Possible duplicate of the MSAL-only work: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2884

**Comment by bgavrilMS** [comment] 2022-07-28 14:33
This was fixed by the partner.

**Closed by bgavrilMS** 2022-07-28 14:33 UTC
Labels: enhancement, Feature Request, Supportability
